@startuml
class JsonString <<static>> {
    + {static} Escape(s:String, w:IStore) : void
    + {static} Escape(s:Utf8String, w:IStore) : void
    + {static} Escape(s:String) : string
    + {static} Quote(s:String, w:IStore) : void
    + {static} Quote(s:Utf8String, w:IStore) : void
    + {static} Quote(s:string) : string
    + {static} Quote(s:Utf8String) : Utf8String
    + {static} Unescape(src:string, w:IStore) : int
    + {static} Unescape(s:Utf8String, w:IStore) : int
    + {static} Unescape(src:string) : string
    + {static} Unquote(src:string, w:IStore) : int
    + {static} Unquote(src:Utf8String, w:IStore) : int
    + {static} Unquote(src:string) : string
    + {static} Unquote(src:Utf8String) : Utf8String
}
@enduml
