@startuml
class UniGLTFPreference <<static>> {
    + <<const>> UNIGLTF_ENABLE_ZIPARCHVIE_IMPORTER : string = "UNIGLTF_ENABLE_ZIPARCHVIE_IMPORTER"
    + {static} HasSymbol(symbol:string) : bool
    + {static} AddSymbol(symbol:string) : void
    + {static} RemoveSymbol(symbol:string) : void
    + {static} ToggleSymbol(title:string, symbol:string) : void
}
UniGLTFPreference --> "GltfIOAxis" Axes
@enduml
