@startuml
class FastSpringBoneBuffer {
    + IsDisposed : bool <<get>>
    + <<unsafe>> FastSpringBoneBuffer(springs:IReadOnlyList<FastSpringBoneSpring>, externalData:BlittableExternalData, simulateLastBone:bool)
    + Dispose() : void
}
class "NativeArray`1"<T> {
}
IDisposable <|-- FastSpringBoneBuffer
FastSpringBoneBuffer --> "Springs<BlittableSpring>" "NativeArray`1"
FastSpringBoneBuffer --> "Joints<BlittableJoint>" "NativeArray`1"
FastSpringBoneBuffer --> "Colliders<BlittableCollider>" "NativeArray`1"
FastSpringBoneBuffer --> "Logics<BlittableLogic>" "NativeArray`1"
FastSpringBoneBuffer --> "BlittableTransforms<BlittableTransform>" "NativeArray`1"
FastSpringBoneBuffer --> "ExternalData" BlittableExternalData
@enduml
