@startuml
struct FastSpringBoneJoint {
}
FastSpringBoneJoint --> "Transform" Transform
FastSpringBoneJoint --> "Joint" BlittableJoint
FastSpringBoneJoint --> "DefaultLocalRotation" Quaternion
@enduml
