@startuml
class MigrationVrm <<static>> {
    + {static} Migrate(vrm0bytes:byte[], meta:VRM10ObjectMeta, modGltf:Action<UniGLTF.glTF>) : byte[]
    + {static} Migrate(data:GltfData, meta:VRM10ObjectMeta, modGltf:Action<UniGLTF.glTF>) : byte[]
    + {static} CreateMeshToNode(gltf:UniGLTF.glTF) : MeshIndexToNodeIndexFunc
    + {static} Check(vrm0:JsonNode, vrm1:UniGLTF.Extensions.VRMC_vrm.VRMC_vrm, meshToNode:MeshIndexToNodeIndexFunc) : void
    + {static} Check(vrm0:JsonNode, vrm1:UniGLTF.Extensions.VRMC_springBone.VRMC_springBone, nodes:List<glTFNode>) : void
}
@enduml
