@startuml
class MigrationVrmExpression <<static>> {
    + <<const>> COLOR_PROPERTY : string = "_Color"
    + <<const>> EMISSION_COLOR_PROPERTY : string = "_EmissionColor"
    + <<const>> RIM_COLOR_PROPERTY : string = "_RimColor"
    + <<const>> OUTLINE_COLOR_PROPERTY : string = "_OutlineColor"
    + <<const>> SHADE_COLOR_PROPERTY : string = "_ShadeColor"
    + {static} Migrate(gltf:UniGLTF.glTF, json:JsonNode, meshToNode:MigrationVrm.MeshIndexToNodeIndexFunc) : IEnumerable<(ExpressionPreset, string, UniGLTF.Extensions.VRMC_vrm.Expression)>
    + {static} Check(vrm0:JsonNode, vrm1:UniGLTF.Extensions.VRMC_vrm.Expressions, meshToNode:MigrationVrm.MeshIndexToNodeIndexFunc) : void
}
@enduml
