@startuml
class Vrm0XVersion <<static>> {
    + {static} IsNewer(newer:string, older:string) : bool
    + {static} IsNewer(newerVersion:Version, olderVersion:Version) : bool
    + {static} ParseVersion(version:string, v:Version) : bool
}
struct Version {
    + Major : int
    + Minor : int
    + Patch : int
    + Pre : string
}
Vrm0XVersion +-- Version
@enduml
