@startuml
class FastSpringBoneService {
    + {static} Free() : void
}
MonoBehaviour <|-- FastSpringBoneService
FastSpringBoneService --> "RootBoneRegistry" RootBoneRegistry
FastSpringBoneService --> "TransformRegistry" TransformRegistry
FastSpringBoneService --> "ColliderGroupRegistry" ColliderGroupRegistry
FastSpringBoneService --> "FastSpringBoneScheduler" FastSpringBoneScheduler
FastSpringBoneService --> "Instance" FastSpringBoneService
@enduml
