@startuml
class FastSpringRootBone <<sealed>> {
    + FastSpringRootBone(transformRegistry:TransformRegistry, transform:Transform, rootBoneRegistry:RootBoneRegistry, colliderGroupRegistry:ColliderGroupRegistry)
    + <<unsafe>> Initialize(gravityPower:float, gravityDir:Vector3, dragForce:float, stiffnessForce:float, colliderGroups:IReadOnlyList<FastSpringBoneColliderGroup>, radius:float, center:Transform) : void
    + Dispose() : void
}
class "IReadOnlyList`1"<T> {
}
IDisposable <|-- FastSpringRootBone
FastSpringRootBone --> "ColliderGroups<FastSpringBoneColliderGroup>" "IReadOnlyList`1"
@enduml
