@startuml
class glTF_KHR_materials_unlit {
    + <<const>> ExtensionName : string = "KHR_materials_unlit"
    + {static} CreateDefault() : glTFMaterial
    + {static} IsEnable(m:glTFMaterial) : bool
    + {static} Serialize(materialExtensions:glTFExtension) : void
    + {static} ForTest() : glTFExtensionImport
}
glTF_KHR_materials_unlit o-> "ExtensionNameUtf8" Utf8String
@enduml
