@startuml
class glTF_KHR_texture_transform {
    + <<const>> ExtensionName : string = "KHR_texture_transform"
    + rotation : float
    + texCoord : int
    + {static} TryGet(info:glTFTextureInfo, t:glTF_KHR_texture_transform) : bool
    + {static} Serialize(info:glTFTextureInfo, offset:(float, float), scale:(float, float)) : void
}
glTF_KHR_texture_transform o-> "ExtensionNameUt8" Utf8String
@enduml
