@startuml
enum Axes {
    Z,
    X,
}
interface IAxisInverter {
}
struct ReverseZ {
    + InvertMat4(src:Matrix4x4) : Matrix4x4
    + InvertQuaternion(src:Quaternion) : Quaternion
    + InvertVector3(src:Vector3) : Vector3
    + InvertVector4(src:Vector4) : Vector4
}
struct ReverseX {
    + InvertMat4(src:Matrix4x4) : Matrix4x4
    + InvertQuaternion(src:Quaternion) : Quaternion
    + InvertVector3(src:Vector3) : Vector3
    + InvertVector4(src:Vector4) : Vector4
}
class AxisesExtensions <<static>> {
    + {static} Create(axis:Axes) : IAxisInverter
}
IAxisInverter <|-- ReverseZ
IAxisInverter <|-- ReverseX
@enduml
