@startuml
struct Byte4 {
    + <<readonly>> x : byte
    + <<readonly>> y : byte
    + <<readonly>> z : byte
    + <<readonly>> w : byte
    + Byte4(_x:byte, _y:byte, _z:byte, _w:byte)
    + Equals(other:Byte4) : bool
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<Byte4>" <|-- Byte4
@enduml
