@startuml
class glbImporter <<static>> {
    + <<const>> GLB_MAGIC : string = "glTF"
    + <<const>> GLB_VERSION : float = 2.0f
    + {static} ToChunkType(src:string) : GlbChunkType
    + {static} ToChunkTypeString(type:GlbChunkType) : string
    + {static} ParseGlbChanks(bytes:Byte[]) : List<GlbChunk>
    + {static} ParseGlbChunks(bytes:Byte[]) : List<GlbChunk>
}
@enduml
