@startuml
class GltfData <<sealed>> {
    + TargetPath : string <<get>>
    + Json : string <<get>>
    + GltfData(targetPath:string, json:string, gltf:glTF, chunks:IReadOnlyList<GlbChunk>, storage:IStorage, migrationFlags:MigrationFlags)
    + Dispose() : void
    + {static} CreateFromExportForTest(data:ExportingGltfData) : GltfData
    + {static} CreateFromGltfDataForTest(gltf:glTF, bytes:ArraySegment<byte>) : GltfData
    + GetBytesFromBuffer(bufferIndex:int) : NativeArray<Byte>
    + GetBytesFromBufferView(bufferView:int) : NativeArray<Byte>
    + GetIndicesFromAccessorIndex(accessorIndex:int) : BufferAccessor
    + GetArrayFromAccessor(accessorIndex:int) : NativeArray<T>
    + FlatternFloatArrayFromAccessor(accessorIndex:int) : NativeArray<float>
    + GetBytesFromImage(imageIndex:int) : (NativeArray<byte> binary, string mimeType)?
    + HasVertexColor(attributes:glTFAttributes) : bool
    + MaterialHasVertexColor(materialIndex:int) : bool
}
class "IReadOnlyList`1"<T> {
}
class "NativeArray`1"<T> {
}
IDisposable <|-- GltfData
GltfData --> "Chunks<GlbChunk>" "IReadOnlyList`1"
GltfData --> "GLTF" glTF
GltfData o-> "NativeArrayManager" NativeArrayManager
GltfData --> "Bin<byte>" "NativeArray`1"
GltfData --> "MigrationFlags" MigrationFlags
@enduml
