@startuml
class GltfExportSettings {
    + DivideVertexBuffer : bool
    + UseSparseAccessorForMorphTarget : bool
    + ExportOnlyBlendShapePosition : bool
    + ExportTangents : bool
    + KeepVertexColor : bool
}
GltfExportSettings o-> "InverseAxis" Axes
GltfExportSettings o-> "MeshFilterAllowedHideFlags" HideFlags
@enduml
