@startuml
class ImporterContextSpeedLog {
    + MeasureTime(key:string) : IDisposable
    + GetSpeedLog() : string
}
struct KeyElapsed {
    + Key : string
    + KeyElapsed(key:string, elapsed:TimeSpan)
}
struct MeasureScope {
    + MeasureScope(onDispose:Action)
    + Dispose() : void
}
class "List`1"<T> {
}
ImporterContextSpeedLog o-> "m_speedReports<KeyElapsed>" "List`1"
ImporterContextSpeedLog +-- KeyElapsed
KeyElapsed --> "Elapsed" TimeSpan
ImporterContextSpeedLog +-- MeasureScope
IDisposable <|-- MeasureScope
@enduml
