@startuml
interface INativeArrayManager {
}
class NativeArrayManager {
    + Dispose() : void
    + NativeArrayManager()
    + CreateNativeArray(size:int) : NativeArray<T>
    + CreateNativeArray(data:ArraySegment<T>) : NativeArray<T>
    + CreateNativeArray(data:T[]) : NativeArray<T>
    + Convert(src:NativeArray<TSrc>, convert:Func<TSrc, TDst>) : NativeArray<TDst>
}
INativeArrayManager <|-- NativeArrayManager
IDisposable <|-- NativeArrayManager
@enduml
