@startuml
struct ExportProgress {
    + <<readonly>> Title : string
    + <<readonly>> Message : string
    + <<readonly>> Progress : float
    + ExportProgress(title:string, message:string, progress:float)
}
class NullProgress {
    + Report(value:ExportProgress) : void
}
class "IProgress`1"<T> {
}
"IProgress`1" "<ExportProgress>" <|-- NullProgress
@enduml
