@startuml
struct UShort2 {
    + <<readonly>> x : ushort
    + <<readonly>> y : ushort
    + UShort2(_x:ushort, _y:ushort)
    + Equals(other:UShort2) : bool
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<UShort2>" <|-- UShort2
@enduml
