@startuml
class HierarchyValidator <<static>> {
    + {static} ValidateRoot(ExportRoot:GameObject) : IEnumerable<Validation>
    + {static} Validate(ExportRoot:GameObject) : IEnumerable<Validation>
}
enum ExportValidatorMessages {
    ROOT_EXISTS,
    NO_PARENT,
    NO_ACTIVE_MESH,
    DUPLICATE_BONE_NAME_EXISTS,
    NO_UNIQUE_JOINTS,
}
HierarchyValidator +-- ExportValidatorMessages
@enduml
