@startuml
class HumanoidValidator <<static>> {
    + {static} HasRotationOrScale(root:GameObject) : bool
    + {static} EnableFreeze : bool
    + {static} Validate_Normalize(ExportRoot:GameObject) : IEnumerable<Validation>
    + {static} Validate_TPose(ExportRoot:GameObject) : IEnumerable<Validation>
}
enum ValidationMessages {
    ROTATION_OR_SCALEING_INCLUDED_IN_NODE,
    IS_POSE_FREEZE_DONE,
    NO_ANIMATOR,
    FACE_Z_POSITIVE_DIRECTION,
    NOT_TPOSE,
    NO_AVATAR_IN_ANIMATOR,
    AVATAR_IS_NOT_VALID,
    AVATAR_IS_NOT_HUMANOID,
    JAW_BONE_IS_INCLUDED,
}
class "IReadOnlyList`1"<T> {
}
HumanoidValidator --> "MeshInformations<UniGLTF.MeshExportInfo>" "IReadOnlyList`1"
HumanoidValidator +-- ValidationMessages
@enduml
