@startuml
class FootTarget_Editor {
    + OnEnable() : void
    + OnDisable() : void
    + <<override>> OnInspectorGUI() : void
    + {static} Inspector(footTarget:FootTarget, name:string) : FootTarget
    + {static} GetHumanoid(target:HumanoidTarget) : HumanoidControl
    + OnSceneGUI() : void
}
abstract class TargetProps {
    + TargetProps(serializedObject:SerializedObject, _sensor:LegSensor, _footTarget:FootTarget, unitySensorName:string)
    + <<virtual>> SetSensor2Target() : void
    + {abstract} Inspector() : void
}
Editor <|-- FootTarget_Editor
FootTarget_Editor +-- TargetProps
TargetProps --> "enabledProp" SerializedProperty
TargetProps --> "sensorComponentProp" SerializedProperty
TargetProps --> "sensor2TargetPositionProp" SerializedProperty
TargetProps --> "sensor2TargetRotationProp" SerializedProperty
TargetProps --> "footTarget" FootTarget
TargetProps --> "sensor" LegSensor
@enduml
