@startuml
class HandTarget_Editor {
    + OnEnable() : void
    + OnDisable() : void
    + <<override>> OnInspectorGUI() : void
    + {static} Inspector(handTarget:HandTarget, name:string) : HandTarget
    + {static} GetHumanoid(target:HumanoidTarget) : HumanoidControl
    + showControllers : bool = true
    + showSettings : bool
}
abstract class TargetProps {
    + TargetProps(serializedObject:SerializedObject, _sensor:Humanoid.ArmSensor, _handTarget:HandTarget, unitySensorName:string)
    + <<virtual>> SetSensor2Target() : void
    + {abstract} Inspector() : void
}
Editor <|-- HandTarget_Editor
HandTarget_Editor o-> "selectedBone" BonePose
HandTarget_Editor +-- TargetProps
TargetProps --> "enabledProp" SerializedProperty
TargetProps --> "sensorComponentProp" SerializedProperty
TargetProps --> "sensor2TargetPositionProp" SerializedProperty
TargetProps --> "sensor2TargetRotationProp" SerializedProperty
TargetProps --> "handTarget" HandTarget
@enduml
