@startuml
class HeadTarget_Editor {
    + OnEnable() : void
    + OnDisable() : void
    + <<override>> OnInspectorGUI() : void
    + OnSceneGUI() : void
}
abstract class TargetProps {
    + TargetProps(serializedObject:SerializedObject, _sensor:HeadSensor, _headTarget:HeadTarget, unitySensorName:string)
    + <<virtual>> SetSensor2Target() : void
    + {abstract} Inspector() : void
}
Editor <|-- HeadTarget_Editor
HeadTarget_Editor +-- TargetProps
TargetProps --> "enabledProp" SerializedProperty
TargetProps --> "sensorComponentProp" SerializedProperty
TargetProps --> "sensor2TargetPositionProp" SerializedProperty
TargetProps --> "sensor2TargetRotationProp" SerializedProperty
TargetProps --> "headTarget" HeadTarget
TargetProps --> "sensor" HeadSensor
@enduml
