@startuml
class EnumSerialization {
    + IsInline : bool <<get>>
    + <<override>> ToString() : string
    + EnumSerialization(t:Type, serializationType:EnumSerializationType)
    + GenerateDeserializer(writer:StreamWriter, callName:string) : void
    + GenerateDeserializerCall(callName:string, argName:string) : string
    + CreateSerializationCondition(argName:string, t:JsonSchemaAttribute) : string
    + GenerateSerializer(writer:StreamWriter, callName:string) : void
    + GenerateSerializerCall(callName:string, argName:string) : string
}
IValueSerialization <|-- EnumSerialization
EnumSerialization --> "ValueType" Type
@enduml
