@startuml
class ExtensionSerialization {
    + IsInline : bool <<get>>
    + GenerateDeserializer(writer:StreamWriter, callName:string) : void
    + GenerateDeserializerCall(callName:string, argName:string) : string
    + CreateSerializationCondition(argName:string, t:JsonSchemaAttribute) : string
    + GenerateSerializer(writer:StreamWriter, callName:string) : void
    + GenerateSerializerCall(callName:string, argName:string) : string
}
IValueSerialization <|-- ExtensionSerialization
ExtensionSerialization --> "ValueType" Type
@enduml
