@startuml
class FieldSerializationInfo {
    + Name : string <<get>>
    + Path : string <<get>>
    + FunctionName : string <<get>>
    + FieldSerializationInfo(fi:FieldInfo, path:string, prefix:string)
    + <<override>> ToString() : string
}
FieldSerializationInfo --> "FieldInfo" FieldInfo
FieldSerializationInfo --> "Attribute" JsonSchemaAttribute
FieldSerializationInfo --> "Serialization" IValueSerialization
@enduml
