@startuml
class ListSerialization {
    + ListSerialization(t:Type, inner:IValueSerialization)
    + <<override>> ToString() : string
    + <<override>> GenerateDeserializer(writer:StreamWriter, callName:string) : void
    + <<override>> CreateSerializationCondition(argName:string, t:JsonSchemaAttribute) : string
    + <<override>> GenerateSerializer(writer:StreamWriter, callName:string) : void
}
CollectionSerializationBase <|-- ListSerialization
@enduml
