@startuml
class ControllerEventHandlers {
    + ControllerEventHandlers()
    + defaultParameterProperty : string
    + floatValue : float <<get>> <<set>>
    + {static} Cleanup(eventHandlers:ControllerEventHandlers[]) : void
    + Clear() : void
    + SetMethod(eventType:EventHandler.Type, voidEvent:UnityAction) : void
    + SetMethod(eventType:EventHandler.Type, boolEvent:UnityAction<bool>) : void
}
class ControllerEventHandler {
    + ControllerEventHandler(gameObject:UnityEngine.GameObject, eventType:Type)
    + label : string
    + <<virtual>> floatValue : float <<get>> <<set>>
    + <<virtual>> floatValue2 : float <<get>> <<set>>
    + stringValue : string
    + <<override>> Update() : void
}
class "EventHandlers`1"<T> {
}
class UnityPoseFloatEvent {
}
class "UnityEvent`2"<T1,T2> {
}
"EventHandlers`1" "<ControllerEventHandler>" <|-- ControllerEventHandlers
FloatEvent <|-- ControllerEventHandler
ControllerEventHandler --> "poseFloatEvent" UnityPoseFloatEvent
ControllerEventHandler +-- UnityPoseFloatEvent
"UnityEvent`2" "<Humanoid.Pose,float>" <|-- UnityPoseFloatEvent
@enduml
