@startuml
class IntEventHandlers {
    + value : int <<get>> <<set>>
}
class IntEventHandler {
    + IntEventHandler()
    + IntEventHandler(eventType:Type)
    + minValue : int
    + maxValue : int
    + intTriggerLow : int = 0
    + intTriggerHigh : int = 1
    + multiplicationFactor : int = 1
    + <<virtual>> value : int <<get>> <<set>>
}
class "EventHandlers`1"<T> {
}
"EventHandlers`1" "<IntEventHandler>" <|-- IntEventHandlers
EventHandler <|-- IntEventHandler
@enduml
