@startuml
class PinchInteraction {
    + pinching : bool
    + {static} pinchDistance : float = 0.04F
    + PinchCheck(handTarget:HandTarget, pinchSocket:Socket, obj:GameObject) : void
    + {static} IsPinching(handTarget:HandTarget) : bool
    + {static} IsNotPinching(handTarget:HandTarget) : bool
    + {static} Pinch(handTarget:HandTarget, obj:GameObject) : void
    + {static} PinchDropCheck(handTarget:HandTarget, pinchSocket:Socket) : void
}
MonoBehaviour <|-- PinchInteraction
@enduml
