@startuml
class MaterialDescriptor <<sealed>> {
    + <<readonly>> Name : string
    + <<readonly>> RenderQueue : int?
    + MaterialDescriptor(name:string, shader:Shader, renderQueue:int?, textureSlots:IReadOnlyDictionary<string, TextureDescriptor>, floatValues:IReadOnlyDictionary<string, float>, colors:IReadOnlyDictionary<string, Color>, vectors:IReadOnlyDictionary<string, Vector4>, actions:IReadOnlyList<Action<Material>>)
}
class "IReadOnlyDictionary`2"<T1,T2> {
}
class "IReadOnlyList`1"<T> {
}
MaterialDescriptor --> "Shader" Shader
MaterialDescriptor --> "TextureSlots<string,TextureDescriptor>" "IReadOnlyDictionary`2"
MaterialDescriptor --> "FloatValues<string,float>" "IReadOnlyDictionary`2"
MaterialDescriptor --> "Colors<string,Color>" "IReadOnlyDictionary`2"
MaterialDescriptor --> "Vectors<string,Vector4>" "IReadOnlyDictionary`2"
MaterialDescriptor --> "Actions<Action<Material>>" "IReadOnlyList`1"
MaterialDescriptor --> "SubAssetKey" SubAssetKey
@enduml
