@startuml
class BlendShapeAvatar {
    + CreateDefaultPreset() : void
    + SetClip(key:BlendShapeKey, clip:BlendShapeClip) : void
    + GetClip(key:BlendShapeKey) : BlendShapeClip
    + GetClip(preset:BlendShapePreset) : BlendShapeClip
    + GetClip(name:String) : BlendShapeClip
}
class "List`1"<T> {
}
ScriptableObject <|-- BlendShapeAvatar
BlendShapeAvatar o-> "Clips<BlendShapeClip>" "List`1"
@enduml
