@startuml
class BlendShapeMerger {
    + BlendShapeMerger(clips:IEnumerable<BlendShapeClip>, root:Transform)
    + Apply() : void
    + SetValues(values:IEnumerable<KeyValuePair<BlendShapeKey, float>>) : void
    + AccumulateValue(key:BlendShapeKey, value:float) : void
    + ImmediatelySetValue(key:BlendShapeKey, value:float) : void
    + SetValue(key:BlendShapeKey, value:float, immediately:bool) : void
    + GetValue(key:BlendShapeKey) : float
    + RestoreMaterialInitialValues(clips:IEnumerable<BlendShapeClip>) : void
}
@enduml
