@startuml
class Blinker {
    + Interval : float = 5.0f
    + ClosingTime : float = 0.06f
    + OpeningSeconds : float = 0.03f
    + CloseSeconds : float = 0.1f
    + Request : bool <<get>> <<set>>
}
MonoBehaviour <|-- Blinker
@enduml
