@startuml
class MaterialItem {
    + {static} Create(material:Material) : MaterialItem
}
class MeshPreviewItem {
    + Path : string <<get>>
    + BlendShapeCount : int <<get>>
    + Bake(values:IEnumerable<BlendShapeBinding>, weight:float) : void
    + {static} Create(t:Transform, root:Transform, getOrCreateMaterial:Func<Material, Material>) : MeshPreviewItem
}
MaterialItem --> "Material" Material
MeshPreviewItem --> "SkinnedMeshRenderer" SkinnedMeshRenderer
MeshPreviewItem --> "Mesh" Mesh
MeshPreviewItem --> "Position" Vector3
MeshPreviewItem --> "Rotation" Quaternion
@enduml
