@startuml
abstract class Movements {
    + Movements()
    + <<virtual>> Start(_humanoid:HumanoidControl, _target:HumanoidTarget) : void
    + {static} ClampRotation(bone:Transform, referenceRotation:Quaternion, ROMnegative:Vector3, ROMpositive:Vector3) : void
    + {static} MuscleTension(bone:Transform, referenceRotation:Quaternion, ROMnegative:Vector3, ROMpositive:Vector3) : Vector3
    + {static} Euler180(eulerAngles:Vector3) : Vector3
    + {static} Angle180(_angle:float) : float
    + {static} AngleDifference(a:float, b:float) : float
}
@enduml
