@startuml
class DeserializingTextureInfo <<sealed>> {
    + DataMimeType : string <<get>>
    + UseMipmap : bool <<get>>
    + DeserializingTextureInfo(imageData:byte[], dataMimeType:string, colorSpace:ColorSpace, useMipmap:bool, filterMode:FilterMode, wrapModeU:TextureWrapMode, wrapModeV:TextureWrapMode)
    + DeserializingTextureInfo(imageData:byte[], dataMimeType:string, colorSpace:ColorSpace, samplerParam:SamplerParam)
}
DeserializingTextureInfo --> "ColorSpace" ColorSpace
DeserializingTextureInfo --> "FilterMode" FilterMode
DeserializingTextureInfo --> "WrapModeU" TextureWrapMode
DeserializingTextureInfo --> "WrapModeV" TextureWrapMode
@enduml
