@startuml
struct TextureDescriptor {
    + <<readonly>> UnityObjectName : string
    + <<readonly>> MetallicFactor : float
    + <<readonly>> RoughnessFactor : float
    + TextureDescriptor(name:string, offset:Vector2, scale:Vector2, sampler:SamplerParam, textureType:TextureImportTypes, metallicFactor:float, roughnessFactor:float, i0:GetTextureBytesAsync, i1:GetTextureBytesAsync, i2:GetTextureBytesAsync, i3:GetTextureBytesAsync, i4:GetTextureBytesAsync, i5:GetTextureBytesAsync)
}
class "Task`1"<T> {
}
TextureDescriptor --> "Offset" Vector2
TextureDescriptor --> "Scale" Vector2
TextureDescriptor --> "Sampler" SamplerParam
TextureDescriptor --> "TextureType" TextureImportTypes
TextureDescriptor --> "Index0" GetTextureBytesAsync
TextureDescriptor --> "Index1" GetTextureBytesAsync
TextureDescriptor --> "Index2" GetTextureBytesAsync
TextureDescriptor --> "Index3" GetTextureBytesAsync
TextureDescriptor --> "Index4" GetTextureBytesAsync
TextureDescriptor --> "Index5" GetTextureBytesAsync
TextureDescriptor --> "SubAssetKey" SubAssetKey
@enduml
