@startuml
class Event_Editor {
    + {static} showParameterSettings : bool = false
    + {static} EventInspector(eventHandlerProp:SerializedProperty, selectedEventSourceIx:int, selectedEventIx:int, methodCheck:MethodCheck, InitEvent:InitEvent, LabelField:LabelField, showOverrideMode:bool) : void
    + {static} GetButtonLabel(eventProp:SerializedProperty, eventTypeLabels:string[]) : string
    + {static} EventTypeInspector(eventProp:SerializedProperty, eventTypeLabels:string[]) : SerializedProperty
    + {static} GetMethodIndex(methodName:string, methodNames:string[]) : int
    + {static} GetMethodNames(targetGameObjectProp:SerializedProperty, methodCheck:MethodCheck) : string[]
    + {static} GetTargetGameObject(callTargetProp:SerializedProperty) : GameObject
    + {static} BlackListed(methodName:string) : bool
    + {static} SetMethod(functionCallProp:SerializedProperty, fullMethodName:string) : void
    + {static} EventMethodCheck(method:MethodInfo, label:string) : bool
    + {static} MethodParametersInspector(eventProp:SerializedProperty, eventHandlerProp:SerializedProperty) : void
    + {static} ParameterOptionsInspector(eventSourceProp:SerializedProperty) : void
}
@enduml
