@startuml
class FloatEvent_Editor {
    + {static} EventInspector(eventSourceProp:SerializedProperty, eventSource:FloatEventHandlers, selectedEventSourceIx:int, selectedEventIx:int) : void
}
Event_Editor <|-- FloatEvent_Editor
@enduml
