@startuml
class Flythrough {
    + sunX : float
    + sunY : float
    + sunZ : float
    + defaultFov : float
    + baseSpeed : float = 0.07f
    + runSpeed : float = 0.3f
    + dashSpeed : float = 2f
}
MonoBehaviour <|-- Flythrough
Flythrough --> "sun" GameObject
Flythrough --> "rimLight" GameObject
Flythrough --> "mycamera" Camera
@enduml
