@startuml
class VrmMeshIntegratorWizard {
    + {static} CreateWizard() : void
}
enum HelpMessage {
    Ready,
    SetTarget,
    InvalidTarget,
}
enum ValidationError {
    None,
    NoTarget,
    HasParent,
    NotPrefab,
}
struct MaterialKey {
    + Shader : string
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
struct MaterialList {
    + MaterialList(list:Material[])
}
class ExcludeItem {
    + Exclude : bool
}
ScriptableWizard <|-- VrmMeshIntegratorWizard
VrmMeshIntegratorWizard +-- HelpMessage
VrmMeshIntegratorWizard +-- ValidationError
VrmMeshIntegratorWizard +-- MaterialKey
VrmMeshIntegratorWizard +-- MaterialList
VrmMeshIntegratorWizard +-- ExcludeItem
ExcludeItem --> "Mesh" Mesh
@enduml
