@startuml
class Vrm10Instance {
    + DrawLookAtGizmo : bool = true
    + TryGetBoneTransform(bone:HumanBodyBones, t:Transform) : bool
}
enum UpdateTypes {
    None,
    Update,
    LateUpdate,
}
MonoBehaviour <|-- Vrm10Instance
Vrm10Instance --> "Vrm" VRM10Object
Vrm10Instance o-> "SpringBone" Vrm10InstanceSpringBone
Vrm10Instance o-> "UpdateType" UpdateTypes
Vrm10Instance --> "LookAtTarget" Transform
Vrm10Instance --> "Runtime" Vrm10Runtime
Vrm10Instance --> "Gaze" Transform
Vrm10Instance +-- UpdateTypes
@enduml
