@startuml
class Vrm10InstanceSpringBone <<sealed>> {
}
class "List`1"<T> {
}
class Spring {
    + Name : string
    + GUIName(i:int) : string
    + Spring(name:string)
    + EnumHeadTail() : IEnumerable<(VRM10SpringBoneJoint, Transform)>
}
Vrm10InstanceSpringBone o-> "ColliderGroups<VRM10SpringBoneColliderGroup>" "List`1"
Vrm10InstanceSpringBone o-> "Springs<Spring>" "List`1"
Vrm10InstanceSpringBone +-- Spring
Spring o-> "ColliderGroups<VRM10SpringBoneColliderGroup>" "List`1"
Spring o-> "Joints<VRM10SpringBoneJoint>" "List`1"
Spring --> "Center" Transform
@enduml
