@startuml
class ControllerComponent {
    + isLeft : bool
    + trigger1 : float
    + trigger2 : float
    + button1 : float
    + button2 : float
    + button3 : float
    + button4 : float
    + option : float
    + battery : float
    + <<virtual>> StartComponent(trackerTransform:Transform, isLeft:bool) : void
}
SensorComponent <|-- ControllerComponent
ControllerComponent --> "primaryAxis" Vector3
ControllerComponent --> "secondaryAxis" Vector3
@enduml
