@startuml
class HandSkeleton {
    + isLeft : bool
    + <<new>> show : bool = false
    + {static} FindHandSkeleton(trackerTransform:Transform, isLeft:bool) : HandSkeleton
    + <<virtual>> CreateHandSkeleton(trackerTransform:Transform, isLeft:bool, showRealObjects:bool) : GameObject
    + <<virtual>> GetForearmBone() : Transform
    + <<virtual>> GetWristBone() : Transform
    + <<virtual>> GetBoneTransform(finger:Finger, fingerBone:FingerBone) : Transform
    + <<virtual>> GetBoneId(finger:Finger, fingerBone:FingerBone) : int
}
enum BoneId {
    Invalid= -1,
    Hand= 0,
    ThumbProximal,
    ThumbIntermediate,
    ThumbDistal,
    ThumbTip,
    IndexMetaCarpal,
    IndexProximal,
    IndexIntermediate,
    IndexDistal,
    IndexTip,
    MiddleMetaCarpal,
    MiddleProximal,
    MiddleIntermediate,
    MiddleDistal,
    MiddleTip,
    RingMetaCarpal,
    RingProximal,
    RingIntermediate,
    RingDistal,
    RingTip,
    LittleMetacarpal,
    LittleProximal,
    LittleIntermediate,
    LittleDistal,
    LittleTip,
    Forearm,
    Count,
}
SensorComponent <|-- HandSkeleton
HandSkeleton +-- BoneId
@enduml
