@startuml
abstract class HeadSensor {
    + <<virtual>> CheckSensor(headTarget:HeadTarget) : void
    + <<virtual>> Init(headTarget:HeadTarget) : void
    + <<override>> Start(_humanoid:HumanoidControl, targetTransform:Transform) : void
    + <<override>> Update() : void
}
HumanoidSensor <|-- HeadSensor
@enduml
