@startuml
abstract class HumanoidTracker {
    + <<virtual>> CheckTracker(humanoid:HumanoidControl) : void
    + CheckTracker(humanoid:HumanoidControl, getTracker:TrackerGetter) : void
    + CheckTracker(humanoid:HumanoidControl, getTracker:TrackerGetter, localPosition:Vector3, localRotation:Quaternion) : void
    + <<virtual>> StartTracker(_humanoid:HumanoidControl) : void
}
abstract class SubTracker {
    + subTrackerId : int
    + {abstract} IsPresent() : bool
    + {abstract} UpdateTracker(showRealObjects:bool) : void
}
Tracker <|-- HumanoidTracker
HumanoidTracker --> "humanoid" HumanoidControl
HumanoidTracker --> "headSensor" HeadSensor
HumanoidTracker --> "leftHandSensor" ArmSensor
HumanoidTracker --> "rightHandSensor" ArmSensor
HumanoidTracker --> "hipsSensor" TorsoSensor
HumanoidTracker --> "leftFootSensor" LegSensor
HumanoidTracker --> "rightFootSensor" LegSensor
MonoBehaviour <|-- SubTracker
SubTracker --> "tracker" HumanoidTracker
@enduml
