@startuml
class RealWorldConfiguration {
}
class "List`1"<T> {
}
class TrackingSpace {
}
ScriptableObject <|-- RealWorldConfiguration
RealWorldConfiguration o-> "trackers<TrackingSpace>" "List`1"
RealWorldConfiguration +-- TrackingSpace
TrackingSpace --> "position" Vector3
TrackingSpace --> "rotation" Quaternion
@enduml
