@startuml
abstract class Tracker {
    + <<virtual>> name : string <<get>>
    + enabled : bool
    + <<virtual>> StartTracker() : void
    + <<virtual>> StopTracker() : void
    + <<virtual>> UpdateTracker() : void
    + <<virtual>> ShowTracker(shown:bool) : void
    + <<virtual>> Calibrate() : void
    + <<virtual>> AdjustTracking(positionalDelta:Vector3, rotationalDelta:Quaternion) : void
}
enum Status {
    Unavailable,
    Present,
    Tracking,
}
Tracker --> "status" Status
Tracker --> "trackerComponent" TrackerComponent
Tracker +-- Status
@enduml
