@startuml
abstract class SelectedGUIBase {
    + {abstract} Draw2D(r:Rect) : void
    + {abstract} Draw3D() : void
    + {static} LayoutLine(rect:Rect) : (Rect line, Rect remain)
    + {static} LayoutVerticalHalf(r:Rect) : (Rect layout, Rect remain)
}
class SelectedColliderGroupGUI {
    + SelectedColliderGroupGUI(so:SerializedObject, i:int)
    + Draw2D(r:Rect) : void
    + {static} DrawWireCapsule(headPos:Vector3, tailPos:Vector3, radius:float) : void
    + Draw3D() : void
}
class SelectedSpringGUI {
    + SelectedSpringGUI(target:Vrm10Instance, so:SerializedObject, i:int)
    + <<override>> Draw2D(r:Rect) : void
    + <<override>> Draw3D() : void
}
SelectedGUIBase --> "Property" SerializedProperty
SelectedGUIBase <|-- SelectedSpringGUI
@enduml
