@startuml
class SpringBoneTreeView {
    + SpringBoneTreeView(state:TreeViewState, target:Vrm10Instance, so:SerializedObject)
    + Draw2D() : void
    + Draw3D(springBone:Vrm10InstanceSpringBone) : bool
}
TreeView <|-- SpringBoneTreeView
SpringBoneTreeView --> "Target" Vrm10Instance
SpringBoneTreeView o-> "Active" MonoBehaviour
@enduml
