@startuml
class NextFrameTaskScheduler <<sealed>> {
    + IsSupported : bool <<get>>
    + NextFrameTaskScheduler()
    + Enqueue(action:Action) : bool
}
class UnityLoopTaskScheduler <<sealed>> {
}
NextFrameTaskScheduler +-- UnityLoopTaskScheduler
MonoBehaviour <|-- UnityLoopTaskScheduler
UnityLoopTaskScheduler --> "Instance" UnityLoopTaskScheduler
UnityLoopTaskScheduler o-> "Scheduler" TinyManagedTaskScheduler
@enduml
