@startuml
class RuntimeOnlyAwaitCaller <<sealed>> {
    + RuntimeOnlyAwaitCaller(timeOutInSeconds:float)
    + NextFrame() : Task
    + Run(action:Action) : Task
    + Run(action:Func<T>) : Task<T>
    + NextFrameIfTimedOut() : Task
}
IAwaitCaller <|-- RuntimeOnlyAwaitCaller
@enduml
