@startuml
class RuntimeOnlyNoThreadAwaitCaller <<sealed>> {
    + RuntimeOnlyNoThreadAwaitCaller(timeoutInSeconds:float)
    + NextFrame() : Task
    + Run(action:Action) : Task
    + Run(action:Func<T>) : Task<T>
    + NextFrameIfTimedOut() : Task
}
IAwaitCaller <|-- RuntimeOnlyNoThreadAwaitCaller
@enduml
