@startuml
enum GameControllers {
    Generic,
    Xbox,
    PS4,
    Steelseries,
    GameSmart,
    Oculus,
    OpenVR,
}
class Controllers <<static>> {
    + {static} Update() : void
    + {static} GetController(controllerID:int) : Controller
    + {static} Clear() : void
    + {static} EndFrame() : void
}
class Controller {
    + Update() : void
    + Controller()
    + Clear() : void
    + EndFrame() : void
    + GetButton(side:Side, buttonID:Button) : bool
}
class ControllerSide {
    + stickHorizontal : float
    + stickVertical : float
    + stickButton : bool
    + stickTouch : bool
    + touchpadVertical : float
    + touchpadHorizontal : float
    + touchpadPress : bool
    + touchpadTouch : bool
    + trigger1 : float
    + trigger2 : float
    + option : bool
    +  <<event>> OnButtonDownEvent : OnButtonDown 
    +  <<event>> OnButtonUpEvent : OnButtonUp 
    + Update() : void
    + Clear() : void
    + GetButton(buttonID:Controller.Button) : bool
}
enum Side {
    Left,
    Right,
}
enum Button {
    ButtonOne= 0,
    ButtonTwo= 1,
    ButtonThree= 2,
    ButtonFour= 3,
    Bumper= 10,
    BumperTouch= 11,
    Trigger= 12,
    TriggerTouch= 13,
    StickButton= 14,
    StickTouch= 15,
    Option= 30,
    None= 9999,
}
Controller --> "left" ControllerSide
Controller --> "right" ControllerSide
Controller +-- Side
Controller +-- Button
@enduml
