@startuml
class ControllerDebugger {
}
struct ControllerSideDebugger {
    + stickHorizontal : float
    + stickVertical : float
    + stickButton : bool
    + stickTouch : bool
    + touchpadHorizontal : float
    + touchpadVertical : float
    + touchpadButton : bool
    + touchpadTouch : bool
    + bumper : float
    + trigger : float
    + option : bool
}
MonoBehaviour <|-- ControllerDebugger
ControllerDebugger --> "left" ControllerSideDebugger
ControllerDebugger --> "right" ControllerSideDebugger
ControllerDebugger +-- ControllerSideDebugger
@enduml
