@startuml
class ControllerInput {
    + fingerMovements : bool = true
    + leftStickVertical : float <<get>>
    + leftStickHorizontal : float <<get>>
    + leftStickPressed : bool <<get>>
    + leftTouchpadVertical : float <<get>>
    + leftTouchpadHorizontal : float <<get>>
    + leftTouchpadPressed : bool <<get>>
    + leftTrigger1 : float <<get>>
    + leftTrigger1Touched : bool <<get>>
    + leftTrigger1Pressed : bool <<get>>
    + leftTrigger2 : float <<get>>
    + leftTrigger2Touched : bool <<get>>
    + leftTrigger2Pressed : bool <<get>>
    + leftButton1Pressed : bool <<get>>
    + leftButton2Pressed : bool <<get>>
    + leftButton3Pressed : bool <<get>>
    + leftButton4Pressed : bool <<get>>
    + leftOptionPressed : bool <<get>>
    + rightStickVertical : float <<get>>
    + rightStickHorizontal : float <<get>>
    + rightStickPressed : bool <<get>>
    + rightTouchpadVertical : float <<get>>
    + rightTouchpadHorizontal : float <<get>>
    + rightTouchpadPressed : bool <<get>>
    + rightTrigger1 : float <<get>>
    + rightTrigger1Touched : bool <<get>>
    + rightTrigger1Pressed : bool <<get>>
    + rightTrigger2 : float <<get>>
    + rightTrigger2Touched : bool <<get>>
    + rightTrigger2Pressed : bool <<get>>
    + rightButton1Pressed : bool <<get>>
    + rightButton2Pressed : bool <<get>>
    + rightButton3Pressed : bool <<get>>
    + rightButton4Pressed : bool <<get>>
    + rightOptionPressed : bool <<get>>
    + InitializeLeftInputEvents() : void
    + InitializeRightInputEvents() : void
    + GetInputEvent(isLeft:bool, controllerButton:SideButton) : ControllerEventHandlers
    + SetEventHandler(isLeft:bool, sideButton:SideButton, boolEvent:UnityAction<bool>) : void
    + {static} SetBoolMethod(gameObject:GameObject, eventHandlers:ControllerEventHandlers, eventType:EventHandler.Type, boolEvent:UnityAction<bool>) : void
    + SetRightTrigger1Value(value:float) : void
}
enum SideButton {
    StickVertical,
    StickHorizontal,
    StickButton,
    TouchpadVertical,
    TouchpadHorizontal,
    TouchpadButton,
    Button1,
    Button2,
    Button3,
    Button4,
    Trigger1,
    Trigger2,
    Option,
}
MonoBehaviour <|-- ControllerInput
ControllerInput --> "humanoid" HumanoidControl
ControllerInput --> "gameController" GameControllers
ControllerInput +-- SideButton
@enduml
