@startuml
class KeyboardInput {
}
class KeyboardEventHandlers {
}
class "List`1"<T> {
}
MonoBehaviour <|-- KeyboardInput
KeyboardInput o-> "keyboardHandlers<KeyboardEventHandlers>" "List`1"
ControllerEventHandlers <|-- KeyboardEventHandlers
KeyboardEventHandlers --> "keyCode" KeyCode
@enduml
