@startuml
class TraditionalDevice {
    + {static} gameControllerEnabled : bool = true
    + Clear() : void
    + SetControllerID(controllerID:int) : Controller
    + mouseAccumulation : bool = true
    + UpdateGameController(gameController:GameControllers) : void
    + UpdateGenericController() : void
    + UpdateXboxController() : void
    + UpdatePS4Controller() : void
    + UpdateSteelseriesController() : void
    + UpdateGameSmartController() : void
    + UpdateGA100Controller() : void
    + UpdateOculusController() : void
    + UpdateOpenVRController() : void
}
enum LeftRight {
    Left,
    Right,
}
TraditionalDevice o-> "mouseIsControllerStick" LeftRight
TraditionalDevice +-- LeftRight
@enduml
