@startuml
class RaycastVisualizer {
    + rayLength : float = 1.0f
}
enum RayDirection {
    Forward,
    Up,
    Right,
}
MonoBehaviour <|-- RaycastVisualizer
RaycastVisualizer o-> "rayDirectionEnum" RayDirection
RaycastVisualizer o-> "color" Color
RaycastVisualizer +-- RayDirection
@enduml
