@startuml
struct BlittableTransform {
    + SetWorldRotation(rotation:Quaternion) : void
    + BlittableTransform(parent:BlittableTransform*, transform:Transform)
    + PullFrom(transform:TransformAccess) : void
    + PushTo(transform:TransformAccess) : void
    + TransformPoint(offset:Vector3) : Vector3
    + UpdateLocalToWorldMatrix() : void
}
BlittableTransform --> "WorldPosition" Vector3
BlittableTransform --> "LocalToWorld" Matrix4x4
BlittableTransform --> "ParentWorldRotation" Quaternion
@enduml
