@startuml
class EditorTextureSerializerTests <<sealed>> {
    + InputAssetsRawImage() : void
    + CopyToSrgbRenderTexture() : void
    + CopyToLinearRenderTexture() : void
    + AssignSrgbImageToSrgbTextureProperty() : void
    + AssignLinearImageToSrgbTextureProperty() : void
    + AssignSrgbImageToLinearTextureProperty() : void
    + AssignLinearImageToLinearTextureProperty() : void
    + AssignLinearImageToNormalTextureProperty() : void
    + AssignLinearImageAsNormalMapSettingsToNormalTextureProperty() : void
}
@enduml
