@startuml
class SceneManager {
    + currentScene : int = 0
    + dontDestroyOnLoad : bool = false
    + LoadScene(sceneId:int) : void
    + NextScene() : void
    + PreviousScene() : void
    + {static} mod(k:int, n:int) : int
}
MonoBehaviour <|-- SceneManager
@enduml
