@startuml
class Socket {
    + isOccupied : bool <<get>>
    + socketTag : string
    + destroyOnLoad : bool = false
    + Attach(objectToAttach:GameObject) : void
    + Attach(objectToAttach:GameObject, rangeCheck:bool) : bool
    + <<virtual>> Attach(transformToAttach:Transform, rangeCheck:bool) : bool
    + <<virtual>> Attach(handle:Handle, rangeCheck:bool) : bool
    + <<virtual>> AttachStaticJoint(objTransform:Transform) : void
    + <<virtual>> Release(releaseSticky:bool) : void
    + <<virtual>> ReleaseStaticJoint() : void
    + OnDrawGizmosSelected() : void
    + {static} GenerateGizmoMesh1() : Mesh
    + {static} GenerateGizmoMesh() : Mesh
}
class DestroyedJoints {
}
enum AttachMethod {
    Unknown,
    Parenting,
    ReverseParenting,
    Joint,
    StaticJoint,
    ColliderDuplication,
}
MonoBehaviour <|-- Socket
Socket --> "attachedPrefab" GameObject
Socket --> "attachedTransform" Transform
Socket --> "attachedHandle" Handle
Socket o-> "attachMethod" AttachMethod
Socket o-> "attachEvent" GameObjectEventHandlers
MonoBehaviour <|-- DestroyedJoints
Socket +-- AttachMethod
@enduml
