@startuml
class Teleporter {
    + <<virtual>> TeleportTransform() : void
    + {static} <<new>> Add(parentTransform:Transform, pointerType:PointerType) : Teleporter
    + <<override>> Click(clicking:bool) : void
}
enum TransportType {
    Teleport,
    Dash,
}
InteractionPointer <|-- Teleporter
Teleporter o-> "transportType" TransportType
Teleporter --> "transformToTeleport" Transform
Teleporter +-- TransportType
@enduml
