@startuml
class TeleportTarget {
    + teleportRoot : bool = false
    + checkCollision : bool = true
    + enableAnimators : bool = true
    + TeleportToHere(t:Transform) : void
    + TeleportToHere(humanoid:HumanoidControl) : void
    + <<override>> OnPointerDown(eventData:PointerEventData) : void
}
enum TargetPosRot {
    Pointer,
    Transform,
}
EventTrigger <|-- TeleportTarget
TeleportTarget --> "movementType" MovementType
TeleportTarget o-> "targetPosRot" TargetPosRot
TeleportTarget --> "targetTransform" Transform
TeleportTarget --> "pose" Pose
TeleportTarget --> "unityEvents" UnityEvent
TeleportTarget +-- TargetPosRot
@enduml
