@startuml
class Transportation {
    + forwardSpeed : float = 1
    + sidewardSpeed : float = 1
    + rotationalSpeed : float = 60
    + <<virtual>> MoveForward(z:float) : void
    + <<virtual>> MoveSideward(x:float) : void
    + <<virtual>> Rotate(angularSpeed:float) : void
    + Dash(targetPosition:Vector3) : void
    + Teleport(targetPosition:Vector3) : void
    + Teleport() : void
}
class TransformMovements <<static>> {
    + {static} MoveForward(transform:Transform, z:float) : void
    + {static} MoveSidewards(transform:Transform, x:float) : void
    + {static} Turn(transform:Transform, angle:float) : void
    + {static} Teleport(transform:Transform, targetPosition:Vector3) : void
    + {static} DashCoroutine(transform:Transform, targetPosition:Vector3) : IEnumerator
}
MonoBehaviour <|-- Transportation
@enduml
