@startuml
enum MovementType {
    Teleport,
    Dash,
    Walk,
}
class Transport {
    + {static} DashCoroutine(transform:Transform, targetPosition:Vector3, duration:float, minSpeed:float) : IEnumerator
    + {static} LookAt(transform:Transform, targetPosition:Vector3, rotationSpeed:float) : IEnumerator
    + {static} RotateTo(transform:Transform, targetRotation:Quaternion, rotationSpeed:float) : IEnumerator
    + {static} WalkCoroutine(transform:Transform, targetPosition:Vector3, maxSpeed:float) : IEnumerator
    + {static} WalkCoroutine(transform:Transform, targetPosition:Vector3, targetRotation:Quaternion, maxSpeed:float) : IEnumerator
}
class TransformTransport <<static>> {
    + {static} MoveTo(transform:Transform, position:Vector3, movementType:MovementType) : void
}
@enduml
