@startuml
class GltfDeserializer <<static>> {
    + {static} TryGet(src:UniGLTF.glTFExtension, extension:VRMC_springBone) : bool
    + {static} Deserialize(parsed:JsonNode) : VRMC_springBone
    + {static} Deserialize_Colliders(parsed:JsonNode) : List<Collider>
    + {static} Deserialize_Colliders_ITEM(parsed:JsonNode) : Collider
    + {static} __colliders_ITEM_Deserialize_Shape(parsed:JsonNode) : ColliderShape
    + {static} __colliders_ITEM__shape_Deserialize_Sphere(parsed:JsonNode) : ColliderShapeSphere
    + {static} __colliders_ITEM__shape__sphere_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __colliders_ITEM__shape_Deserialize_Capsule(parsed:JsonNode) : ColliderShapeCapsule
    + {static} __colliders_ITEM__shape__capsule_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __colliders_ITEM__shape__capsule_Deserialize_Tail(parsed:JsonNode) : float[]
    + {static} Deserialize_ColliderGroups(parsed:JsonNode) : List<ColliderGroup>
    + {static} Deserialize_ColliderGroups_ITEM(parsed:JsonNode) : ColliderGroup
    + {static} __colliderGroups_ITEM_Deserialize_Colliders(parsed:JsonNode) : int[]
    + {static} Deserialize_Springs(parsed:JsonNode) : List<Spring>
    + {static} Deserialize_Springs_ITEM(parsed:JsonNode) : Spring
    + {static} __springs_ITEM_Deserialize_Joints(parsed:JsonNode) : List<SpringBoneJoint>
    + {static} __springs_ITEM_Deserialize_Joints_ITEM(parsed:JsonNode) : SpringBoneJoint
    + {static} __springs_ITEM__joints_ITEM_Deserialize_GravityDir(parsed:JsonNode) : float[]
    + {static} __springs_ITEM_Deserialize_ColliderGroups(parsed:JsonNode) : int[]
}
GltfDeserializer o-> "ExtensionNameUtf8" Utf8String
@enduml
