@startuml
class ColliderShapeSphere {
    + Radius : float?
}
class ColliderShapeCapsule {
    + Radius : float?
}
class ColliderShape {
    + Extensions : object
    + Extras : object
}
class Collider {
    + Extensions : object
    + Extras : object
    + Node : int?
}
class ColliderGroup {
    + Extensions : object
    + Extras : object
    + Name : string
}
class SpringBoneJoint {
    + Extensions : object
    + Extras : object
    + Node : int?
    + HitRadius : float?
    + Stiffness : float?
    + GravityPower : float?
    + DragForce : float?
}
class Spring {
    + Extensions : object
    + Extras : object
    + Name : string
    + Center : int?
}
class VRMC_springBone {
    + <<const>> ExtensionName : string = "VRMC_springBone"
    + Extensions : object
    + Extras : object
    + SpecVersion : string
}
class "List`1"<T> {
}
ColliderShape --> "Sphere" ColliderShapeSphere
ColliderShape --> "Capsule" ColliderShapeCapsule
Collider --> "Shape" ColliderShape
Spring --> "Joints<SpringBoneJoint>" "List`1"
VRMC_springBone --> "Colliders<Collider>" "List`1"
VRMC_springBone --> "ColliderGroups<ColliderGroup>" "List`1"
VRMC_springBone --> "Springs<Spring>" "List`1"
@enduml
