@startuml
class ByteUnion <<static>> {
}
struct WordValue {
    + Byte0 : byte
    + Byte1 : byte
    + HostToNetworkOrder() : WordValue
    + {static} Create(value:Int16) : WordValue
    + {static} Create(value:UInt16) : WordValue
}
struct DWordValue {
    + Byte0 : byte
    + Byte1 : byte
    + Byte2 : byte
    + Byte3 : byte
    + HostToNetworkOrder() : DWordValue
    + {static} Create(value:Int32) : DWordValue
    + {static} Create(value:UInt32) : DWordValue
    + {static} Create(value:Single) : DWordValue
}
struct QWordValue {
    + Byte0 : byte
    + Byte1 : byte
    + Byte2 : byte
    + Byte3 : byte
    + Byte4 : byte
    + Byte5 : byte
    + Byte6 : byte
    + Byte7 : byte
    + HostToNetworkOrder() : QWordValue
    + {static} Create(value:Int64) : QWordValue
    + {static} Create(value:UInt64) : QWordValue
    + {static} Create(value:Double) : QWordValue
}
ByteUnion +-- WordValue
WordValue --> "Signed" Int16
WordValue --> "Unsigned" UInt16
ByteUnion +-- DWordValue
DWordValue --> "Signed" Int32
DWordValue --> "Unsigned" UInt32
DWordValue --> "Float" Single
ByteUnion +-- QWordValue
QWordValue --> "Signed" Int64
QWordValue --> "Unsigned" UInt64
QWordValue --> "Float" Double
@enduml
