@startuml
class BytesStore {
    + BytesStore()
    + BytesStore(size:int)
    + BytesStore(buffer:Byte[])
    + Clear() : void
    + Write(c:char) : void
    + Write(src:string) : void
    + Write(bytes:ArraySegment<byte>) : void
    + Write(value:sbyte) : void
    + Write(value:byte) : void
    + WriteLittleEndian(value:short) : void
    + WriteLittleEndian(value:int) : void
    + WriteLittleEndian(value:long) : void
    + WriteLittleEndian(value:ushort) : void
    + WriteLittleEndian(value:uint) : void
    + WriteLittleEndian(value:ulong) : void
    + WriteLittleEndian(value:float) : void
    + WriteLittleEndian(value:double) : void
    + WriteBigEndian(value:short) : void
    + WriteBigEndian(value:int) : void
    + WriteBigEndian(value:long) : void
    + WriteBigEndian(value:ushort) : void
    + WriteBigEndian(value:uint) : void
    + WriteBigEndian(value:ulong) : void
    + WriteBigEndian(value:float) : void
    + WriteBigEndian(value:double) : void
}
class "ArraySegment`1"<T> {
}
IStore <|-- BytesStore
BytesStore --> "Bytes<byte>" "ArraySegment`1"
@enduml
