@startuml
class StringBuilderStore {
    + StringBuilderStore(sb:StringBuilder)
    + Buffer() : string
    + Clear() : void
    + Write(bytes:ArraySegment<byte>) : void
    + Write(value:byte) : void
    + Write(value:sbyte) : void
    + Write(src:IEnumerable<char>) : void
    + Write(c:Char) : void
    + Write(src:string) : void
    + WriteBigEndian(value:int) : void
    + WriteBigEndian(value:float) : void
    + WriteBigEndian(value:double) : void
    + WriteBigEndian(value:long) : void
    + WriteBigEndian(value:ulong) : void
    + WriteBigEndian(value:short) : void
    + WriteBigEndian(value:uint) : void
    + WriteBigEndian(value:ushort) : void
    + WriteLittleEndian(value:double) : void
    + WriteLittleEndian(value:short) : void
    + WriteLittleEndian(value:int) : void
    + WriteLittleEndian(value:float) : void
    + WriteLittleEndian(value:long) : void
    + WriteLittleEndian(value:ulong) : void
    + WriteLittleEndian(value:uint) : void
    + WriteLittleEndian(value:ushort) : void
}
class "ArraySegment`1"<T> {
}
IStore <|-- StringBuilderStore
StringBuilderStore --> "Bytes<Byte>" "ArraySegment`1"
@enduml
