@startuml
struct BlittableTransform {
}
BlittableTransform --> "position" Vector3
BlittableTransform --> "rotation" Quaternion
BlittableTransform --> "localPosition" Vector3
BlittableTransform --> "localRotation" Quaternion
BlittableTransform --> "localScale" Vector3
BlittableTransform --> "localToWorldMatrix" Matrix4x4
BlittableTransform --> "worldToLocalMatrix" Matrix4x4
@enduml
