@startuml
struct BlittableSpring {
    + centerTransformIndex : int
    + transformIndexOffset : int
}
BlittableSpring --> "colliderSpan" BlittableSpan
BlittableSpring --> "logicSpan" BlittableSpan
@enduml
