@startuml
class GltfDeserializer <<static>> {
    + {static} TryGet(src:UniGLTF.glTFExtension, extension:VRMC_node_constraint) : bool
    + {static} Deserialize(parsed:JsonNode) : VRMC_node_constraint
    + {static} Deserialize_Constraint(parsed:JsonNode) : Constraint
    + {static} __constraint_Deserialize_Roll(parsed:JsonNode) : RollConstraint
    + {static} __constraint_Deserialize_Aim(parsed:JsonNode) : AimConstraint
    + {static} __constraint_Deserialize_Rotation(parsed:JsonNode) : RotationConstraint
}
GltfDeserializer o-> "ExtensionNameUtf8" Utf8String
@enduml
