@startuml
class Vrm10RuntimeExpression <<sealed>> {
    + BlinkOverrideRate : float <<get>>
    + LookAtOverrideRate : float <<get>>
    + MouthOverrideRate : float <<get>>
    + GetWeights() : IDictionary<ExpressionKey, float>
    + GetWeight(expressionKey:ExpressionKey) : float
    + GetEyeDirection() : LookAtEyeDirection
    + SetWeights(weights:IEnumerable<KeyValuePair<ExpressionKey, float>>) : void
    + SetWeight(expressionKey:ExpressionKey, weight:float) : void
}
class "IReadOnlyList`1"<T> {
}
class "IReadOnlyDictionary`2"<T1,T2> {
}
Vrm10RuntimeExpression o-> "ExpressionValidatorFactory" IExpressionValidatorFactory
Vrm10RuntimeExpression --> "ExpressionKeys<ExpressionKey>" "IReadOnlyList`1"
Vrm10RuntimeExpression --> "ActualWeights<ExpressionKey,float>" "IReadOnlyDictionary`2"
Vrm10RuntimeExpression --> "ActualEyeDirection" LookAtEyeDirection
@enduml
