@startuml
class Vrm10RuntimeLookAt <<sealed>> {
    + Yaw : float <<get>>
    + Pitch : float <<get>>
    + SetYawPitchManually(yaw:float, pitch:float) : void
    + CalculateYawPitchFromLookAtPosition(lookAtWorldPosition:Vector3) : (float Yaw, float Pitch)
    + GetLookAtOrigin(head:Transform) : Transform
    + SetLookAtYawPitch(yaw:float, pitch:float) : void
    + GetLookAtYawPitch(head:Transform, lookAtTargetType:VRM10ObjectLookAt.LookAtTargetTypes, gaze:Transform) : (float, float)
}
ILookAtEyeDirectionProvider <|-- Vrm10RuntimeLookAt
Vrm10RuntimeLookAt --> "EyeDirection" LookAtEyeDirection
Vrm10RuntimeLookAt --> "LookAtOriginTransform" Transform
@enduml
