@startuml
class Angle {
    + {static} Normalize(angle:float) : float
    + {static} Clamp(angle:float, min:float, max:float) : float
}
struct Angles {
    + {static} Normalize(angles:Vector) : Vector
    + {static} Clamp(angles:Vector, min:Vector, max:Vector) : Vector
}
@enduml
