@startuml
class BoneMapping {
    + GuessBoneMapping() : void
    + EnsureTPose() : void
    + {static} SetBonesToDescription(mapping:BoneMapping, description:AvatarDescription) : void
}
MonoBehaviour <|-- BoneMapping
BoneMapping --> "Description" AvatarDescription
@enduml
