@startuml
class HumanPoseTransfer {
    + CreatePose() : HumanPose
    + SetPose(pose:HumanPose) : void
    + {static} SetPose(avatar:Avatar, transform:Transform, pose:HumanPose) : void
    + {static} SetTPose(avatar:Avatar, transform:Transform) : void
    + OnEnable() : void
    + Setup() : void
    + GetPose(frameCount:int, pose:HumanPose) : bool
}
enum HumanPoseTransferSourceType {
    None,
    HumanPoseTransfer,
    HumanPoseClip,
}
MonoBehaviour <|-- HumanPoseTransfer
HumanPoseTransfer --> "SourceType" HumanPoseTransferSourceType
HumanPoseTransfer --> "Avatar" Avatar
HumanPoseTransfer --> "Source" HumanPoseTransfer
HumanPoseTransfer --> "PoseClip" HumanPoseClip
HumanPoseTransfer +-- HumanPoseTransferSourceType
@enduml
