@startuml
class MuscleDebug {
}
struct Muscle {
    + Index : int
    + Name : string
    + Value : float
}
MonoBehaviour <|-- MuscleDebug
MuscleDebug --> "m_pose" HumanPose
MuscleDebug --> "BodyPosition" Vector3
MuscleDebug +-- Muscle
@enduml
