@startuml
struct Skeleton {
    + GetBoneIndex(bone:HumanBodyBones) : int
    + {static} Estimate(hips:Transform) : Skeleton
    + Set(bone:HumanBodyBones, bones:IList<IBone>, b:IBone) : void
    + Set(bone:HumanBodyBones, index:int, name:string) : void
}
class "Dictionary`2"<T1,T2> {
}
Skeleton --> "Bones<HumanBodyBones,int>" "Dictionary`2"
@enduml
