@startuml
interface ISkeletonDetector {
}
class BvhSkeletonEstimator {
    + Detect(bones:IList<IBone>) : Skeleton
    + Detect(bvh:Bvh) : Skeleton
    + Detect(t:Transform) : Skeleton
}
struct Arm {
}
struct Leg {
}
ISkeletonDetector <|-- BvhSkeletonEstimator
BvhSkeletonEstimator +-- Arm
Arm --> "Shoulder" IBone
Arm --> "UpperArm" IBone
Arm --> "LowerArm" IBone
Arm --> "Hand" IBone
BvhSkeletonEstimator +-- Leg
Leg --> "UpperLeg" IBone
Leg --> "LowerLeg" IBone
Leg --> "Foot" IBone
Leg --> "Toes" IBone
@enduml
