@startuml
class CurveMapper {
    + CurveXRangeDegree : float
    + CurveYRangeDegree : float
    + CurveMapper(xRange:float, yRange:float)
    + OnValidate() : void
    + Assign(mapper:CurveMapper) : void
    + Apply(degreeMap:glTF_VRM_DegreeMap) : void
    + Map(src:float) : float
    + Equals(other:CurveMapper) : bool
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<CurveMapper>" <|-- CurveMapper
CurveMapper o-> "Curve" AnimationCurve
@enduml
