@startuml
class VRMLookAtBoneApplyer {
    + DrawGizmo : bool = false
    + OnImported(context:VRMImporterContext) : void
}
MonoBehaviour <|-- VRMLookAtBoneApplyer
IVRMComponent <|-- VRMLookAtBoneApplyer
VRMLookAtBoneApplyer --> "LeftEye" OffsetOnTransform
VRMLookAtBoneApplyer --> "RightEye" OffsetOnTransform
VRMLookAtBoneApplyer o-> "HorizontalOuter" CurveMapper
VRMLookAtBoneApplyer o-> "HorizontalInner" CurveMapper
VRMLookAtBoneApplyer o-> "VerticalDown" CurveMapper
VRMLookAtBoneApplyer o-> "VerticalUp" CurveMapper
@enduml
