@startuml
class UnityXRDevice <<static>> {
    + {static} Start() : void
}
enum XRDeviceType {
    None,
    Oculus,
    OpenVR,
    WindowsMR,
    Cardboard,
}
UnityXRDevice o-> "xrDevice" XRDeviceType
UnityXRDevice +-- XRDeviceType
@enduml
