@startuml
class UnityXR {
    + {static} Find(parentTransform:Transform) : UnityXR
    + {static} Get(parentTransform:Transform, localPosition:Vector3, localRotation:Quaternion) : UnityXR
    + GetHmd(position:Vector3, rotation:Quaternion) : UnityXRHmd
}
TrackerComponent <|-- UnityXR
UnityXR --> "hmd" UnityXRHmd
UnityXR --> "leftSkeleton" UnityXRHandSkeleton
UnityXR --> "rightSkeleton" UnityXRHandSkeleton
@enduml
