@startuml
class GltfSerializer <<static>> {
    + {static} SerializeTo(dst:UniGLTF.glTFExtension, extension:VRMC_vrm_animation) : void
    + {static} Serialize(f:JsonFormatter, value:VRMC_vrm_animation) : void
    + {static} Serialize_Humanoid(f:JsonFormatter, value:Humanoid) : void
    + {static} __humanoid_Serialize_HumanBones(f:JsonFormatter, value:HumanBones) : void
    + {static} __humanoid__humanBones_Serialize_Hips(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Spine(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Chest(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_UpperChest(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Neck(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Head(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Jaw(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftUpperLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLowerLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftFoot(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftToes(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightUpperLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLowerLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightFoot(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightToes(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftShoulder(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftUpperArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLowerArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftHand(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightShoulder(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightUpperArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLowerArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightHand(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftThumbMetacarpal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftThumbProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftThumbDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftIndexProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftIndexIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftIndexDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftMiddleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftMiddleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftMiddleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftRingProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftRingIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftRingDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLittleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLittleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLittleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightThumbMetacarpal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightThumbProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightThumbDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightIndexProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightIndexIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightIndexDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightMiddleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightMiddleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightMiddleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightRingProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightRingIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightRingDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLittleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLittleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLittleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} Serialize_Expressions(f:JsonFormatter, value:Expressions) : void
    + {static} __expressions_Serialize_Preset(f:JsonFormatter, value:Preset) : void
    + {static} __expressions__preset_Serialize_Happy(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Angry(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Sad(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Relaxed(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Surprised(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Aa(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Ih(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Ou(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Ee(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Oh(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Blink(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_BlinkLeft(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_BlinkRight(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_LookUp(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_LookDown(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_LookLeft(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_LookRight(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset_Serialize_Neutral(f:JsonFormatter, value:Expression) : void
    + {static} __expressions_Serialize_Custom(f:JsonFormatter, value:Dictionary<string, Expression>) : void
    + {static} __expressions_Serialize_Custom_ITEM(f:JsonFormatter, value:Expression) : void
    + {static} Serialize_LookAt(f:JsonFormatter, value:LookAt) : void
}
@enduml
