@startuml
class InitScene {
    + SetReferenceInstructionPanelShownState(value:bool) : void
    + ReferenceInstructionPanelAlreadyShown() : bool
    + SetConclusionPanelShownState(value:bool) : void
    + ConclusionPanelAlreadyShown() : bool
    + IsCurrentScene(sceneName:string) : bool
}
MonoBehaviour <|-- InitScene
@enduml
