@startuml
class SpellRouting {
    +  <<event>> OnSpawningPointDataCollected : Action<SpawningPointData> 
    + auraIsGrowing : bool = true
    + StartSpellRouting() : void
    + PlayAudio() : void
    + GetSpawningPointData() : SpawningPointData
}
MonoBehaviour <|-- SpellRouting
SpellRouting --> "spherePrefab" GameObject
SpellRouting --> "SphereCollisionSound" AudioSource
SpellRouting --> "initScene" InitScene
@enduml
