@startuml
class NaturalHandBarText {
    + OnPointerEnter(eventData:PointerEventData) : void
    + OnPointerExit(eventData:PointerEventData) : void
    + OnPointerDown(eventData:PointerEventData) : void
    + OnBeginDrag(eventData:PointerEventData) : void
    + OnDrag(eventData:PointerEventData) : void
    + OnEndDrag(eventData:PointerEventData) : void
    + OnDrop(eventData:PointerEventData) : void
    + OnPointerUp(eventData:PointerEventData) : void
    + OnPointerClick(eventData:PointerEventData) : void
    + OnSubmit(eventData:BaseEventData) : void
}
MonoBehaviour <|-- NaturalHandBarText
IPointerEnterHandler <|-- NaturalHandBarText
IPointerExitHandler <|-- NaturalHandBarText
IPointerDownHandler <|-- NaturalHandBarText
IBeginDragHandler <|-- NaturalHandBarText
IDragHandler <|-- NaturalHandBarText
IEndDragHandler <|-- NaturalHandBarText
IDropHandler <|-- NaturalHandBarText
IPointerClickHandler <|-- NaturalHandBarText
IPointerUpHandler <|-- NaturalHandBarText
ISubmitHandler <|-- NaturalHandBarText
@enduml
