@startuml
class NaturalDropdownHandler <<sealed>> {
    + ChangeColor() : void
}
MonoBehaviour <|-- NaturalDropdownHandler
NaturalDropdownHandler --> "RaycastPointerL" HandRaycastPointer
NaturalDropdownHandler --> "RaycastPointerR" HandRaycastPointer
@enduml
