@startuml
class BlendShapeClipSelector {
    + BlendShapeClipSelector(avatar:BlendShapeAvatar, onSelected:Action<BlendShapeClip>)
    + SelectGUI() : void
    + DuplicateWarn() : void
}
BlendShapeClipSelector --> "Selected" BlendShapeClip
@enduml
