@startuml
class BlendShapeClipEditorHelper <<static>> {
    + {static} DrawBlendShapeBinding(position:Rect, property:SerializedProperty, scene:PreviewSceneManager) : bool
    + {static} DrawMaterialValueBinding(position:Rect, property:SerializedProperty, scene:PreviewSceneManager) : bool
}
class TextureScale {
    + {static} Scale(tex:Texture2D, newWidth:int, newHeight:int) : void
    + {static} GetResized(texture:Texture2D, width:int, height:int) : Texture2D
}
@enduml
