@startuml
class PreviewFaceRenderer {
    + SetAmbientColor(color:Color) : void
    + PreviewFaceRenderer()
    + Render(r:Rect, background:GUIStyle, scene:PreviewSceneManager, yaw:float, pitch:float, position:Vector3) : Texture
    + Dispose() : void
}
class FogScope {
    + FogScope()
    + Dispose() : void
}
IDisposable <|-- PreviewFaceRenderer
PreviewFaceRenderer --> "PreviewCamera" Camera
PreviewFaceRenderer +-- FogScope
IDisposable <|-- FogScope
@enduml
