@startuml
class SerializedBlendShapeEditor {
    + {static} BlendShapeBindingHeight : int = 60
    + SerializedBlendShapeEditor(serializedObject:SerializedObject, previewSceneManager:PreviewSceneManager)
    + SerializedBlendShapeEditor(blendShapeClip:BlendShapeClip, previewSceneManager:PreviewSceneManager)
    + SerializedBlendShapeEditor(serializedObject:SerializedObject, targetObject:BlendShapeClip, previewSceneManager:PreviewSceneManager)
    + Draw() : DrawResult
}
struct DrawResult {
    + Changed : bool
}
SerializedBlendShapeEditor +-- DrawResult
@enduml
