@startuml
class GlbScriptedImporterEditor {
    + <<override>> OnEnable() : void
    + <<override>> OnDisable() : void
    + <<override>> OnInspectorGUI() : void
}
enum Tabs {
    Model,
    Animation,
    Materials,
}
RemapScriptedImporterEditorBase <|-- GlbScriptedImporterEditor
GlbScriptedImporterEditor +-- Tabs
@enduml
