@startuml
abstract class RemapEditorBase {
    + {static} ExtractSubAsset(subAsset:UnityEngine.Object, destinationPath:string, isForceUpdate:bool) : UnityEngine.Object
    + {static} ClearExternalObjects(importer:ScriptedImporter, targetTypes:Type[]) : void
}
class "Dictionary`2"<T1,T2> {
}
struct SubAssetPair {
    + SubAssetPair(key:SubAssetKey, o:UnityEngine.Object)
}
RemapEditorBase +-- SubAssetPair
SubAssetPair --> "Type" String
SubAssetPair --> "Name" String
SubAssetPair --> "Key" SubAssetKey
@enduml
