@startuml
class TextureExtractor {
    + TextureExtractor(data:GltfData, textureDirectory:UnityPath, subAssets:IReadOnlyDictionary<SubAssetKey, Texture>)
    + {static} GetExt(mime:string, uri:string) : string
    + Extract(key:SubAssetKey, texDesc:TextureDescriptor) : void
    + {static} ExtractTextures(data:GltfData, textureDirectory:UnityPath, textureDescriptorGenerator:ITextureDescriptorGenerator, subAssets:IReadOnlyDictionary<SubAssetKey, Texture>, addRemap:Action<SubAssetKey, Texture2D>, onCompleted:Action<IEnumerable<UnityPath>>) : void
}
class "Dictionary`2"<T1,T2> {
}
TextureExtractor --> "Data" GltfData
TextureExtractor --> "GLTF" glTF
TextureExtractor o-> "Textures<SubAssetKey,UnityPath>" "Dictionary`2"
@enduml
