@startuml
class BuiltInGltfMaterialExporter {
    + ExportMaterial(m:Material, textureExporter:ITextureExporter, settings:GltfExportSettings) : glTFMaterial
}
IMaterialExporter <|-- BuiltInGltfMaterialExporter
@enduml
