@startuml
class Model {
    + Model(coordinates:Coordinates)
    + AssetVersion : string = "2.0"
    + AssetGenerator : string
    + AssetCopyright : string
    + AssetMinVersion : string
    + SetRoot(root:Node) : void
    + GetBoneMap() : Dictionary<HumanoidBones, Node>
    + <<override>> ToString() : string
    + CheckVrmHumanoid() : bool
    + {static} GetNode(root:Node, path:string) : Node
    + ApplyRotationAndScale() : void
    + NodeAdd(node:Node, parent:Node) : void
    + NodeRemove(remove:Node) : void
    + SkinningBake(arrayManager:INativeArrayManager) : string
    + ConvertCoordinate(coordinates:Coordinates, ignoreVrm:bool) : void
}
class "List`1"<T> {
}
struct Reverser {
}
class "Action`1"<T> {
}
class "Func`2"<T1,T2> {
}
Model --> "Coordinates" Coordinates
Model o-> "Materials<object>" "List`1"
Model o-> "Skins<Skin>" "List`1"
Model o-> "MeshGroups<MeshGroup>" "List`1"
Model --> "Root" Node
Model o-> "Nodes<Node>" "List`1"
Model +-- Reverser
Reverser --> "ReverseBuffer<BufferAccessor>" "Action`1"
Reverser --> "ReverseVector3<Vector3,Vector3>" "Func`2"
Reverser --> "ReverseMatrix<Matrix4x4,Matrix4x4>" "Func`2"
@enduml
