@startuml
class MaterialExtensions <<static>> {
    + {static} SetKeyword(mat:Material, keyword:string, isEnabled:bool) : void
    + {static} GetInt(mat:Material, prop:MToon10Prop) : int
    + {static} SetInt(mat:Material, prop:MToon10Prop, val:int) : void
    + {static} GetTexture(mat:Material, prop:MToon10Prop) : Texture
    + {static} GetTextureScale(mat:Material, prop:MToon10Prop) : Vector2
    + {static} GetTextureOffset(mat:Material, prop:MToon10Prop) : Vector2
    + {static} GetFloat(mat:Material, prop:MToon10Prop) : float
    + {static} GetColor(mat:Material, prop:MToon10Prop) : Color
}
@enduml
