@startuml
class InitTracking {
    + BeginTracking() : void
    + EndTracking() : void
}
MonoBehaviour <|-- InitTracking
InitTracking o-> "humanoidTracking" HumanoidTracking
InitTracking o-> "beginBtn" Button
@enduml
