@startuml
class JsonParserTest {
    + Tests() : void
    + NullTest() : void
    + BooleanTest() : void
    + NumberTest() : void
    + StringTest() : void
    + StringEscapeTest() : void
    + ObjectTest() : void
    + NestedObjectTest() : void
    + ArrayTest() : void
    + ParseTest() : void
    + Utf8Test() : void
    + TimeTest() : void
}
@enduml
