@startuml
class SkeletonEstimator <<static>> {
    {static} + DetectByName(root:Node, map:Dictionary<string, HumanoidBones>) : Dictionary<HumanoidBones, Node>
    {static} + DetectByPosition(root:Node) : Dictionary<HumanoidBones, Node>
    {static} + Detect(root:Node) : Dictionary<HumanoidBones, Node>
}
struct Arm {
}
struct Leg {
}
SkeletonEstimator +-- Arm
Arm --> "Shoulder" Node
Arm --> "UpperArm" Node
Arm --> "LowerArm" Node
Arm --> "Hand" Node
SkeletonEstimator +-- Leg
Leg --> "UpperLeg" Node
Leg --> "LowerLeg" Node
Leg --> "Foot" Node
Leg --> "Toes" Node
@enduml
