@startuml
class ControllerInput_Editor {
    + <<override>> OnInspectorGUI() : void
}
class InputManager {
}
class Axis {
    + name : string
    + descriptiveName : string
    + descriptiveNegativeName : string
    + negativeButton : string
    + positiveButton : string
    + altNegativeButton : string
    + altPositiveButton : string
    + gravity : float = 0.0f
    + dead : float = 0.001f
    + sensitivity : float = 1.0f
    + snap : bool = false
    + invert : bool = false
    + type : int = 2
    + axis : int = 0
    + joyNum : int = 0
}
Editor <|-- ControllerInput_Editor
InputManager +-- Axis
@enduml
