@startuml
class TopMenuImplementation <<static>> {
    + {static} ExportGameObjectToGltfFile() : void
    + {static} ImportGltfFileToGameObject() : void
    + {static} GenerateSerializationCode() : void
}
@enduml
