@startuml
class Utils <<static>> <<partial>> {
    + <<const>> ShaderName : string = "VRM/MToon"
    + <<const>> PropVersion : string = "_MToonVersion"
    + <<const>> PropDebugMode : string = "_DebugMode"
    + <<const>> PropOutlineWidthMode : string = "_OutlineWidthMode"
    + <<const>> PropOutlineColorMode : string = "_OutlineColorMode"
    + <<const>> PropBlendMode : string = "_BlendMode"
    + <<const>> PropCullMode : string = "_CullMode"
    + <<const>> PropOutlineCullMode : string = "_OutlineCullMode"
    + <<const>> PropCutoff : string = "_Cutoff"
    + <<const>> PropColor : string = "_Color"
    + <<const>> PropShadeColor : string = "_ShadeColor"
    + <<const>> PropMainTex : string = "_MainTex"
    + <<const>> PropShadeTexture : string = "_ShadeTexture"
    + <<const>> PropBumpScale : string = "_BumpScale"
    + <<const>> PropBumpMap : string = "_BumpMap"
    + <<const>> PropReceiveShadowRate : string = "_ReceiveShadowRate"
    + <<const>> PropReceiveShadowTexture : string = "_ReceiveShadowTexture"
    + <<const>> PropShadingGradeRate : string = "_ShadingGradeRate"
    + <<const>> PropShadingGradeTexture : string = "_ShadingGradeTexture"
    + <<const>> PropShadeShift : string = "_ShadeShift"
    + <<const>> PropShadeToony : string = "_ShadeToony"
    + <<const>> PropLightColorAttenuation : string = "_LightColorAttenuation"
    + <<const>> PropIndirectLightIntensity : string = "_IndirectLightIntensity"
    + <<const>> PropRimColor : string = "_RimColor"
    + <<const>> PropRimTexture : string = "_RimTexture"
    + <<const>> PropRimLightingMix : string = "_RimLightingMix"
    + <<const>> PropRimFresnelPower : string = "_RimFresnelPower"
    + <<const>> PropRimLift : string = "_RimLift"
    + <<const>> PropSphereAdd : string = "_SphereAdd"
    + <<const>> PropEmissionColor : string = "_EmissionColor"
    + <<const>> PropEmissionMap : string = "_EmissionMap"
    + <<const>> PropOutlineWidthTexture : string = "_OutlineWidthTexture"
    + <<const>> PropOutlineWidth : string = "_OutlineWidth"
    + <<const>> PropOutlineScaledMaxDistance : string = "_OutlineScaledMaxDistance"
    + <<const>> PropOutlineColor : string = "_OutlineColor"
    + <<const>> PropOutlineLightingMix : string = "_OutlineLightingMix"
    + <<const>> PropUvAnimMaskTexture : string = "_UvAnimMaskTexture"
    + <<const>> PropUvAnimScrollX : string = "_UvAnimScrollX"
    + <<const>> PropUvAnimScrollY : string = "_UvAnimScrollY"
    + <<const>> PropUvAnimRotation : string = "_UvAnimRotation"
    + <<const>> PropSrcBlend : string = "_SrcBlend"
    + <<const>> PropDstBlend : string = "_DstBlend"
    + <<const>> PropZWrite : string = "_ZWrite"
    + <<const>> PropAlphaToMask : string = "_AlphaToMask"
    + <<const>> KeyNormalMap : string = "_NORMALMAP"
    + <<const>> KeyAlphaTestOn : string = "_ALPHATEST_ON"
    + <<const>> KeyAlphaBlendOn : string = "_ALPHABLEND_ON"
    + <<const>> KeyAlphaPremultiplyOn : string = "_ALPHAPREMULTIPLY_ON"
    + <<const>> KeyOutlineWidthWorld : string = "MTOON_OUTLINE_WIDTH_WORLD"
    + <<const>> KeyOutlineWidthScreen : string = "MTOON_OUTLINE_WIDTH_SCREEN"
    + <<const>> KeyOutlineColorFixed : string = "MTOON_OUTLINE_COLOR_FIXED"
    + <<const>> KeyOutlineColorMixed : string = "MTOON_OUTLINE_COLOR_MIXED"
    + <<const>> KeyDebugNormal : string = "MTOON_DEBUG_NORMAL"
    + <<const>> KeyDebugLitShadeRate : string = "MTOON_DEBUG_LITSHADERATE"
    + <<const>> TagRenderTypeKey : string = "RenderType"
    + <<const>> TagRenderTypeValueOpaque : string = "Opaque"
    + <<const>> TagRenderTypeValueTransparentCutout : string = "TransparentCutout"
    + <<const>> TagRenderTypeValueTransparent : string = "Transparent"
    + <<const>> DisabledIntValue : int = 0
    + <<const>> EnabledIntValue : int = 1
    + {static} GetRenderQueueRequirement(renderMode:RenderMode) : RenderQueueRequirement
}
@enduml
