@startuml
class Utf8StringTests {
    + Utf8StringTest() : void
    + ShortUtf8Test() : void
    + QuoteTest() : void
    + SplitTest() : void
    + SplitIntegerTest() : void
    + AtoiTest() : void
    + ToCharTest() : void
    + FromStringTest() : void
    + UnicodeEscapeTest() : void
}
@enduml
