@startuml
class BoneMappingEditor {
    + <<override>> OnInspectorGUI() : void
}
struct Bone {
    + Bone(head:Transform, tail:Transform)
    + Draw() : void
}
struct BoneDef {
    + BoneDef(head:HumanBodyBones, tail:HumanBodyBones)
}
Editor <|-- BoneMappingEditor
BoneMappingEditor +-- Bone
Bone --> "Head" Transform
Bone --> "Tail" Transform
BoneMappingEditor +-- BoneDef
BoneDef --> "Head" HumanBodyBones
BoneDef --> "Tail" HumanBodyBones
@enduml
