@startuml
class BoneNode {
    + BoneNode(bone:HumanBodyBones, muscles:int[])
    + GetEnumerator() : IEnumerator<BoneNode>
    + Add(child:BoneNode) : void
}
class BoneTreeViewItem {
    + BoneTreeViewItem(id:int, depth:int, bone:HumanBodyBones)
}
class MuscleTreeViewItem {
    + Muscle : int <<get>>
    + MuscleTreeViewItem(id:int, depth:int, muscle:int)
}
class BoneTreeView {
    + Begin() : void
    + End() : void
    + BoneTreeView(treeViewState:TreeViewState, header:MultiColumnHeader, handler:HumanPoseHandler)
    + {static} CreateDefaultMultiColumnHeaderState() : MultiColumnHeaderState
}
class MuscleInspectorEditor {
    + <<override>> OnInspectorGUI() : void
}
class "IEnumerable`1"<T> {
}
class "List`1"<T> {
}
"IEnumerable`1" "<BoneNode>" <|-- BoneNode
BoneNode --> "Bone" HumanBodyBones
BoneNode o-> "Children<BoneNode>" "List`1"
TreeViewItem <|-- BoneTreeViewItem
TreeViewItem <|-- MuscleTreeViewItem
TreeView <|-- BoneTreeView
Editor <|-- MuscleInspectorEditor
@enduml
