@startuml
class ControllerPointerProvider <<sealed>> {
    + SetControllerPointer(hand:XR_Hand, pointer:GameObject) : void
    + GetControllerPointer(hand:XR_Hand) : GameObject
}
class PointerStorage {
    + PointerStorage(type:XR_Hand, pointer:GameObject)
}
ControllerPointerProvider --> "Instance" ControllerPointerProvider
ControllerPointerProvider +-- PointerStorage
PointerStorage --> "hand" XR_Hand
PointerStorage --> "pointerObject" GameObject
@enduml
