@startuml
class ControllerBeamProvider <<sealed>> {
    + SetControllerBeam(hand:XR_Hand, beam:GameObject) : void
    + GetControllerBeam(hand:XR_Hand) : GameObject
}
class BeamStorage {
    + BeamStorage(type:XR_Hand, beam:GameObject)
}
ControllerBeamProvider --> "Instance" ControllerBeamProvider
ControllerBeamProvider +-- BeamStorage
BeamStorage --> "hand" XR_Hand
BeamStorage --> "beamObject" GameObject
@enduml
