@startuml
class GazePointer <<sealed>> {
    + PointerRingWidth : float <<get>> <<set>>
    + PointerCircleRadius : float <<get>> <<set>>
    + PointerDistance : float <<get>> <<set>>
    + PointerRenderQueue : int <<get>> <<set>>
    + PointerSortingOrder : int <<get>> <<set>>
    + ShowPointer : bool <<get>> <<set>>
    + RingPercent : int <<get>> <<set>>
    + GetPointerPosition() : Vector3
    + OnTracking(tracking:bool, localOffset:Vector3) : void
}
MonoBehaviour <|-- GazePointer
GazePointer --> "PointerColor" Color
GazePointer --> "ProgressColor" Color
GazePointer --> "PointerMaterial" Material
@enduml
