@startuml
class HandBeam <<sealed>> {
    + ShowBeam : bool <<get>> <<set>>
    + EndOffsetMin : float <<get>> <<set>>
    + EndOffsetMax : float <<get>> <<set>>
    + EndOffset : float <<get>> <<set>>
    + StartOffset : float <<get>> <<set>>
    + EndWidth : float <<get>> <<set>>
    + StartWidth : float <<get>> <<set>>
    + UseDefaultMaterial : bool <<get>> <<set>>
    + Update() : void
    + SetEffectiveBeam(effective:bool) : void
}
MonoBehaviour <|-- HandBeam
HandBeam --> "EndColor" Color32
HandBeam --> "StartColor" Color32
HandBeam --> "CustomMaterial" Material
@enduml
