@startuml
class InteractionModeManager <<sealed>> {
    + EyeTracking : bool <<get>> <<set>>
    + Movable : bool <<get>> <<set>>
    + TimerControl : bool <<get>> <<set>>
    + TimeToGaze : float <<get>> <<set>>
    + ButtonControl : bool <<get>> <<set>>
    + EnableEyeTracking : bool <<get>> <<set>>
    + DominantEvent : bool <<get>> <<set>>
    + NonDominantEvent : bool <<get>> <<set>>
    + FixedBeamLength : float <<get>> <<set>>
    + m_DominantElectronicHand : bool = false
    + m_NonDominantElectronicHand : bool = false
    + UseDefaultPinch : bool <<get>> <<set>>
    + PinchOnThreshold : float <<get>> <<set>>
    + PinchOffThreshold : float <<get>> <<set>>
    + PinchTimeToDrag : float <<get>> <<set>>
    + InitialStartNaturalHand : bool <<get>> <<set>>
    + InitialStartElectronicHand : bool <<get>> <<set>>
    + ShowElectronicHandIfSupported : bool <<get>> <<set>>
}
enum InputTypes {
    Default= 1,
    Gaze= 2,
    Controller= 3,
    Hand= 4,
}
MonoBehaviour <|-- InteractionModeManager
InteractionModeManager o-> "InputModuleGaze" GazeInputModule
InteractionModeManager o-> "InputModuleController" ControllerInputModule
InteractionModeManager o-> "InputModuleHand" HandInputModule
InteractionModeManager --> "DominantRaycastMask" LayerMask
InteractionModeManager --> "NonDominantRaycastMask" LayerMask
InteractionModeManager --> "DominantController" GameObject
InteractionModeManager --> "NonDominantController" GameObject
InteractionModeManager o-> "DominantElectronicHand" GameObject
InteractionModeManager o-> "NonDominantElectronicHand" GameObject
InteractionModeManager --> "RightHandSelector" GameObject
InteractionModeManager --> "LeftHandSelector" GameObject
InteractionModeManager --> "Instance" InteractionModeManager
InteractionModeManager +-- InputTypes
@enduml
