@startuml
enum MToon10Prop {
    AlphaMode,
    TransparentWithZWrite,
    AlphaCutoff,
    RenderQueueOffsetNumber,
    DoubleSided,
    BaseColorFactor,
    BaseColorTexture,
    ShadeColorFactor,
    ShadeColorTexture,
    NormalTexture,
    NormalTextureScale,
    ShadingShiftFactor,
    ShadingShiftTexture,
    ShadingShiftTextureScale,
    ShadingToonyFactor,
    GiEqualizationFactor,
    EmissiveFactor,
    EmissiveTexture,
    MatcapColorFactor,
    MatcapTexture,
    ParametricRimColorFactor,
    ParametricRimFresnelPowerFactor,
    ParametricRimLiftFactor,
    RimMultiplyTexture,
    RimLightingMixFactor,
    OutlineWidthMode,
    OutlineWidthFactor,
    OutlineWidthMultiplyTexture,
    OutlineColorFactor,
    OutlineLightingMixFactor,
    UvAnimationMaskTexture,
    UvAnimationScrollXSpeedFactor,
    UvAnimationScrollYSpeedFactor,
    UvAnimationRotationSpeedFactor,
    UnityCullMode,
    UnitySrcBlend,
    UnityDstBlend,
    UnityZWrite,
    UnityAlphaToMask,
    EditorEditMode,
}
@enduml
