@startuml
class TextureExporter <<sealed>> {
    + TextureExporter(textureSerializer:ITextureSerializer)
    + Dispose() : void
    + Export() : List<(Texture2D, ColorSpace)>
    + RegisterExportingAsSRgb(src:Texture, needsAlpha:bool) : int
    + RegisterExportingAsLinear(src:Texture, needsAlpha:bool) : int
    + RegisterExportingAsCombinedGltfPbrParameterTextureFromUnityStandardTextures(metallicSmoothTexture:Texture, smoothness:float, occlusionTexture:Texture) : int
    + RegisterExportingAsNormal(src:Texture) : int
}
ITextureExporter <|-- TextureExporter
@enduml
