@startuml
class TextureExportParam <<sealed>> {
    + OptionFactor : float <<get>>
    + NeedsAlpha : bool <<get>> <<set>>
    + TextureExportParam(exportType:TextureExportTypes, exportColorSpace:ColorSpace, primaryTexture:Texture, secondaryTexture:Texture, optionFactor:float, needsAlpha:bool, creator:Func<(Texture2D, bool IsDisposable)>)
    + EqualsAsKey(other:TextureExportParam) : bool
}
class "Func`1"<T> {
}
TextureExportParam --> "ExportType" TextureExportTypes
TextureExportParam --> "ExportColorSpace" ColorSpace
TextureExportParam --> "PrimaryTexture" Texture
TextureExportParam --> "SecondaryTexture" Texture
TextureExportParam --> "Creator<(Texture2D, bool IsDisposable)>" "Func`1"
@enduml
