@startuml
class Vrm10FirstPersonLayerSettings <<static>> {
    + <<const>> DEFAULT_FIRSTPERSON_ONLY_LAYER : int = 9
    + <<const>> FIRSTPERSON_ONLY_LAYER_NAME : string = "VRMFirstPersonOnly"
    + <<const>> DEFAULT_THIRDPERSON_ONLY_LAYER : int = 10
    + <<const>> THIRDPERSON_ONLY_LAYER_NAME : string = "VRMThirdPersonOnly"
    + {static} GetLayer(arg:int?, name:string, fallback:int) : int
    + {static} GetFirstPersonOnlyLayer(arg:int?) : int
    + {static} GetThirdPersonOnlyLayer(arg:int?) : int
}
@enduml
