@startuml
class VisitorSites {
    + {static} GetSiteList() : SiteList
    + {static} SaveSiteList(sites:SiteList) : void
}
class Site {
    + name : string
    + siteLocation : string
}
class SiteList {
    + Add(site:Site) : void
    + Remove(site:Site) : void
    + Find(match:System.Predicate<Site>) : Site
}
class "List`1"<T> {
}
MonoBehaviour <|-- VisitorSites
VisitorSites +-- Site
VisitorSites +-- SiteList
IEnumerator <|-- SiteList
IEnumerable <|-- SiteList
SiteList o-> "list<Site>" "List`1"
@enduml
