@startuml
class BuiltInGltfMaterialDescriptorGenerator <<sealed>> {
    + Get(data:GltfData, i:int) : MaterialDescriptor
    + GetGltfDefault() : MaterialDescriptor
}
IMaterialDescriptorGenerator <|-- BuiltInGltfMaterialDescriptorGenerator
@enduml
