@startuml
class BraceletPose {
    + IsLeft : bool <<get>> <<set>>
}
enum BraceletMode {
    bottom= 0,
    side= 1,
}
MonoBehaviour <|-- BraceletPose
BraceletPose --> "Bracelet" GameObject
BraceletPose +-- BraceletMode
@enduml
