@startuml
class SwitchPanels {
    + ShowPanels() : void
}
enum ShowPanelOption {
    ShowAll= 0,
    ShowPanels1= 1,
    ShowPanels2= 2,
    HideAll= 3,
}
class "List`1"<T> {
}
MonoBehaviour <|-- SwitchPanels
SwitchPanels o-> "Panels1<GameObject>" "List`1"
SwitchPanels o-> "Panels2<GameObject>" "List`1"
SwitchPanels +-- ShowPanelOption
@enduml
