@startuml
class MeshExportUtil <<static>> {
}
class BlendShapeBuffer {
    + BlendShapeBuffer(reserve:int)
    + Set(index:int, position:Vector3, normal:Vector3) : void
    + ToGltf(data:ExportingGltfData, useNormal:bool, useSparse:bool) : gltfMorphTarget
}
class VertexBuffer {
    + ContainsTriangle(v0:int, v1:int, v2:int) : bool
    + VertexBuffer(vertexCount:int, getJointIndex:Func<int, int>)
    + PushVertex(index:int, position:Vector3, normal:Vector3, uv:Vector2) : void
    + PushColor(color:Vector4) : void
    + PushBoneWeight(boneWeight:BoneWeight) : void
    + ToGltfPrimitive(data:ExportingGltfData, materialIndex:int, indices:IEnumerable<int>) : glTFPrimitives
}
MeshExportUtil +-- BlendShapeBuffer
MeshExportUtil +-- VertexBuffer
@enduml
