@startuml
class PrimitiveExtensions <<static>> {
    + {static} HasNormal(primitives:glTFPrimitives) : bool
    + {static} HasTexCoord0(primitives:glTFPrimitives) : bool
    + {static} HasTexCoord1(primitives:glTFPrimitives) : bool
    + {static} HasSkin(primitives:glTFPrimitives) : bool
    + {static} HasColor(primitives:glTFPrimitives) : bool
    + {static} GetPositions(primitives:glTFPrimitives, data:GltfData) : NativeArray<Vector3>
    + {static} GetNormals(primitives:glTFPrimitives, data:GltfData, positionsLength:int) : NativeArray<Vector3>?
    + {static} GetTexCoords0(primitives:glTFPrimitives, data:GltfData, positionsLength:int) : NativeArray<Vector2>?
    + {static} GetTexCoords1(primitives:glTFPrimitives, data:GltfData, positionsLength:int) : NativeArray<Vector2>?
    + {static} GetColors(primitives:glTFPrimitives, data:GltfData, positionsLength:int) : NativeArray<Color>?
    + {static} GetJoints(primitives:glTFPrimitives, data:GltfData, positionsLength:int) : JointsAccessor.Getter
    + {static} GetWeights(primitives:glTFPrimitives, data:GltfData, positionsLength:int) : WeightsAccessor.Getter
}
@enduml
