@startuml
enum VertexColorState {
    None,
    ExistsAndIsUsed,
    ExistsButNotUsed,
    ExistsAndMixed,
}
class VertexColorUtility <<static>> {
    + {static} DetectVertexColor(mesh:Mesh, materials:IEnumerable<Material>) : VertexColorState
}
@enduml
