@startuml
class DictionaryJsonSchema {
    + <<readonly>> MinProperties : int
    + DictionaryJsonSchema(source:JsonSchemaSource, useUpperCamelName:bool)
    + <<override>> ValueType : string <<get>>
    + <<override>> IsInline : bool <<get>>
    + <<override>> CreateSerializationCondition(argName:string) : string
    + <<override>> GenerateDeserializerCall(callName:string, argName:string) : string
    + <<override>> GenerateSerializerCall(callName:string, argName:string) : string
    + <<override>> GenerateDeserializer(writer:TraverseContext, callName:string) : void
    + <<override>> GenerateSerializer(writer:TraverseContext, callName:string) : void
}
JsonSchemaBase <|-- DictionaryJsonSchema
DictionaryJsonSchema --> "AdditionalProperties" JsonSchemaBase
@enduml
