@startuml
struct EnumValue {
    + Name : string
    + Value : int
    + <<override>> ToString() : string
}
class EnumJsonSchema {
    + EnumJsonSchema(source:JsonSchemaSource)
    + <<override>> ValueType : string <<get>>
    + <<override>> IsInline : bool <<get>>
    + <<override>> GenerateDeserializerCall(callName:string, argName:string) : string
    + <<override>> CreateSerializationCondition(argName:string) : string
    + <<override>> GenerateSerializerCall(callName:string, argName:string) : string
    + <<override>> ToString() : string
}
class EnumStringJsonSchema {
    + EnumStringJsonSchema(source:JsonSchemaSource)
    + <<override>> ValueType : string <<get>>
    + <<override>> IsInline : bool <<get>>
    + <<override>> GenerateDeserializerCall(callName:string, argName:string) : string
    + <<override>> CreateSerializationCondition(argName:string) : string
    + <<override>> GenerateSerializerCall(callName:string, argName:string) : string
    + <<override>> ToString() : string
}
JsonSchemaBase <|-- EnumJsonSchema
JsonSchemaBase <|-- EnumStringJsonSchema
@enduml
