@startuml
class ExtensionJsonSchema {
    + ExtensionJsonSchema(source:JsonSchemaSource)
    + <<override>> ValueType : string <<get>>
    + <<override>> IsInline : bool <<get>>
    + <<override>> GenerateDeserializerCall(callName:string, argName:string) : string
    + <<override>> CreateSerializationCondition(argName:string) : string
    + <<override>> GenerateSerializerCall(callName:string, argName:string) : string
}
JsonSchemaBase <|-- ExtensionJsonSchema
@enduml
