@startuml
class ObjectJsonSchema {
    + ObjectJsonSchema(source:JsonSchemaSource, useUpperCamelName:bool)
    + <<override>> ToString() : string
    + <<override>> ValueType : string <<get>>
    + <<override>> IsInline : bool <<get>>
    + <<override>> GenerateDeserializerCall(callName:string, argName:string) : string
    + <<override>> GenerateDeserializer(writer:TraverseContext, callName:string) : void
    + <<override>> CreateSerializationCondition(argName:string) : string
    + <<override>> GenerateSerializer(writer:TraverseContext, callName:string) : void
    + <<override>> GenerateSerializerCall(callName:string, argName:string) : string
}
class "Dictionary`2"<T1,T2> {
}
JsonSchemaBase <|-- ObjectJsonSchema
ObjectJsonSchema o-> "Properties<string,JsonSchemaBase>" "Dictionary`2"
@enduml
