@startuml
class StringJsonSchema {
    + <<readonly>> Pattern : string
    + StringJsonSchema(source:JsonSchemaSource)
    + <<override>> ValueType : string <<get>>
    + <<override>> IsInline : bool <<get>>
    + <<override>> CreateSerializationCondition(argName:string) : string
    + <<override>> GenerateDeserializerCall(callName:string, argName:string) : string
    + <<override>> GenerateSerializerCall(callName:string, argName:string) : string
}
JsonSchemaBase <|-- StringJsonSchema
@enduml
