@startuml
class TraverseContext {
    + TraverseContext(writer:TextWriter)
    + Write(s:string) : void
}
class "HashSet`1"<T> {
}
TraverseContext --> "Writer" TextWriter
TraverseContext o-> "Used<string>" "HashSet`1"
@enduml
