@startuml
class VRMMetaObjectEditor {
    + <<override>> OnInspectorGUI() : void
}
class ValidateProperty {
    + ValidateProperty(prop:SerializedProperty, validator:Validator)
    + OnGUI() : void
}
enum MessageKeys {
    PERSONATION,
    ALLOWED_USER,
    VIOLENT_USAGE,
    SEXUAL_USAGE,
    COMMERCIAL_USAGE,
    REDISTRIBUTION_MODIFICATIONS,
    SCREENSHOT,
    SCREENSHOT_BUTTON,
}
Editor <|-- VRMMetaObjectEditor
VRMMetaObjectEditor +-- ValidateProperty
ValidateProperty --> "m_prop" SerializedProperty
VRMMetaObjectEditor +-- MessageKeys
@enduml
