@startuml
class TrainedLimbDataSO {
}
ScriptableObject <|-- TrainedLimbDataSO
TrainedLimbDataSO --> "ChestRotation" ChestDataSO
TrainedLimbDataSO --> "UpperLimbVertical" UpperLimbDataSO
TrainedLimbDataSO --> "UpperLimbHorizontal" UpperLimbDataSO
TrainedLimbDataSO --> "ElbowFlexion" ElbowFlexionDataSO
TrainedLimbDataSO --> "LowerLimbRotation" LowerLimbRotationDataSO
@enduml
