@startuml
class UserDataSO {
}
enum TrainedLimb {
    Left,
    Right,
}
ScriptableObject <|-- UserDataSO
UserDataSO --> "SimulationStartTime" DateTime
UserDataSO --> "SimulationEndTime" DateTime
UserDataSO --> "TrainedLimb" TrainedLimb
UserDataSO --> "InitialData" InitialDataSO
UserDataSO --> "TrainedLimbData" TrainedLimbDataSO
UserDataSO --> "ReferenceLimbData" ReferenceLimbDataSO
@enduml
