@startuml
class VRM10MetaEditor {
    + VRM10MetaEditor(serializedObject:SerializedObject, property:SerializedProperty)
    + {static} Create(serializedObject:SerializedObject) : VRM10MetaEditor
}
enum MessageKeys {
    PERSONATION,
    ALLOWED_USER,
    VIOLENT_USAGE,
    SEXUAL_USAGE,
    COMMERCIAL_USAGE,
    POLITICAL_USAGE,
    ANTI_USAGE,
    REDISTRIBUTION_MODIFICATIONS,
    MOD_CREDIT,
    MOD_REDISTRIBUTION,
    MOD_MODIFICATION,
    MOD_OTHER,
}
SerializedPropertyEditor <|-- VRM10MetaEditor
VRM10MetaEditor +-- MessageKeys
@enduml
