@startuml
class ControllerPointerTracker <<sealed>> {
}
MonoBehaviour <|-- ControllerPointerTracker
ControllerPointerTracker --> "Instance" ControllerPointerTracker
ControllerPointerTracker --> "TrackerType" XR_Hand
@enduml
