@startuml
class PoseEventList {
}
class UnityPoseEvent {
}
class PoseEvent {
    + PoseEvent()
    + <<override>> Update() : void
}
class "EventHandlers`1"<T> {
}
class "UnityEvent`1"<T> {
}
"EventHandlers`1" "<PoseEvent>" <|-- PoseEventList
PoseEventList --> "value" Pose
"UnityEvent`1" "<Pose>" <|-- UnityPoseEvent
EventHandler <|-- PoseEvent
PoseEvent --> "poseEvent" UnityPoseEvent
PoseEvent --> "value" Pose
@enduml
