@startuml
class AngleComputeDebugging {
    + isExecuted : bool = false
    + horizontalRight : bool = false
    + verticalRight : bool = false
    + rotationRight : bool = false
    + extensionRight : bool = false
    + supinationRight : bool = false
    + horizontalLeft : bool = false
    + verticalLeft : bool = false
    + rotationLeft : bool = false
    + extensionLeft : bool = false
    + supinationLeft : bool = false
    + chestRotation : bool = false
    + DebugAll() : void
}
MonoBehaviour <|-- AngleComputeDebugging
AngleComputeDebugging --> "upperLimbAngleCalculator" UpperLimbAngleCalculator
AngleComputeDebugging --> "trackerChest" Transform
AngleComputeDebugging --> "trackerElbowLeft" Transform
AngleComputeDebugging --> "controllerLeft" Transform
AngleComputeDebugging --> "trackerElbowRight" Transform
AngleComputeDebugging --> "controllerRight" Transform
@enduml
