@startuml
class LineRendererVisualizer {
    + rayLength : float = 1.0f
}
enum RayDirection {
    Forward,
    Up,
    Right,
}
MonoBehaviour <|-- LineRendererVisualizer
LineRendererVisualizer o-> "rayDirectionEnum" RayDirection
LineRendererVisualizer o-> "color" Color
LineRendererVisualizer +-- RayDirection
@enduml
