@startuml
class VRMFirstPersonCameraManager {
}
class CameraWithRawImage {
}
MonoBehaviour <|-- VRMFirstPersonCameraManager
VRMFirstPersonCameraManager +-- CameraWithRawImage
CameraWithRawImage --> "Camera" Camera
CameraWithRawImage --> "Texture" RenderTexture
CameraWithRawImage --> "Image" RawImage
@enduml
