@startuml
class VRMFirstPerson {
    + {static} TriedSetupLayer : bool = false
    + {static} FIRSTPERSON_ONLY_LAYER : int = 9
    + {static} THIRDPERSON_ONLY_LAYER : int = 10
    + CopyTo(_dst:GameObject, map:Dictionary<Transform, Transform>) : void
    + SetDefault() : void
    + Reset() : void
    + TraverseRenderers(context:VRMImporterContext) : void
    + {static} SetupLayers() : void
    + {static} SetVisibility(renderer:Renderer, firstPerson:bool, thirdPerson:bool) : void
    + {static} SetVisiblity(renderer:Renderer, firstPerson:bool, thirdPerson:bool) : void
    + Setup() : void
    + Setup(isSelf:bool, setVisibility:SetVisibilityFunc) : void
}
struct RendererFirstPersonFlags {
}
class "List`1"<T> {
}
MonoBehaviour <|-- VRMFirstPerson
VRMFirstPerson --> "FirstPersonBone" Transform
VRMFirstPerson --> "FirstPersonOffset" Vector3
VRMFirstPerson o-> "Renderers<RendererFirstPersonFlags>" "List`1"
VRMFirstPerson +-- RendererFirstPersonFlags
RendererFirstPersonFlags --> "Renderer" Renderer
RendererFirstPersonFlags --> "FirstPersonFlag" FirstPersonFlag
RendererFirstPersonFlags --> "SharedMesh" Mesh
@enduml
