@startuml
class XR_EXT_hand_tracking <<static>> {
    + {static} GetRotation(up:Vector3, forward:Vector3) : Quaternion
}
class "IReadOnlyDictionary`2"<T1,T2> {
}
XR_EXT_hand_tracking o-> "LeftHand" Quaternion
XR_EXT_hand_tracking o-> "RightHand" Quaternion
XR_EXT_hand_tracking o-> "LeftThumb" Quaternion
XR_EXT_hand_tracking o-> "RightThumb" Quaternion
XR_EXT_hand_tracking --> "InitialRotations<HumanBodyBones,Quaternion>" "IReadOnlyDictionary`2"
@enduml
