@startuml
class XR_FB_body_tracking <<static>> {
    + {static} GetRotation(yAxis:Vector3, zAxis:Vector3) : Quaternion
}
class "IReadOnlyDictionary`2"<T1,T2> {
}
XR_FB_body_tracking o-> "Spine" Quaternion
XR_FB_body_tracking o-> "Left" Quaternion
XR_FB_body_tracking o-> "LeftThumb" Quaternion
XR_FB_body_tracking o-> "LeftHand" Quaternion
XR_FB_body_tracking o-> "Right" Quaternion
XR_FB_body_tracking o-> "RightThumb" Quaternion
XR_FB_body_tracking o-> "RightHand" Quaternion
XR_FB_body_tracking --> "InitialRotations<HumanBodyBones,Quaternion>" "IReadOnlyDictionary`2"
@enduml
