@startuml
class ObjectMove {
    + time : float
    + MoveSpeed : float = 10
    + AbleHit : bool
    + HitDelay : float
    + MaxLength : float
    + DestroyTime2 : float
}
MonoBehaviour <|-- ObjectMove
ObjectMove --> "m_hitObject" GameObject
@enduml
