@startuml
class PullTransformJobScheduler <<sealed>> <<unsafe>> {
    + PullTransformJobScheduler(transformRegistry:TransformRegistry)
    + Schedule(dependOn:JobHandle) : JobHandle
    + Dispose() : void
}
struct Job {
    + Execute(index:int, transform:TransformAccess) : void
}
IDisposable <|-- PullTransformJobScheduler
PullTransformJobScheduler +-- Job
IJobParallelForTransform <|-- Job
@enduml
