@startuml
class PushTransformJobScheduler <<sealed>> <<unsafe>> {
    + PushTransformJobScheduler(transformRegistry:TransformRegistry)
    + Schedule(dependOn:JobHandle) : JobHandle
    + Dispose() : void
}
struct Job {
    + Execute(index:int, transform:TransformAccess) : void
}
IDisposable <|-- PushTransformJobScheduler
PushTransformJobScheduler +-- Job
IJobParallelForTransform <|-- Job
@enduml
