@startuml
class UpdateSpringBoneJobScheduler <<sealed>> <<unsafe>> {
    + UpdateSpringBoneJobScheduler(rootBoneRegistry:RootBoneRegistry)
    + Dispose() : void
    + Schedule(dependOn:JobHandle) : JobHandle
}
struct Job {
    + DeltaTime : float
    + Execute(index:int) : void
}
IDisposable <|-- UpdateSpringBoneJobScheduler
UpdateSpringBoneJobScheduler +-- Job
IJobParallelFor <|-- Job
@enduml
