@startuml
class NativeColliderGroups <<sealed>> <<unsafe>> {
    + GetUnsafePtr() : BlittableColliderGroups*
    + DrawGizmos() : void
    + NativeColliderGroups(colliderGroups:IReadOnlyList<FastSpringBoneColliderGroup>)
    + Dispose() : void
}
class "IReadOnlyList`1"<T> {
}
IDisposable <|-- NativeColliderGroups
NativeColliderGroups --> "ColliderGroups<FastSpringBoneColliderGroup>" "IReadOnlyList`1"
@enduml
