@startuml
class "NativePointer`1"<T> <<sealed>> {
    + <<unsafe>> GetUnsafePtr() : T*
    + <<unsafe>> Value : T <<get>> <<set>>
    + <<unsafe>> NativePointer()
    + <<unsafe>> NativePointer(value:T)
    + <<unsafe>> Dispose() : void
}
IDisposable <|-- "NativePointer`1"
@enduml
