@startuml
class MeshObject {
    + MeshName : string
    + hasEffect : bool
}
class BinaryButtonObject {
    + MeshName : string
    + hasEffect : bool
    + hasAnimation : bool
    + alsoEffect : bool
    + lastState : bool
    + BinaryButtonObject()
}
class Travel1DObject {
    + MeshName : string
    + hasEffect : bool
    + hasAnimation : bool
    + isInAnimation : bool
    + Travel1DObject()
}
class TouchpadObject {
    + MeshName : string
    + hasEffect : bool
    + hasAnimation : bool
    + TouchpadObject()
}
class ThumbstickObject {
    + MeshName : string
    + hasEffect : bool
    + hasAnimation : bool
    + raidus : float
    + ThumbstickObject()
}
class CtrlerModelAnimPoseData {
    + CtrlerModelAnimPoseData()
}
class CtrlerModelAnimNodeData {
    + btnName : string
    + btnType : uint
    + alsoBlueEffect : uint
    + CtrlerModelAnimNodeData()
}
class ButtonEffect {
    + enableButtonEffect : bool = true
    + useSystemConfig : bool = true
    + collectInStart : bool = true
    + checkInteractionMode : bool = false
    + Circle(tex:Texture2D, cx:int, cy:int, r:int, col:Color) : void
}
class WVR_InputObject {
}
MeshObject --> "gameObject" GameObject
MeshObject --> "originPosition" Vector3
MeshObject --> "originMat" Material
MeshObject --> "effectMat" Material
BinaryButtonObject --> "gameObject" GameObject
BinaryButtonObject --> "originMat" Material
BinaryButtonObject --> "effectMat" Material
BinaryButtonObject --> "originPosition" Vector3
BinaryButtonObject --> "originRotation" Vector3
BinaryButtonObject --> "originScale" Vector3
BinaryButtonObject --> "pressPosition" Vector3
BinaryButtonObject --> "pressRotation" Vector3
BinaryButtonObject --> "pressScale" Vector3
Travel1DObject --> "gameObject" GameObject
Travel1DObject --> "originMat" Material
Travel1DObject --> "effectMat" Material
Travel1DObject --> "originPosition" Vector3
Travel1DObject --> "originRotation" Quaternion
Travel1DObject --> "originScale" Vector3
Travel1DObject --> "pressPosition" Vector3
Travel1DObject --> "pressRotation" Quaternion
Travel1DObject --> "pressScale" Vector3
TouchpadObject --> "gameObject" GameObject
TouchpadObject --> "originMat" Material
TouchpadObject --> "effectMat" Material
TouchpadObject --> "originPosition" Vector3
TouchpadObject --> "originRotation" Vector3
TouchpadObject --> "originScale" Vector3
TouchpadObject --> "pressPosition" Vector3
TouchpadObject --> "pressRotation" Vector3
TouchpadObject --> "pressScale" Vector3
ThumbstickObject --> "gameObject" GameObject
ThumbstickObject --> "originMat" Material
ThumbstickObject --> "effectMat" Material
ThumbstickObject --> "centerPosition" Vector3
ThumbstickObject --> "centerRotation" Vector3
ThumbstickObject --> "centerScale" Vector3
ThumbstickObject --> "upPosition" Vector3
ThumbstickObject --> "upRotation" Vector3
ThumbstickObject --> "upScale" Vector3
ThumbstickObject --> "rightPosition" Vector3
ThumbstickObject --> "rightRotation" Vector3
ThumbstickObject --> "rightScale" Vector3
ThumbstickObject --> "ptW" Vector3
ThumbstickObject --> "ptU" Vector3
ThumbstickObject --> "ptV" Vector3
ThumbstickObject --> "rtW" Vector3
ThumbstickObject --> "rtU" Vector3
ThumbstickObject --> "rtV" Vector3
ThumbstickObject --> "stW" Vector3
ThumbstickObject --> "stU" Vector3
ThumbstickObject --> "stV" Vector3
ThumbstickObject --> "xAngle" Vector3
ThumbstickObject --> "zAngle" Vector3
CtrlerModelAnimPoseData --> "position" Vector3
CtrlerModelAnimPoseData --> "rotation" Vector3
CtrlerModelAnimPoseData --> "scale" Vector3
CtrlerModelAnimNodeData --> "origin" CtrlerModelAnimPoseData
CtrlerModelAnimNodeData --> "pressed" CtrlerModelAnimPoseData
CtrlerModelAnimNodeData --> "minX" CtrlerModelAnimPoseData
CtrlerModelAnimNodeData --> "maxX" CtrlerModelAnimPoseData
CtrlerModelAnimNodeData --> "minY" CtrlerModelAnimPoseData
CtrlerModelAnimNodeData --> "maxY" CtrlerModelAnimPoseData
MonoBehaviour <|-- ButtonEffect
ButtonEffect o-> "HandType" XR_Hand
ButtonEffect o-> "buttonEffectColor" Color
ButtonEffect +-- WVR_InputObject
WVR_InputObject --> "destination" WVR_InputId
WVR_InputObject --> "sourceId" WVR_InputId
@enduml
