@startuml
class ControllerTipsLine {
    + startWidth : float = 0.0004f
    + endWidth : float = 0.0004f
    + lineLength : float = 0.03f
    + Update() : void
    + Circle(tex:Texture2D, cx:int, cy:int, r:int, col:Color) : void
    + updateMeshSettings() : void
}
MonoBehaviour <|-- ControllerTipsLine
ControllerTipsLine o-> "lineColor" Color
ControllerTipsLine o-> "alignment" Alignment
@enduml
