@startuml
enum EnableTPose {
    ENALBE_TPOSE_BUTTON,
    DISABLE_TPOSE_BUTTON,
}
class InternalTPose <<static>> {
    + {static} TrySampleBindPose(go:GameObject) : bool
    + {static} TryMakePoseValid(go:GameObject) : bool
}
struct TRS {
    + Apply(t:Transform) : void
    + {static} From(t:Transform) : TRS
}
InternalTPose +-- TRS
TRS --> "T" Vector3
TRS --> "R" Quaternion
TRS --> "S" Vector3
@enduml
