@startuml
class MeshExportValidator {
    + {static} GetMesh(r:Renderer) : Mesh
    + ExpectedExportByteSize : int <<get>>
    + SetRoot(ExportRoot:GameObject, settings:GltfExportSettings, blendShapeFilter:IBlendShapeExportFilter) : void
    + Validate(ExportRoot:GameObject) : IEnumerable<Validation>
}
enum Messages {
    MATERIALS_LESS_THAN_SUBMESH_COUNT,
    MATERIALS_GREATER_THAN_SUBMESH_COUNT,
    MATERIALS_CONTAINS_NULL,
    UNKNOWN_SHADER,
    MULTIFRAME_BLENDSHAPE,
}
ScriptableObject <|-- MeshExportValidator
MeshExportValidator o-> "Meshes" MeshExportList
MeshExportValidator o-> "MaterialValidator" IMaterialValidator
MeshExportValidator +-- Messages
@enduml
