@startuml
class Vrm10ImportData {
    + AssetVersion : string <<get>>
    + AssetMinVersion : string <<get>>
    + AssetGenerator : string <<get>>
    + AssetCopyright : string <<get>>
    + NodeCount : int <<get>>
    + TextureCount : int <<get>>
    + SkinCount : int <<get>>
    + MeshCount : int <<get>>
    + Vrm10ImportData(data:UniGLTF.GltfData)
    + GetBufferBytes(buffer:UniGLTF.glTFBuffer) : NativeArray<byte>
    + GetBufferBytes(bufferView:UniGLTF.glTFBufferView) : NativeArray<byte>
    + GetAccessorBytes(accessorIndex:int) : NativeArray<byte>
    + TryCreateAccessor(accessorIndex:int, ba:BufferAccessor) : bool
    + CreateAccessor(accessorIndex:int) : BufferAccessor
    + CreateAccessor(accessorIndices:int[]) : BufferAccessor
    + CreateBufferAccessorAndAdd(accessorIndex:int, b:VertexBuffer, key:string) : void
    + CreateNode(index:int) : Node
    + GetChildNodeIndices(i:int) : IEnumerable<int>
    + CreateSkin(index:int, nodes:List<Node>) : Skin
    + CreateMesh(index:int) : MeshGroup
    + GetNodeMeshSkin(index:int) : (int, int)
}
@enduml
