@startuml
struct PathObject {
    + FullPath : string <<get>>
    + Extension : string <<get>>
    + Stem : string <<get>>
    + IsUnderAsset : bool <<get>>
    + Exists : bool <<get>>
    + UnityAssetPath : string <<get>>
    + <<override>> ToString() : string
    + {static} FromFullPath(src:string) : PathObject
    + {static} FromUnityAssetPath(src:string) : PathObject
    + {static} TryGetFromEnvironmentVariable(key:string, dst:PathObject) : bool
    + Child(child:string) : PathObject
    + IsDescendantOf(ascendant:PathObject) : bool
    + ReadAllBytes() : byte[]
    + WriteAllBytes(data:byte[]) : void
}
PathObject --> "Parent" PathObject
PathObject o-> "UnityRoot" PathObject
PathObject o-> "UnityAssets" PathObject
@enduml
