@startuml
class VRMExporterWizard {
    + {static} OpenExportMenu() : void
}
enum Tabs {
    Meta,
    Mesh,
    BlendShape,
    ExportSettings,
}
enum BlendShapeTabMessages {
    CANNOT_MANIPULATE_PREFAB,
    SCENE_MESSAGE,
    APPLY_BLENDSHAPECLIP_BUTTON,
    CLEAR_BLENDSHAPE_BUTTON,
}
ExportDialogBase <|-- VRMExporterWizard
VRMExporterWizard +-- Tabs
VRMExporterWizard +-- BlendShapeTabMessages
@enduml
