@startuml
enum VRMExportOptions {
    FORCE_T_POSE,
    NORMALIZE,
    USE_GENERATED_SERIALIZER,
    BLENDSHAPE_USE_SPARSE,
    BLENDSHAPE_EXCLUDE_NORMAL_AND_TANGENT,
    BLENDSHAPE_ONLY_CLIP_USE,
    BLENDSHAPE_EXCLUDE_UNKNOWN,
    REMOVE_VERTEX_COLOR,
    DO_TPOSE,
    DIVIDE_VERTEX_BUFFER,
    KEEP_VERTEX_COLOR,
    EXPORT_GLTF_ANIMATION,
}
@enduml
