@startuml
class VRMExportSettings {
    + ForceTPose : bool = false
    + PoseFreeze : bool = true
    + UseSparseAccessor : bool = false
    + OnlyBlendshapePosition : bool = false
    + ReduceBlendshape : bool = false
    + ReduceBlendshapeClip : bool = false
    + DivideVertexBuffer : bool = false
    + KeepVertexColor : bool = false
    + KeepAnimation : bool = false
}
ScriptableObject <|-- VRMExportSettings
VRMExportSettings --> "GltfExportSettings" GltfExportSettings
VRMExportSettings --> "Root" GameObject
@enduml
