@startuml
class Configuration {
    + openVRSupport : bool = false
    + steamVrSupport : bool = false
    + viveTrackerSupport : bool = false
    + oculusSupport : bool = true
    + windowsMRSupport : bool = true
    + neuronSupport : bool
    + hi5Support : bool
    + realsenseSupport : bool
    + leapSupport : bool
    + kinect1Support : bool
    + kinect2Support : bool
    + kinect4Support : bool
    + astraSupport : bool
    + hydraSupport : bool
    + arkitSupport : bool
    + tobiiSupport : bool
    + optitrackSupport : bool
    + pupilSupport : bool
    + antilatencySupport : bool
    + networkingVoiceSupport : bool
    + humanoidSceneName : string
}
Configuration --> "networkingSupport" NetworkingSystems
@enduml
