@startuml
class ObjectTracker {
    + <<override>> InitSensors() : void
    + <<override>> StartSensors() : void
    + physics : bool
    + Start() : void
    + <<override>> StartTarget() : void
    + <<override>> InitializeTrackingConfidence() : void
    + <<override>> UpdateTarget() : void
    + ShowTrackers(shown:bool) : void
}
Target <|-- ObjectTracker
ObjectTracker --> "sensorComponent" SensorComponent
@enduml
