@startuml
class BuiltInGltfPbrMaterialImporter <<static>> {
    + {static} TryCreateParam(data:GltfData, i:int, matDesc:MaterialDescriptor) : bool
}
enum BlendMode {
    Opaque,
    Cutout,
    Fade,
    Transparent,
}
BuiltInGltfPbrMaterialImporter --> "Shader" Shader
BuiltInGltfPbrMaterialImporter +-- BlendMode
@enduml
