@startuml
struct JsonNode {
    + <<override>> GetHashCode() : int
    + <<override>> Equals(obj:object) : bool
    + <<override>> ToString() : string
    + ToString(indent:string) : string
    + IsValid : bool <<get>>
    + ValueIndex : int <<get>>
    + SetValue(value:JsonValue) : void
    + ChildCount : int <<get>>
    + HasParent : bool <<get>>
    + JsonNode(values:List<JsonValue>, index:int)
    + AddKey(key:Utf8String) : JsonNode
    + AddValue(bytes:ArraySegment<byte>, valueType:ValueNodeType) : JsonNode
    + AddValue(value:JsonValue) : JsonNode
    + SetValueBytesCount(count:int) : void
}
class "IEnumerable`1"<T> {
}
JsonNode --> "Prev" JsonNode
JsonNode --> "Value" JsonValue
JsonNode --> "Children<JsonNode>" "IEnumerable`1"
JsonNode --> "Parent" JsonNode
@enduml
