@startuml
class IValueNodeObjectExtensions <<static>> {
    + {static} ObjectItems(self:JsonNode) : IEnumerable<KeyValuePair<JsonNode, JsonNode>>
    + {static} GetObjectCount(self:JsonNode) : int
    + {static} GetObjectValueOrDefault(self:JsonNode, key:String, defualtValue:string) : string
    + {static} GetObjectItem(self:JsonNode, key:String) : JsonNode
    + {static} GetObjectItem(self:JsonNode, key:Utf8String) : JsonNode
    + {static} ContainsKey(self:JsonNode, key:Utf8String) : bool
    + {static} ContainsKey(self:JsonNode, key:String) : bool
    + {static} TryGet(self:JsonNode, key:Utf8String, found:JsonNode) : bool
    + {static} TryGet(self:JsonNode, key:String, found:JsonNode) : bool
    + {static} KeyOf(self:JsonNode, node:JsonNode) : Utf8String
}
@enduml
