@startuml
class GltfDeserializer <<static>> {
    + {static} TryGet(src:UniGLTF.glTFExtension, extension:VRMC_vrm) : bool
    + {static} Deserialize(parsed:JsonNode) : VRMC_vrm
    + {static} Deserialize_Meta(parsed:JsonNode) : Meta
    + {static} __meta_Deserialize_Authors(parsed:JsonNode) : List<string>
    + {static} __meta_Deserialize_References(parsed:JsonNode) : List<string>
    + {static} Deserialize_Humanoid(parsed:JsonNode) : Humanoid
    + {static} __humanoid_Deserialize_HumanBones(parsed:JsonNode) : HumanBones
    + {static} __humanoid__humanBones_Deserialize_Hips(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_Spine(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_Chest(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_UpperChest(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_Neck(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_Head(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftEye(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightEye(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_Jaw(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftUpperLeg(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftLowerLeg(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftFoot(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftToes(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightUpperLeg(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightLowerLeg(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightFoot(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightToes(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftShoulder(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftUpperArm(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftLowerArm(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftHand(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightShoulder(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightUpperArm(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightLowerArm(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightHand(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftThumbMetacarpal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftThumbProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftThumbDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftIndexProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftIndexIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftIndexDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftMiddleProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftMiddleIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftMiddleDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftRingProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftRingIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftRingDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftLittleProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftLittleIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_LeftLittleDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightThumbMetacarpal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightThumbProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightThumbDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightIndexProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightIndexIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightIndexDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightMiddleProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightMiddleIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightMiddleDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightRingProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightRingIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightRingDistal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightLittleProximal(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightLittleIntermediate(parsed:JsonNode) : HumanBone
    + {static} __humanoid__humanBones_Deserialize_RightLittleDistal(parsed:JsonNode) : HumanBone
    + {static} Deserialize_FirstPerson(parsed:JsonNode) : FirstPerson
    + {static} __firstPerson_Deserialize_MeshAnnotations(parsed:JsonNode) : List<MeshAnnotation>
    + {static} __firstPerson_Deserialize_MeshAnnotations_ITEM(parsed:JsonNode) : MeshAnnotation
    + {static} Deserialize_LookAt(parsed:JsonNode) : LookAt
    + {static} __lookAt_Deserialize_OffsetFromHeadBone(parsed:JsonNode) : float[]
    + {static} __lookAt_Deserialize_RangeMapHorizontalInner(parsed:JsonNode) : LookAtRangeMap
    + {static} __lookAt_Deserialize_RangeMapHorizontalOuter(parsed:JsonNode) : LookAtRangeMap
    + {static} __lookAt_Deserialize_RangeMapVerticalDown(parsed:JsonNode) : LookAtRangeMap
    + {static} __lookAt_Deserialize_RangeMapVerticalUp(parsed:JsonNode) : LookAtRangeMap
    + {static} Deserialize_Expressions(parsed:JsonNode) : Expressions
    + {static} __expressions_Deserialize_Preset(parsed:JsonNode) : Preset
    + {static} __expressions__preset_Deserialize_Happy(parsed:JsonNode) : Expression
    + {static} __expressions__preset__happy_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__happy_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__happy_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__happy_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__happy__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__happy_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__happy_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__happy__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__happy__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Angry(parsed:JsonNode) : Expression
    + {static} __expressions__preset__angry_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__angry_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__angry_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__angry_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__angry__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__angry_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__angry_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__angry__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__angry__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Sad(parsed:JsonNode) : Expression
    + {static} __expressions__preset__sad_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__sad_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__sad_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__sad_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__sad__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__sad_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__sad_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__sad__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__sad__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Relaxed(parsed:JsonNode) : Expression
    + {static} __expressions__preset__relaxed_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__relaxed_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__relaxed_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__relaxed_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__relaxed__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__relaxed_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__relaxed_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__relaxed__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__relaxed__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Surprised(parsed:JsonNode) : Expression
    + {static} __expressions__preset__surprised_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__surprised_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__surprised_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__surprised_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__surprised__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__surprised_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__surprised_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__surprised__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__surprised__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Aa(parsed:JsonNode) : Expression
    + {static} __expressions__preset__aa_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__aa_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__aa_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__aa_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__aa__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__aa_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__aa_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__aa__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__aa__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Ih(parsed:JsonNode) : Expression
    + {static} __expressions__preset__ih_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__ih_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__ih_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__ih_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__ih__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__ih_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__ih_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__ih__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__ih__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Ou(parsed:JsonNode) : Expression
    + {static} __expressions__preset__ou_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__ou_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__ou_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__ou_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__ou__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__ou_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__ou_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__ou__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__ou__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Ee(parsed:JsonNode) : Expression
    + {static} __expressions__preset__ee_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__ee_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__ee_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__ee_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__ee__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__ee_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__ee_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__ee__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__ee__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Oh(parsed:JsonNode) : Expression
    + {static} __expressions__preset__oh_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__oh_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__oh_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__oh_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__oh__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__oh_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__oh_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__oh__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__oh__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Blink(parsed:JsonNode) : Expression
    + {static} __expressions__preset__blink_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__blink_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__blink_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__blink_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__blink__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__blink_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__blink_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__blink__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__blink__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_BlinkLeft(parsed:JsonNode) : Expression
    + {static} __expressions__preset__blinkLeft_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__blinkLeft_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__blinkLeft_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__blinkLeft_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__blinkLeft__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__blinkLeft_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__blinkLeft_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__blinkLeft__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__blinkLeft__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_BlinkRight(parsed:JsonNode) : Expression
    + {static} __expressions__preset__blinkRight_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__blinkRight_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__blinkRight_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__blinkRight_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__blinkRight__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__blinkRight_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__blinkRight_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__blinkRight__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__blinkRight__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_LookUp(parsed:JsonNode) : Expression
    + {static} __expressions__preset__lookUp_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__lookUp_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__lookUp_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__lookUp_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__lookUp__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookUp_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__lookUp_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__lookUp__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookUp__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_LookDown(parsed:JsonNode) : Expression
    + {static} __expressions__preset__lookDown_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__lookDown_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__lookDown_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__lookDown_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__lookDown__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookDown_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__lookDown_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__lookDown__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookDown__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_LookLeft(parsed:JsonNode) : Expression
    + {static} __expressions__preset__lookLeft_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__lookLeft_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__lookLeft_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__lookLeft_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__lookLeft__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookLeft_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__lookLeft_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__lookLeft__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookLeft__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_LookRight(parsed:JsonNode) : Expression
    + {static} __expressions__preset__lookRight_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__lookRight_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__lookRight_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__lookRight_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__lookRight__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookRight_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__lookRight_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__lookRight__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__lookRight__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions__preset_Deserialize_Neutral(parsed:JsonNode) : Expression
    + {static} __expressions__preset__neutral_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__preset__neutral_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__preset__neutral_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__preset__neutral_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__preset__neutral__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__preset__neutral_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__preset__neutral_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__preset__neutral__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__preset__neutral__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
    + {static} __expressions_Deserialize_Custom(parsed:JsonNode) : Dictionary<string, Expression>
    + {static} __expressions_Deserialize_Custom_ITEM(parsed:JsonNode) : Expression
    + {static} __expressions__custom_PROP_Deserialize_MorphTargetBinds(parsed:JsonNode) : List<MorphTargetBind>
    + {static} __expressions__custom_PROP_Deserialize_MorphTargetBinds_ITEM(parsed:JsonNode) : MorphTargetBind
    + {static} __expressions__custom_PROP_Deserialize_MaterialColorBinds(parsed:JsonNode) : List<MaterialColorBind>
    + {static} __expressions__custom_PROP_Deserialize_MaterialColorBinds_ITEM(parsed:JsonNode) : MaterialColorBind
    + {static} __expressions__custom_PROP__materialColorBinds_ITEM_Deserialize_TargetValue(parsed:JsonNode) : float[]
    + {static} __expressions__custom_PROP_Deserialize_TextureTransformBinds(parsed:JsonNode) : List<TextureTransformBind>
    + {static} __expressions__custom_PROP_Deserialize_TextureTransformBinds_ITEM(parsed:JsonNode) : TextureTransformBind
    + {static} __expressions__custom_PROP__textureTransformBinds_ITEM_Deserialize_Scale(parsed:JsonNode) : float[]
    + {static} __expressions__custom_PROP__textureTransformBinds_ITEM_Deserialize_Offset(parsed:JsonNode) : float[]
}
GltfDeserializer o-> "ExtensionNameUtf8" Utf8String
@enduml
