@startuml
class GltfSerializer <<static>> {
    + {static} SerializeTo(dst:UniGLTF.glTFExtension, extension:VRMC_vrm) : void
    + {static} Serialize(f:JsonFormatter, value:VRMC_vrm) : void
    + {static} Serialize_Meta(f:JsonFormatter, value:Meta) : void
    + {static} __meta_Serialize_Authors(f:JsonFormatter, value:List<string>) : void
    + {static} __meta_Serialize_References(f:JsonFormatter, value:List<string>) : void
    + {static} Serialize_Humanoid(f:JsonFormatter, value:Humanoid) : void
    + {static} __humanoid_Serialize_HumanBones(f:JsonFormatter, value:HumanBones) : void
    + {static} __humanoid__humanBones_Serialize_Hips(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Spine(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Chest(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_UpperChest(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Neck(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Head(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftEye(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightEye(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_Jaw(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftUpperLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLowerLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftFoot(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftToes(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightUpperLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLowerLeg(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightFoot(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightToes(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftShoulder(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftUpperArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLowerArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftHand(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightShoulder(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightUpperArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLowerArm(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightHand(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftThumbMetacarpal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftThumbProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftThumbDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftIndexProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftIndexIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftIndexDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftMiddleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftMiddleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftMiddleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftRingProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftRingIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftRingDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLittleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLittleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_LeftLittleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightThumbMetacarpal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightThumbProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightThumbDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightIndexProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightIndexIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightIndexDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightMiddleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightMiddleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightMiddleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightRingProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightRingIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightRingDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLittleProximal(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLittleIntermediate(f:JsonFormatter, value:HumanBone) : void
    + {static} __humanoid__humanBones_Serialize_RightLittleDistal(f:JsonFormatter, value:HumanBone) : void
    + {static} Serialize_FirstPerson(f:JsonFormatter, value:FirstPerson) : void
    + {static} __firstPerson_Serialize_MeshAnnotations(f:JsonFormatter, value:List<MeshAnnotation>) : void
    + {static} __firstPerson_Serialize_MeshAnnotations_ITEM(f:JsonFormatter, value:MeshAnnotation) : void
    + {static} Serialize_LookAt(f:JsonFormatter, value:LookAt) : void
    + {static} __lookAt_Serialize_OffsetFromHeadBone(f:JsonFormatter, value:float[]) : void
    + {static} __lookAt_Serialize_RangeMapHorizontalInner(f:JsonFormatter, value:LookAtRangeMap) : void
    + {static} __lookAt_Serialize_RangeMapHorizontalOuter(f:JsonFormatter, value:LookAtRangeMap) : void
    + {static} __lookAt_Serialize_RangeMapVerticalDown(f:JsonFormatter, value:LookAtRangeMap) : void
    + {static} __lookAt_Serialize_RangeMapVerticalUp(f:JsonFormatter, value:LookAtRangeMap) : void
    + {static} Serialize_Expressions(f:JsonFormatter, value:Expressions) : void
    + {static} __expressions_Serialize_Preset(f:JsonFormatter, value:Preset) : void
    + {static} __expressions__preset_Serialize_Happy(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__happy_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__happy_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__happy_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__happy_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__happy__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__happy_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__happy_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__happy__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__happy__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Angry(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__angry_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__angry_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__angry_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__angry_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__angry__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__angry_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__angry_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__angry__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__angry__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Sad(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__sad_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__sad_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__sad_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__sad_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__sad__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__sad_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__sad_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__sad__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__sad__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Relaxed(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__relaxed_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__relaxed_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__relaxed_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__relaxed_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__relaxed__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__relaxed_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__relaxed_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__relaxed__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__relaxed__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Surprised(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__surprised_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__surprised_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__surprised_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__surprised_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__surprised__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__surprised_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__surprised_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__surprised__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__surprised__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Aa(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__aa_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__aa_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__aa_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__aa_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__aa__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__aa_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__aa_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__aa__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__aa__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Ih(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__ih_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__ih_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__ih_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__ih_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__ih__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__ih_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__ih_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__ih__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__ih__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Ou(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__ou_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__ou_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__ou_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__ou_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__ou__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__ou_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__ou_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__ou__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__ou__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Ee(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__ee_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__ee_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__ee_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__ee_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__ee__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__ee_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__ee_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__ee__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__ee__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Oh(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__oh_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__oh_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__oh_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__oh_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__oh__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__oh_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__oh_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__oh__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__oh__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Blink(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__blink_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__blink_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__blink_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__blink_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__blink__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__blink_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__blink_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__blink__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__blink__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_BlinkLeft(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__blinkLeft_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__blinkLeft_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__blinkLeft_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__blinkLeft_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__blinkLeft__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__blinkLeft_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__blinkLeft_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__blinkLeft__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__blinkLeft__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_BlinkRight(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__blinkRight_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__blinkRight_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__blinkRight_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__blinkRight_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__blinkRight__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__blinkRight_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__blinkRight_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__blinkRight__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__blinkRight__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_LookUp(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__lookUp_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__lookUp_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__lookUp_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__lookUp_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__lookUp__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookUp_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__lookUp_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__lookUp__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookUp__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_LookDown(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__lookDown_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__lookDown_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__lookDown_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__lookDown_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__lookDown__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookDown_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__lookDown_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__lookDown__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookDown__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_LookLeft(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__lookLeft_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__lookLeft_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__lookLeft_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__lookLeft_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__lookLeft__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookLeft_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__lookLeft_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__lookLeft__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookLeft__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_LookRight(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__lookRight_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__lookRight_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__lookRight_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__lookRight_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__lookRight__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookRight_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__lookRight_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__lookRight__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__lookRight__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset_Serialize_Neutral(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__preset__neutral_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__preset__neutral_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__preset__neutral_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__preset__neutral_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__preset__neutral__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__neutral_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__preset__neutral_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__preset__neutral__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__preset__neutral__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
    + {static} __expressions_Serialize_Custom(f:JsonFormatter, value:Dictionary<string, Expression>) : void
    + {static} __expressions_Serialize_Custom_ITEM(f:JsonFormatter, value:Expression) : void
    + {static} __expressions__custom_PROP_Serialize_MorphTargetBinds(f:JsonFormatter, value:List<MorphTargetBind>) : void
    + {static} __expressions__custom_PROP_Serialize_MorphTargetBinds_ITEM(f:JsonFormatter, value:MorphTargetBind) : void
    + {static} __expressions__custom_PROP_Serialize_MaterialColorBinds(f:JsonFormatter, value:List<MaterialColorBind>) : void
    + {static} __expressions__custom_PROP_Serialize_MaterialColorBinds_ITEM(f:JsonFormatter, value:MaterialColorBind) : void
    + {static} __expressions__custom_PROP__materialColorBinds_ITEM_Serialize_TargetValue(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__custom_PROP_Serialize_TextureTransformBinds(f:JsonFormatter, value:List<TextureTransformBind>) : void
    + {static} __expressions__custom_PROP_Serialize_TextureTransformBinds_ITEM(f:JsonFormatter, value:TextureTransformBind) : void
    + {static} __expressions__custom_PROP__textureTransformBinds_ITEM_Serialize_Scale(f:JsonFormatter, value:float[]) : void
    + {static} __expressions__custom_PROP__textureTransformBinds_ITEM_Serialize_Offset(f:JsonFormatter, value:float[]) : void
}
@enduml
