@startuml
class HumanoidInterface <<partial>> {
    + Jump(takeoffVelocity:float) : void
    + Rotation(yAngle:float) : void
    + TryAddToPossessions(gameObject:GameObject) : void
    + AddToPossessions(newPossession:Possessable) : void
    + ChangeAvatar(avatar:GameObject) : void
    + LeaveSite() : void
}
MonoBehaviour <|-- HumanoidInterface
IHumanoidMovement <|-- HumanoidInterface
HumanoidInterface o-> "attachedBone" Bone
@enduml
