@startuml
class DemoCMGazePointer {
    + PointerRingWidth : float
    + PointerCircleRadius : float
    + PointerDistance : float
    + PointerRenderQueue : int
    + PointerSortingOrder : int = 32767
    + ShowPointer : bool = true
    + RingPercent : int = 0
    + GetPointerPosition() : Vector3
    + OnHover(hovering:bool, intersecPosition:Vector3) : void
    + OnHover(hovering:bool) : void
}
MonoBehaviour <|-- DemoCMGazePointer
DemoCMGazePointer o-> "PointerColor" Color
DemoCMGazePointer o-> "ProgressColor" Color
DemoCMGazePointer o-> "PointerMaterial" Material
@enduml
