@startuml
class glTFAssets {
    + generator : string
    + version : string
    + copyright : string
    + minVersion : string
    + <<override>> ToString() : string
}
glTFAssets --> "extensions" glTFExtension
glTFAssets --> "extras" glTFExtension
@enduml
