@startuml
class glTFAttributes {
    + POSITION : int
    + NORMAL : int
    + TANGENT : int
    + TEXCOORD_0 : int
    + TEXCOORD_1 : int
    + COLOR_0 : int
    + JOINTS_0 : int
    + WEIGHTS_0 : int
    + <<override>> GetHashCode() : int
    + <<override>> Equals(obj:object) : bool
}
class gltfMorphTarget {
    + POSITION : int
    + NORMAL : int
    + TANGENT : int
}
class glTFPrimitives {
    + mode : int
    + indices : int
    + material : int
}
class glTFMesh {
    + name : string
    + glTFMesh()
    + glTFMesh(_name:string)
}
class "List`1"<T> {
}
glTFPrimitives --> "attributes" glTFAttributes
glTFPrimitives o-> "targets<gltfMorphTarget>" "List`1"
glTFPrimitives --> "extras" glTFExtension
glTFPrimitives --> "extensions" glTFExtension
glTFMesh o-> "primitives<glTFPrimitives>" "List`1"
glTFMesh --> "extras" glTFExtension
glTFMesh --> "extensions" glTFExtension
@enduml
