@startuml
class GltfDeserializer <<static>> {
    + {static} Deserialize(parsed:JsonNode) : glTF
    + {static} Deserialize_gltf_asset(parsed:JsonNode) : glTFAssets
    + {static} Deserialize_gltf_buffers(parsed:JsonNode) : List<UniGLTF.glTFBuffer>
    + {static} Deserialize_gltf_buffers_ITEM(parsed:JsonNode) : glTFBuffer
    + {static} Deserialize_gltf_bufferViews(parsed:JsonNode) : List<UniGLTF.glTFBufferView>
    + {static} Deserialize_gltf_bufferViews_ITEM(parsed:JsonNode) : glTFBufferView
    + {static} Deserialize_gltf_accessors(parsed:JsonNode) : List<UniGLTF.glTFAccessor>
    + {static} Deserialize_gltf_accessors_ITEM(parsed:JsonNode) : glTFAccessor
    + {static} Deserialize_gltf_accessors__max(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_accessors__min(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_accessors__sparse(parsed:JsonNode) : glTFSparse
    + {static} Deserialize_gltf_accessors__sparse_indices(parsed:JsonNode) : glTFSparseIndices
    + {static} Deserialize_gltf_accessors__sparse_values(parsed:JsonNode) : glTFSparseValues
    + {static} Deserialize_gltf_textures(parsed:JsonNode) : List<UniGLTF.glTFTexture>
    + {static} Deserialize_gltf_textures_ITEM(parsed:JsonNode) : glTFTexture
    + {static} Deserialize_gltf_samplers(parsed:JsonNode) : List<UniGLTF.glTFTextureSampler>
    + {static} Deserialize_gltf_samplers_ITEM(parsed:JsonNode) : glTFTextureSampler
    + {static} Deserialize_gltf_images(parsed:JsonNode) : List<UniGLTF.glTFImage>
    + {static} Deserialize_gltf_images_ITEM(parsed:JsonNode) : glTFImage
    + {static} Deserialize_gltf_materials(parsed:JsonNode) : List<UniGLTF.glTFMaterial>
    + {static} Deserialize_gltf_materials_ITEM(parsed:JsonNode) : glTFMaterial
    + {static} Deserialize_gltf_materials__pbrMetallicRoughness(parsed:JsonNode) : glTFPbrMetallicRoughness
    + {static} Deserialize_gltf_materials__pbrMetallicRoughness_baseColorTexture(parsed:JsonNode) : glTFMaterialBaseColorTextureInfo
    + {static} Deserialize_gltf_materials__pbrMetallicRoughness_baseColorFactor(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_materials__pbrMetallicRoughness_metallicRoughnessTexture(parsed:JsonNode) : glTFMaterialMetallicRoughnessTextureInfo
    + {static} Deserialize_gltf_materials__normalTexture(parsed:JsonNode) : glTFMaterialNormalTextureInfo
    + {static} Deserialize_gltf_materials__occlusionTexture(parsed:JsonNode) : glTFMaterialOcclusionTextureInfo
    + {static} Deserialize_gltf_materials__emissiveTexture(parsed:JsonNode) : glTFMaterialEmissiveTextureInfo
    + {static} Deserialize_gltf_materials__emissiveFactor(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_meshes(parsed:JsonNode) : List<UniGLTF.glTFMesh>
    + {static} Deserialize_gltf_meshes_ITEM(parsed:JsonNode) : glTFMesh
    + {static} Deserialize_gltf_meshes__primitives(parsed:JsonNode) : List<UniGLTF.glTFPrimitives>
    + {static} Deserialize_gltf_meshes__primitives_ITEM(parsed:JsonNode) : glTFPrimitives
    + {static} Deserialize_gltf_meshes__primitives__attributes(parsed:JsonNode) : glTFAttributes
    + {static} Deserialize_gltf_meshes__primitives__targets(parsed:JsonNode) : List<UniGLTF.gltfMorphTarget>
    + {static} Deserialize_gltf_meshes__primitives__targets_ITEM(parsed:JsonNode) : gltfMorphTarget
    + {static} Deserialize_gltf_meshes__weights(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_nodes(parsed:JsonNode) : List<UniGLTF.glTFNode>
    + {static} Deserialize_gltf_nodes_ITEM(parsed:JsonNode) : glTFNode
    + {static} Deserialize_gltf_nodes__children(parsed:JsonNode) : Int32[]
    + {static} Deserialize_gltf_nodes__matrix(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_nodes__translation(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_nodes__rotation(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_nodes__scale(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_nodes__weights(parsed:JsonNode) : Single[]
    + {static} Deserialize_gltf_skins(parsed:JsonNode) : List<UniGLTF.glTFSkin>
    + {static} Deserialize_gltf_skins_ITEM(parsed:JsonNode) : glTFSkin
    + {static} Deserialize_gltf_skins__joints(parsed:JsonNode) : Int32[]
    + {static} Deserialize_gltf_scenes(parsed:JsonNode) : List<UniGLTF.gltfScene>
    + {static} Deserialize_gltf_scenes_ITEM(parsed:JsonNode) : gltfScene
    + {static} Deserialize_gltf_scenes__nodes(parsed:JsonNode) : Int32[]
    + {static} Deserialize_gltf_animations(parsed:JsonNode) : List<UniGLTF.glTFAnimation>
    + {static} Deserialize_gltf_animations_ITEM(parsed:JsonNode) : glTFAnimation
    + {static} Deserialize_gltf_animations__channels(parsed:JsonNode) : List<UniGLTF.glTFAnimationChannel>
    + {static} Deserialize_gltf_animations__channels_ITEM(parsed:JsonNode) : glTFAnimationChannel
    + {static} Deserialize_gltf_animations__channels__target(parsed:JsonNode) : glTFAnimationTarget
    + {static} Deserialize_gltf_animations__samplers(parsed:JsonNode) : List<UniGLTF.glTFAnimationSampler>
    + {static} Deserialize_gltf_animations__samplers_ITEM(parsed:JsonNode) : glTFAnimationSampler
    + {static} Deserialize_gltf_cameras(parsed:JsonNode) : List<UniGLTF.glTFCamera>
    + {static} Deserialize_gltf_cameras_ITEM(parsed:JsonNode) : glTFCamera
    + {static} Deserialize_gltf_cameras__orthographic(parsed:JsonNode) : glTFOrthographic
    + {static} Deserialize_gltf_cameras__perspective(parsed:JsonNode) : glTFPerspective
    + {static} Deserialize_gltf_extensionsUsed(parsed:JsonNode) : List<System.String>
    + {static} Deserialize_gltf_extensionsRequired(parsed:JsonNode) : List<System.String>
}
@enduml
