@startuml
class GltfSerializer <<static>> {
    + {static} Serialize(f:JsonFormatter, value:glTF) : void
    + {static} Serialize_gltf_asset(f:JsonFormatter, value:glTFAssets) : void
    + {static} Serialize_gltf_buffers(f:JsonFormatter, value:List<glTFBuffer>) : void
    + {static} Serialize_gltf_buffers_ITEM(f:JsonFormatter, value:glTFBuffer) : void
    + {static} Serialize_gltf_bufferViews(f:JsonFormatter, value:List<glTFBufferView>) : void
    + {static} Serialize_gltf_bufferViews_ITEM(f:JsonFormatter, value:glTFBufferView) : void
    + {static} Serialize_gltf_accessors(f:JsonFormatter, value:List<glTFAccessor>) : void
    + {static} Serialize_gltf_accessors_ITEM(f:JsonFormatter, value:glTFAccessor) : void
    + {static} Serialize_gltf_accessors__max(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_accessors__min(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_accessors__sparse(f:JsonFormatter, value:glTFSparse) : void
    + {static} Serialize_gltf_accessors__sparse_indices(f:JsonFormatter, value:glTFSparseIndices) : void
    + {static} Serialize_gltf_accessors__sparse_values(f:JsonFormatter, value:glTFSparseValues) : void
    + {static} Serialize_gltf_textures(f:JsonFormatter, value:List<glTFTexture>) : void
    + {static} Serialize_gltf_textures_ITEM(f:JsonFormatter, value:glTFTexture) : void
    + {static} Serialize_gltf_samplers(f:JsonFormatter, value:List<glTFTextureSampler>) : void
    + {static} Serialize_gltf_samplers_ITEM(f:JsonFormatter, value:glTFTextureSampler) : void
    + {static} Serialize_gltf_images(f:JsonFormatter, value:List<glTFImage>) : void
    + {static} Serialize_gltf_images_ITEM(f:JsonFormatter, value:glTFImage) : void
    + {static} Serialize_gltf_materials(f:JsonFormatter, value:List<glTFMaterial>) : void
    + {static} Serialize_gltf_materials_ITEM(f:JsonFormatter, value:glTFMaterial) : void
    + {static} Serialize_gltf_materials__pbrMetallicRoughness(f:JsonFormatter, value:glTFPbrMetallicRoughness) : void
    + {static} Serialize_gltf_materials__pbrMetallicRoughness_baseColorTexture(f:JsonFormatter, value:glTFMaterialBaseColorTextureInfo) : void
    + {static} Serialize_gltf_materials__pbrMetallicRoughness_baseColorFactor(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_materials__pbrMetallicRoughness_metallicRoughnessTexture(f:JsonFormatter, value:glTFMaterialMetallicRoughnessTextureInfo) : void
    + {static} Serialize_gltf_materials__normalTexture(f:JsonFormatter, value:glTFMaterialNormalTextureInfo) : void
    + {static} Serialize_gltf_materials__occlusionTexture(f:JsonFormatter, value:glTFMaterialOcclusionTextureInfo) : void
    + {static} Serialize_gltf_materials__emissiveTexture(f:JsonFormatter, value:glTFMaterialEmissiveTextureInfo) : void
    + {static} Serialize_gltf_materials__emissiveFactor(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_meshes(f:JsonFormatter, value:List<glTFMesh>) : void
    + {static} Serialize_gltf_meshes_ITEM(f:JsonFormatter, value:glTFMesh) : void
    + {static} Serialize_gltf_meshes__primitives(f:JsonFormatter, value:List<glTFPrimitives>) : void
    + {static} Serialize_gltf_meshes__primitives_ITEM(f:JsonFormatter, value:glTFPrimitives) : void
    + {static} Serialize_gltf_meshes__primitives__attributes(f:JsonFormatter, value:glTFAttributes) : void
    + {static} Serialize_gltf_meshes__primitives__targets(f:JsonFormatter, value:List<gltfMorphTarget>) : void
    + {static} Serialize_gltf_meshes__primitives__targets_ITEM(f:JsonFormatter, value:gltfMorphTarget) : void
    + {static} Serialize_gltf_meshes__weights(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_nodes(f:JsonFormatter, value:List<glTFNode>) : void
    + {static} Serialize_gltf_nodes_ITEM(f:JsonFormatter, value:glTFNode) : void
    + {static} Serialize_gltf_nodes__children(f:JsonFormatter, value:Int32[]) : void
    + {static} Serialize_gltf_nodes__matrix(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_nodes__translation(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_nodes__rotation(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_nodes__scale(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_nodes__weights(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_gltf_skins(f:JsonFormatter, value:List<glTFSkin>) : void
    + {static} Serialize_gltf_skins_ITEM(f:JsonFormatter, value:glTFSkin) : void
    + {static} Serialize_gltf_skins__joints(f:JsonFormatter, value:Int32[]) : void
    + {static} Serialize_gltf_scenes(f:JsonFormatter, value:List<gltfScene>) : void
    + {static} Serialize_gltf_scenes_ITEM(f:JsonFormatter, value:gltfScene) : void
    + {static} Serialize_gltf_scenes__nodes(f:JsonFormatter, value:Int32[]) : void
    + {static} Serialize_gltf_animations(f:JsonFormatter, value:List<glTFAnimation>) : void
    + {static} Serialize_gltf_animations_ITEM(f:JsonFormatter, value:glTFAnimation) : void
    + {static} Serialize_gltf_animations__channels(f:JsonFormatter, value:List<glTFAnimationChannel>) : void
    + {static} Serialize_gltf_animations__channels_ITEM(f:JsonFormatter, value:glTFAnimationChannel) : void
    + {static} Serialize_gltf_animations__channels__target(f:JsonFormatter, value:glTFAnimationTarget) : void
    + {static} Serialize_gltf_animations__samplers(f:JsonFormatter, value:List<glTFAnimationSampler>) : void
    + {static} Serialize_gltf_animations__samplers_ITEM(f:JsonFormatter, value:glTFAnimationSampler) : void
    + {static} Serialize_gltf_cameras(f:JsonFormatter, value:List<glTFCamera>) : void
    + {static} Serialize_gltf_cameras_ITEM(f:JsonFormatter, value:glTFCamera) : void
    + {static} Serialize_gltf_cameras__orthographic(f:JsonFormatter, value:glTFOrthographic) : void
    + {static} Serialize_gltf_cameras__perspective(f:JsonFormatter, value:glTFPerspective) : void
    + {static} Serialize_gltf_extensionsUsed(f:JsonFormatter, value:List<String>) : void
    + {static} Serialize_gltf_extensionsRequired(f:JsonFormatter, value:List<String>) : void
}
@enduml
