@startuml
enum ProjectionType {
    Perspective,
    Orthographic,
}
class glTFOrthographic {
    + xmag : float
    + ymag : float
    + zfar : float
    + znear : float
}
class glTFPerspective {
    + aspectRatio : float
    + yfov : float
    + zfar : float
    + znear : float
}
class glTFCamera {
    + name : string
}
glTFOrthographic --> "extensions" glTFExtension
glTFOrthographic --> "extras" glTFExtension
glTFPerspective --> "extensions" glTFExtension
glTFPerspective --> "extras" glTFExtension
glTFCamera --> "orthographic" glTFOrthographic
glTFCamera --> "perspective" glTFPerspective
glTFCamera --> "type" ProjectionType
glTFCamera --> "extensions" glTFExtension
glTFCamera --> "extras" glTFExtension
@enduml
