@startuml
class gltfScene {
    + name : string
}
class glTF {
    + AddBufferView(view:glTFBufferView) : int
    + GetSampler(index:int) : glTFTextureSampler
    + GetSamplerFromTextureIndex(textureIndex:int) : glTFTextureSampler
    + GetUniqueMaterialName(index:int) : string
    + scene : int
    + <<override>> ToString() : string
    + Equals(other:glTF) : bool
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
gltfScene --> "extensions" glTFExtension
gltfScene --> "extras" glTFExtension
"IEquatable`1" "<glTF>" <|-- glTF
glTF o-> "asset" glTFAssets
glTF o-> "buffers<glTFBuffer>" "List`1"
glTF o-> "bufferViews<glTFBufferView>" "List`1"
glTF o-> "accessors<glTFAccessor>" "List`1"
glTF o-> "textures<glTFTexture>" "List`1"
glTF o-> "samplers<glTFTextureSampler>" "List`1"
glTF o-> "images<glTFImage>" "List`1"
glTF o-> "materials<glTFMaterial>" "List`1"
glTF o-> "meshes<glTFMesh>" "List`1"
glTF o-> "nodes<glTFNode>" "List`1"
glTF o-> "skins<glTFSkin>" "List`1"
glTF o-> "scenes<gltfScene>" "List`1"
glTF o-> "animations<glTFAnimation>" "List`1"
glTF o-> "cameras<glTFCamera>" "List`1"
glTF o-> "extensionsUsed<string>" "List`1"
glTF o-> "extensionsRequired<string>" "List`1"
glTF --> "extensions" glTFExtension
glTF --> "extras" glTFExtension
@enduml
