@startuml
enum EnumSerializationType {
    AsInt,
    AsString,
    AsLowerString,
    AsUpperString,
}
class BaseJsonSchemaAttribute {
    + Title : string
    + Description : string
    + Minimum : double
    + ExclusiveMinimum : bool
    + Maximum : double
    + ExclusiveMaximum : bool
    + MultipleOf : double
    + Pattern : string
    + MinItems : int
    + MaxItems : int
    + MinProperties : int
    + Required : bool
    + SkipSchemaComparison : bool
    + ExplicitIgnorableValue : object
    + ExplicitIgnorableItemLength : int
    + Merge(rhs:BaseJsonSchemaAttribute) : void
    + <<virtual>> GetInfo(fi:FieldInfo) : string
    + {static} IsNumber(t:Type) : bool
    + {static} GetTypeName(t:Type) : string
}
class JsonSchemaAttribute {
    + <<override>> GetInfo(fi:FieldInfo) : string
}
class ItemJsonSchemaAttribute {
    + <<override>> GetInfo(fi:FieldInfo) : string
}
Attribute <|-- BaseJsonSchemaAttribute
BaseJsonSchemaAttribute --> "EnumSerializationType" EnumSerializationType
BaseJsonSchemaAttribute <|-- JsonSchemaAttribute
BaseJsonSchemaAttribute <|-- ItemJsonSchemaAttribute
@enduml
