@startuml
struct Vector2 {
    + x : float
    + y : float
}
struct Vector3 {
    + x : float
    + y : float
    + z : float
    + Equals(other:Vector3) : bool
}
struct Vector4 {
    + x : float
    + y : float
    + z : float
    + w : float
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<Vector3>" <|-- Vector3
Vector3 --> "zero" Vector3
@enduml
