@startuml
class ControllerButtons {
    + stickHorizontal : float
    + stickVertical : float
    + stickPress : bool
    + stickTouch : bool
    + up : bool
    + down : bool
    + left : bool
    + right : bool
    + trigger1 : float
    + trigger2 : float
    + option : bool
}
class ArmController {
    + ArmController(isLeft:bool, deviceView:DeviceView)
    + <<virtual>> UpdateInput() : void
    + <<virtual>> Vibrate(length:float, strength:float) : void
}
ArmSensor <|-- ArmController
ArmController --> "input" ControllerButtons
@enduml
