@startuml
enum FaceBone {
    LeftOuterBrow,
    LeftBrow,
    LeftInnerBrow,
    RightInnerBrow,
    RightBrow,
    RightOuterBrow,
    LeftCheek,
    RightCheek,
    NoseTopLeft,
    NoseTop,
    NoseTopRight,
    NoseTip,
    NoseBottomLeft,
    NoseBottom,
    NoseBottomRight,
    UpperLipLeft,
    UpperLip,
    UpperLipRight,
    LipLeft,
    LipRight,
    LowerLipLeft,
    LowerLip,
    LowerLipRight,
    LastBone,
}
class FaceSensor {
    + smile : float
    + pucker : float
    + frown : float
    + FaceSensor(deviceView:DeviceView)
}
class TrackedBrow {
}
class TrackedEye {
    + closed : float
}
class TrackedNose {
}
class TrackedMouth {
}
class FaceTargetData {
}
Sensor <|-- FaceSensor
FaceSensor o-> "leftBrow" TrackedBrow
FaceSensor o-> "rightBrow" TrackedBrow
FaceSensor o-> "leftEye" TrackedEye
FaceSensor o-> "rightEye" TrackedEye
FaceSensor o-> "leftCheek" TargetData
FaceSensor o-> "rightCheek" TargetData
FaceSensor o-> "nose" TrackedNose
FaceSensor o-> "mouth" TrackedMouth
FaceSensor o-> "jaw" TargetData
FaceSensor +-- TrackedBrow
TrackedBrow --> "inner" TargetData
TrackedBrow --> "center" TargetData
TrackedBrow --> "outer" TargetData
FaceSensor +-- TrackedEye
FaceSensor +-- TrackedNose
TrackedNose --> "top" TargetData
TrackedNose --> "topLeft" TargetData
TrackedNose --> "topRight" TargetData
TrackedNose --> "tip" TargetData
TrackedNose --> "bottom" TargetData
TrackedNose --> "bottomLeft" TargetData
TrackedNose --> "bottomRight" TargetData
FaceSensor +-- TrackedMouth
TrackedMouth --> "upperLipLeft" TargetData
TrackedMouth --> "upperLip" TargetData
TrackedMouth --> "upperLipRight" TargetData
TrackedMouth --> "lipLeft" TargetData
TrackedMouth --> "lipRight" TargetData
TrackedMouth --> "lowerLipLeft" TargetData
TrackedMouth --> "lowerLip" TargetData
TrackedMouth --> "lowerLipRight" TargetData
FaceSensor +-- FaceTargetData
TargetData <|-- FaceTargetData
FaceTargetData --> "startPosition" Vector
@enduml
