@startuml
class LegSensor {
    + isLeft : bool
    + LegSensor(isLeft:bool, deviceView:DeviceView)
    + {static} CalculateLegOrientation(joint1Position:Vector, joint2Position:Vector, hipsRotation:Rotation) : Rotation
}
Sensor <|-- LegSensor
LegSensor --> "upperLeg" TargetData
LegSensor --> "lowerLeg" TargetData
LegSensor --> "foot" TargetData
@enduml
