@startuml
class BvhNode {
    + BvhNode(name:string)
    + GetChannelIndex(channel:BvhChannel) : int
    + <<virtual>> Parse(r:StringReader) : void
    + Traverse() : IEnumerable<BvhNode>
}
class "List`1"<T> {
}
BvhNode --> "Name" String
BvhNode --> "Offset" Vector3
BvhNode --> "Children<BvhNode>" "List`1"
@enduml
