@startuml
class VRM10Object {
}
PrefabRelatedScriptableObject <|-- VRM10Object
VRM10Object --> "SubAssetKey" SubAssetKey
VRM10Object o-> "Meta" VRM10ObjectMeta
VRM10Object o-> "Expression" VRM10ObjectExpression
VRM10Object o-> "LookAt" VRM10ObjectLookAt
VRM10Object o-> "FirstPerson" VRM10ObjectFirstPerson
@enduml
