@startuml
class VRM10ObjectMeta {
    + Name : string
    + Version : string
    + CopyrightInformation : string
    + ContactInformation : string
    + ThirdPartyLicenses : string
    + ViolentUsage : bool
    + SexualUsage : bool
    + PoliticalOrReligiousUsage : bool
    + AntisocialOrHateUsage : bool
    + Redistribution : bool
    + OtherLicenseUrl : string
    + Validate(_:GameObject) : IEnumerable<Validation>
    + CopyTo(dst:VRM10ObjectMeta) : void
}
class "List`1"<T> {
}
VRM10ObjectMeta o-> "Authors<string>" "List`1"
VRM10ObjectMeta o-> "References<string>" "List`1"
VRM10ObjectMeta --> "Thumbnail" Texture2D
@enduml
