@startuml
class OnLoadHumanoidPlayer {
    + {static} GetHumanoidPlayerPrefabPath() : string
    + {static} GetHumanoidPlayerPrefab(prefabPath:string) : GameObject
    + {static} UpdateHumanoidPrefab(prefab:GameObject, prefabPath:string) : void
}
class HumanoidPlayer_Editor {
    + {static} DelayedSave() : void
}
class "Stack`1"<T> {
}
OnLoadHumanoidPlayer +-- HumanoidPlayer_Editor
HumanoidNetworking_Editor <|-- HumanoidPlayer_Editor
HumanoidPlayer_Editor o-> "prefabsToSave<GameObject>" "Stack`1"
HumanoidPlayer_Editor o-> "prefabPaths<string>" "Stack`1"
@enduml
