@startuml
class glTF_VRM_Material {
    + name : string
    + shader : string
    + renderQueue : int
    + {static} <<readonly>> VRM_USE_GLTFSHADER : string = "VRM_USE_GLTFSHADER"
}
class "Dictionary`2"<T1,T2> {
}
glTF_VRM_Material o-> "floatProperties<string,float>" "Dictionary`2"
glTF_VRM_Material o-> "vectorProperties<string,float[]>" "Dictionary`2"
glTF_VRM_Material o-> "textureProperties<string,int>" "Dictionary`2"
glTF_VRM_Material o-> "keywordMap<string,bool>" "Dictionary`2"
glTF_VRM_Material o-> "tagMap<string,string>" "Dictionary`2"
@enduml
