@startuml
class glTF_VRM_SecondaryAnimationCollider {
    + radius : float
}
class glTF_VRM_SecondaryAnimationColliderGroup {
    + node : int
}
class glTF_VRM_SecondaryAnimationGroup {
    + comment : string
    + stiffiness : float
    + gravityPower : float
    + dragForce : float
    + center : int
    + hitRadius : float
}
class glTF_VRM_SecondaryAnimation {
}
class "List`1"<T> {
}
glTF_VRM_SecondaryAnimationCollider --> "offset" Vector3
glTF_VRM_SecondaryAnimationColliderGroup o-> "colliders<glTF_VRM_SecondaryAnimationCollider>" "List`1"
glTF_VRM_SecondaryAnimationGroup --> "gravityDir" Vector3
glTF_VRM_SecondaryAnimation o-> "boneGroups<glTF_VRM_SecondaryAnimationGroup>" "List`1"
glTF_VRM_SecondaryAnimation o-> "colliderGroups<glTF_VRM_SecondaryAnimationColliderGroup>" "List`1"
@enduml
