@startuml
enum VRMBone {
    hips,
    leftUpperLeg,
    rightUpperLeg,
    leftLowerLeg,
    rightLowerLeg,
    leftFoot,
    rightFoot,
    spine,
    chest,
    neck,
    head,
    leftShoulder,
    rightShoulder,
    leftUpperArm,
    rightUpperArm,
    leftLowerArm,
    rightLowerArm,
    leftHand,
    rightHand,
    leftToes,
    rightToes,
    leftEye,
    rightEye,
    jaw,
    leftThumbProximal,
    leftThumbIntermediate,
    leftThumbDistal,
    leftIndexProximal,
    leftIndexIntermediate,
    leftIndexDistal,
    leftMiddleProximal,
    leftMiddleIntermediate,
    leftMiddleDistal,
    leftRingProximal,
    leftRingIntermediate,
    leftRingDistal,
    leftLittleProximal,
    leftLittleIntermediate,
    leftLittleDistal,
    rightThumbProximal,
    rightThumbIntermediate,
    rightThumbDistal,
    rightIndexProximal,
    rightIndexIntermediate,
    rightIndexDistal,
    rightMiddleProximal,
    rightMiddleIntermediate,
    rightMiddleDistal,
    rightRingProximal,
    rightRingIntermediate,
    rightRingDistal,
    rightLittleProximal,
    rightLittleIntermediate,
    rightLittleDistal,
    upperChest,
    unknown,
}
class glTF_VRM_HumanoidBone {
    + bone : string
    + node : int
    + useDefaultValues : bool = true
    + axisLength : float
}
class glTF_VRM_Humanoid {
    + armStretch : float = 0.05f
    + legStretch : float = 0.05f
    + upperArmTwist : float = 0.5f
    + lowerArmTwist : float = 0.5f
    + upperLegTwist : float = 0.5f
    + lowerLegTwist : float = 0.5f
    + feetSpacing : float = 0
    + hasTranslationDoF : bool = false
}
class "List`1"<T> {
}
glTF_VRM_HumanoidBone --> "vrmBone" VRMBone
glTF_VRM_HumanoidBone --> "min" Vector3
glTF_VRM_HumanoidBone --> "max" Vector3
glTF_VRM_HumanoidBone --> "center" Vector3
glTF_VRM_Humanoid o-> "humanBones<glTF_VRM_HumanoidBone>" "List`1"
@enduml
