@startuml
class glTF_VRM_MaterialValueBind {
    + materialName : string
    + propertyName : string
}
class glTF_VRM_BlendShapeBind {
    + mesh : int
    + index : int
    + weight : float = 0
}
enum BlendShapePreset {
    Unknown,
    Neutral,
    A,
    I,
    U,
    E,
    O,
    Blink,
    Joy,
    Angry,
    Sorrow,
    Fun,
    LookUp,
    LookDown,
    LookLeft,
    LookRight,
    Blink_L,
    Blink_R,
}
class glTF_VRM_BlendShapeGroup {
    + name : string
    + presetName : string
    + isBinary : bool
}
class glTF_VRM_BlendShapeMaster {
}
class "List`1"<T> {
}
glTF_VRM_BlendShapeGroup o-> "binds<glTF_VRM_BlendShapeBind>" "List`1"
glTF_VRM_BlendShapeGroup o-> "materialValues<glTF_VRM_MaterialValueBind>" "List`1"
glTF_VRM_BlendShapeMaster o-> "blendShapeGroups<glTF_VRM_BlendShapeGroup>" "List`1"
@enduml
