@startuml
class glTF_VRM_DegreeMap {
    + xRange : float = 90.0f
    + yRange : float = 10.0f
}
enum FirstPersonFlag {
    Auto,
    Both,
    ThirdPersonOnly,
    FirstPersonOnly,
}
class glTF_VRM_MeshAnnotation {
    + mesh : int
    + firstPersonFlag : string
}
enum LookAtType {
    None,
    Bone,
    BlendShape,
}
class glTF_VRM_Firstperson {
    + firstPersonBone : int
    + lookAtTypeName : string = "Bone"
}
class "List`1"<T> {
}
glTF_VRM_Firstperson --> "firstPersonBoneOffset" Vector3
glTF_VRM_Firstperson o-> "meshAnnotations<glTF_VRM_MeshAnnotation>" "List`1"
glTF_VRM_Firstperson --> "lookAtType" LookAtType
glTF_VRM_Firstperson o-> "lookAtHorizontalInner" glTF_VRM_DegreeMap
glTF_VRM_Firstperson o-> "lookAtHorizontalOuter" glTF_VRM_DegreeMap
glTF_VRM_Firstperson o-> "lookAtVerticalDown" glTF_VRM_DegreeMap
glTF_VRM_Firstperson o-> "lookAtVerticalUp" glTF_VRM_DegreeMap
@enduml
