@startuml
class VrmDeserializer <<static>> {
    + {static} Deserialize(parsed:JsonNode) : glTF_VRM_extensions
    + {static} Deserialize_vrm_meta(parsed:JsonNode) : glTF_VRM_Meta
    + {static} Deserialize_vrm_humanoid(parsed:JsonNode) : glTF_VRM_Humanoid
    + {static} Deserialize_vrm_humanoid_humanBones(parsed:JsonNode) : List<VRM.glTF_VRM_HumanoidBone>
    + {static} Deserialize_vrm_humanoid_humanBones_LIST(parsed:JsonNode) : glTF_VRM_HumanoidBone
    + {static} Deserialize_vrm_humanoid_humanBones__min(parsed:JsonNode) : Vector3
    + {static} Deserialize_vrm_humanoid_humanBones__max(parsed:JsonNode) : Vector3
    + {static} Deserialize_vrm_humanoid_humanBones__center(parsed:JsonNode) : Vector3
    + {static} Deserialize_vrm_firstPerson(parsed:JsonNode) : glTF_VRM_Firstperson
    + {static} Deserialize_vrm_firstPerson_firstPersonBoneOffset(parsed:JsonNode) : Vector3
    + {static} Deserialize_vrm_firstPerson_meshAnnotations(parsed:JsonNode) : List<VRM.glTF_VRM_MeshAnnotation>
    + {static} Deserialize_vrm_firstPerson_meshAnnotations_LIST(parsed:JsonNode) : glTF_VRM_MeshAnnotation
    + {static} Deserialize_vrm_firstPerson_lookAtHorizontalInner(parsed:JsonNode) : glTF_VRM_DegreeMap
    + {static} Deserialize_vrm_firstPerson_lookAtHorizontalInner_curve(parsed:JsonNode) : Single[]
    + {static} Deserialize_vrm_firstPerson_lookAtHorizontalOuter(parsed:JsonNode) : glTF_VRM_DegreeMap
    + {static} Deserialize_vrm_firstPerson_lookAtHorizontalOuter_curve(parsed:JsonNode) : Single[]
    + {static} Deserialize_vrm_firstPerson_lookAtVerticalDown(parsed:JsonNode) : glTF_VRM_DegreeMap
    + {static} Deserialize_vrm_firstPerson_lookAtVerticalDown_curve(parsed:JsonNode) : Single[]
    + {static} Deserialize_vrm_firstPerson_lookAtVerticalUp(parsed:JsonNode) : glTF_VRM_DegreeMap
    + {static} Deserialize_vrm_firstPerson_lookAtVerticalUp_curve(parsed:JsonNode) : Single[]
    + {static} Deserialize_vrm_blendShapeMaster(parsed:JsonNode) : glTF_VRM_BlendShapeMaster
    + {static} Deserialize_vrm_blendShapeMaster_blendShapeGroups(parsed:JsonNode) : List<VRM.glTF_VRM_BlendShapeGroup>
    + {static} Deserialize_vrm_blendShapeMaster_blendShapeGroups_LIST(parsed:JsonNode) : glTF_VRM_BlendShapeGroup
    + {static} Deserialize_vrm_blendShapeMaster_blendShapeGroups__binds(parsed:JsonNode) : List<VRM.glTF_VRM_BlendShapeBind>
    + {static} Deserialize_vrm_blendShapeMaster_blendShapeGroups__binds_LIST(parsed:JsonNode) : glTF_VRM_BlendShapeBind
    + {static} Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues(parsed:JsonNode) : List<VRM.glTF_VRM_MaterialValueBind>
    + {static} Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_LIST(parsed:JsonNode) : glTF_VRM_MaterialValueBind
    + {static} Deserialize_vrm_blendShapeMaster_blendShapeGroups__materialValues__targetValue(parsed:JsonNode) : Single[]
    + {static} Deserialize_vrm_secondaryAnimation(parsed:JsonNode) : glTF_VRM_SecondaryAnimation
    + {static} Deserialize_vrm_secondaryAnimation_boneGroups(parsed:JsonNode) : List<VRM.glTF_VRM_SecondaryAnimationGroup>
    + {static} Deserialize_vrm_secondaryAnimation_boneGroups_LIST(parsed:JsonNode) : glTF_VRM_SecondaryAnimationGroup
    + {static} Deserialize_vrm_secondaryAnimation_boneGroups__gravityDir(parsed:JsonNode) : Vector3
    + {static} Deserialize_vrm_secondaryAnimation_boneGroups__bones(parsed:JsonNode) : Int32[]
    + {static} Deserialize_vrm_secondaryAnimation_boneGroups__colliderGroups(parsed:JsonNode) : Int32[]
    + {static} Deserialize_vrm_secondaryAnimation_colliderGroups(parsed:JsonNode) : List<VRM.glTF_VRM_SecondaryAnimationColliderGroup>
    + {static} Deserialize_vrm_secondaryAnimation_colliderGroups_LIST(parsed:JsonNode) : glTF_VRM_SecondaryAnimationColliderGroup
    + {static} Deserialize_vrm_secondaryAnimation_colliderGroups__colliders(parsed:JsonNode) : List<VRM.glTF_VRM_SecondaryAnimationCollider>
    + {static} Deserialize_vrm_secondaryAnimation_colliderGroups__colliders_LIST(parsed:JsonNode) : glTF_VRM_SecondaryAnimationCollider
    + {static} Deserialize_vrm_secondaryAnimation_colliderGroups__colliders__offset(parsed:JsonNode) : Vector3
    + {static} Deserialize_vrm_materialProperties(parsed:JsonNode) : List<VRM.glTF_VRM_Material>
    + {static} Deserialize_vrm_materialProperties_LIST(parsed:JsonNode) : glTF_VRM_Material
    + {static} Deserialize_vrm_materialProperties__floatProperties(parsed:JsonNode) : Dictionary<String, Single>
    + {static} Deserialize_vrm_materialProperties__vectorProperties(parsed:JsonNode) : Dictionary<String, Single[]>
    + {static} Deserialize_vrm_materialProperties__vectorProperties_DICT(parsed:JsonNode) : Single[]
    + {static} Deserialize_vrm_materialProperties__textureProperties(parsed:JsonNode) : Dictionary<String, Int32>
    + {static} Deserialize_vrm_materialProperties__keywordMap(parsed:JsonNode) : Dictionary<String, Boolean>
    + {static} Deserialize_vrm_materialProperties__tagMap(parsed:JsonNode) : Dictionary<String, String>
}
@enduml
