@startuml
class VRMSerializer <<static>> {
    + {static} Serialize(f:JsonFormatter, value:glTF_VRM_extensions) : void
    + {static} Serialize_vrm_meta(f:JsonFormatter, value:glTF_VRM_Meta) : void
    + {static} Serialize_vrm_humanoid(f:JsonFormatter, value:glTF_VRM_Humanoid) : void
    + {static} Serialize_vrm_humanoid_humanBones(f:JsonFormatter, value:List<glTF_VRM_HumanoidBone>) : void
    + {static} Serialize_vrm_humanoid_humanBones_ITEM(f:JsonFormatter, value:glTF_VRM_HumanoidBone) : void
    + {static} Serialize_vrm_humanoid_humanBones__min(f:JsonFormatter, value:Vector3) : void
    + {static} Serialize_vrm_humanoid_humanBones__max(f:JsonFormatter, value:Vector3) : void
    + {static} Serialize_vrm_humanoid_humanBones__center(f:JsonFormatter, value:Vector3) : void
    + {static} Serialize_vrm_firstPerson(f:JsonFormatter, value:glTF_VRM_Firstperson) : void
    + {static} Serialize_vrm_firstPerson_firstPersonBoneOffset(f:JsonFormatter, value:Vector3) : void
    + {static} Serialize_vrm_firstPerson_meshAnnotations(f:JsonFormatter, value:List<glTF_VRM_MeshAnnotation>) : void
    + {static} Serialize_vrm_firstPerson_meshAnnotations_ITEM(f:JsonFormatter, value:glTF_VRM_MeshAnnotation) : void
    + {static} Serialize_vrm_firstPerson_lookAtHorizontalInner(f:JsonFormatter, value:glTF_VRM_DegreeMap) : void
    + {static} Serialize_vrm_firstPerson_lookAtHorizontalInner_curve(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_vrm_firstPerson_lookAtHorizontalOuter(f:JsonFormatter, value:glTF_VRM_DegreeMap) : void
    + {static} Serialize_vrm_firstPerson_lookAtHorizontalOuter_curve(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_vrm_firstPerson_lookAtVerticalDown(f:JsonFormatter, value:glTF_VRM_DegreeMap) : void
    + {static} Serialize_vrm_firstPerson_lookAtVerticalDown_curve(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_vrm_firstPerson_lookAtVerticalUp(f:JsonFormatter, value:glTF_VRM_DegreeMap) : void
    + {static} Serialize_vrm_firstPerson_lookAtVerticalUp_curve(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_vrm_blendShapeMaster(f:JsonFormatter, value:glTF_VRM_BlendShapeMaster) : void
    + {static} Serialize_vrm_blendShapeMaster_blendShapeGroups(f:JsonFormatter, value:List<glTF_VRM_BlendShapeGroup>) : void
    + {static} Serialize_vrm_blendShapeMaster_blendShapeGroups_ITEM(f:JsonFormatter, value:glTF_VRM_BlendShapeGroup) : void
    + {static} Serialize_vrm_blendShapeMaster_blendShapeGroups__binds(f:JsonFormatter, value:List<glTF_VRM_BlendShapeBind>) : void
    + {static} Serialize_vrm_blendShapeMaster_blendShapeGroups__binds_ITEM(f:JsonFormatter, value:glTF_VRM_BlendShapeBind) : void
    + {static} Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues(f:JsonFormatter, value:List<glTF_VRM_MaterialValueBind>) : void
    + {static} Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues_ITEM(f:JsonFormatter, value:glTF_VRM_MaterialValueBind) : void
    + {static} Serialize_vrm_blendShapeMaster_blendShapeGroups__materialValues__targetValue(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_vrm_secondaryAnimation(f:JsonFormatter, value:glTF_VRM_SecondaryAnimation) : void
    + {static} Serialize_vrm_secondaryAnimation_boneGroups(f:JsonFormatter, value:List<glTF_VRM_SecondaryAnimationGroup>) : void
    + {static} Serialize_vrm_secondaryAnimation_boneGroups_ITEM(f:JsonFormatter, value:glTF_VRM_SecondaryAnimationGroup) : void
    + {static} Serialize_vrm_secondaryAnimation_boneGroups__gravityDir(f:JsonFormatter, value:Vector3) : void
    + {static} Serialize_vrm_secondaryAnimation_boneGroups__bones(f:JsonFormatter, value:Int32[]) : void
    + {static} Serialize_vrm_secondaryAnimation_boneGroups__colliderGroups(f:JsonFormatter, value:Int32[]) : void
    + {static} Serialize_vrm_secondaryAnimation_colliderGroups(f:JsonFormatter, value:List<glTF_VRM_SecondaryAnimationColliderGroup>) : void
    + {static} Serialize_vrm_secondaryAnimation_colliderGroups_ITEM(f:JsonFormatter, value:glTF_VRM_SecondaryAnimationColliderGroup) : void
    + {static} Serialize_vrm_secondaryAnimation_colliderGroups__colliders(f:JsonFormatter, value:List<glTF_VRM_SecondaryAnimationCollider>) : void
    + {static} Serialize_vrm_secondaryAnimation_colliderGroups__colliders_ITEM(f:JsonFormatter, value:glTF_VRM_SecondaryAnimationCollider) : void
    + {static} Serialize_vrm_secondaryAnimation_colliderGroups__colliders__offset(f:JsonFormatter, value:Vector3) : void
    + {static} Serialize_vrm_materialProperties(f:JsonFormatter, value:List<glTF_VRM_Material>) : void
    + {static} Serialize_vrm_materialProperties_ITEM(f:JsonFormatter, value:glTF_VRM_Material) : void
    + {static} Serialize_vrm_materialProperties__floatProperties(f:JsonFormatter, value:Dictionary<string, Single>) : void
    + {static} Serialize_vrm_materialProperties__vectorProperties(f:JsonFormatter, value:Dictionary<string, Single[]>) : void
    + {static} Serialize_vrm_materialProperties__vectorProperties_ITEM(f:JsonFormatter, value:Single[]) : void
    + {static} Serialize_vrm_materialProperties__textureProperties(f:JsonFormatter, value:Dictionary<string, Int32>) : void
    + {static} Serialize_vrm_materialProperties__keywordMap(f:JsonFormatter, value:Dictionary<string, Boolean>) : void
    + {static} Serialize_vrm_materialProperties__tagMap(f:JsonFormatter, value:Dictionary<string, String>) : void
}
@enduml
