@startuml
class TextureInfo {
    + Extensions : object
    + Extras : object
    + Index : int?
    + TexCoord : int?
}
class ShadingShiftTextureInfo {
    + Extensions : object
    + Extras : object
    + Index : int?
    + TexCoord : int?
    + Scale : float?
}
enum OutlineWidthMode {
    none,
    worldCoordinates,
    screenCoordinates,
}
class VRMC_materials_mtoon {
    + <<const>> ExtensionName : string = "VRMC_materials_mtoon"
    + Extensions : object
    + Extras : object
    + SpecVersion : string
    + TransparentWithZWrite : bool?
    + RenderQueueOffsetNumber : int?
    + ShadingShiftFactor : float?
    + ShadingToonyFactor : float?
    + GiEqualizationFactor : float?
    + RimLightingMixFactor : float?
    + ParametricRimFresnelPowerFactor : float?
    + ParametricRimLiftFactor : float?
    + OutlineWidthFactor : float?
    + OutlineLightingMixFactor : float?
    + UvAnimationScrollXSpeedFactor : float?
    + UvAnimationScrollYSpeedFactor : float?
    + UvAnimationRotationSpeedFactor : float?
}
VRMC_materials_mtoon --> "ShadeMultiplyTexture" TextureInfo
VRMC_materials_mtoon --> "ShadingShiftTexture" ShadingShiftTextureInfo
VRMC_materials_mtoon --> "MatcapTexture" TextureInfo
VRMC_materials_mtoon --> "RimMultiplyTexture" TextureInfo
VRMC_materials_mtoon --> "OutlineWidthMode" OutlineWidthMode
VRMC_materials_mtoon --> "OutlineWidthMultiplyTexture" TextureInfo
VRMC_materials_mtoon --> "UvAnimationMaskTexture" TextureInfo
@enduml
