@startuml
struct Vrm10HumanoidBoneAttribute {
    + IsRequired : bool <<get>>
    + NeedsParentBone : bool? <<get>>
    + Vrm10HumanoidBoneAttribute(bone:Vrm10HumanoidBones, isRequired:bool, parentBone:Vrm10HumanoidBones?, needsParentBone:bool?, unityBone:HumanBodyBones)
}
Vrm10HumanoidBoneAttribute --> "Bone" Vrm10HumanoidBones
Vrm10HumanoidBoneAttribute --> "ParentBone" Vrm10HumanoidBones
Vrm10HumanoidBoneAttribute --> "UnityBone" HumanBodyBones
@enduml
