@startuml
class DataSerializationClasses {
}
class UserData {
    + TrainedLimb : string <<get>> <<set>>
    + ReferenceLimb : string <<get>> <<set>>
    + SetUserData(simulationStartTime:DateTime, simulationEndTime:DateTime, trainedLimb:string, referenceLimb:string, initialLimbData:InitialLimbData, trainedLimbData:List<TrainedLimbData>, referenceLimbData:List<ReferenceLimbData>) : void
}
class InitialLimbData {
    + SetInitialLimbData(chestData:ChestData, upperLimbVertical:LimbData, upperLimbHorizontal:LimbData, shoulderRotation:LimbData, elbowExtension:LimbData, lowerLimbSupination:LimbData) : void
}
class LimbData {
    + SetLimbData(rightLimbData:AngleData, leftLimbData:AngleData) : void
}
class TrainedLimbData {
    + SetTrainedLimbData(chestData:ChestData, upperLimbVertical:AngleData, upperLimbHorizontal:AngleData, shoulderRotation:AngleData, elbowRotation:AngleData, lowerLimbRotation:AngleData, spawningPointData:SpawningPointData) : void
}
class ReferenceLimbData {
    + SetReferenceLimbData(chestData:ChestData, upperLimbVertical:AngleData, upperLimbHorizontal:AngleData, shoulderRotation:AngleData, elbowExtension:AngleData, lowerLimbSupination:AngleData, spawningPointData:SpawningPointData) : void
}
class ChestData {
    + SetChestData(chestTrackerData:TrackerData, chestRotationEulerAngles:SerializableVector3) : void
}
class AngleData {
    + TrackerName0 : string <<get>> <<set>>
    + TrackerName1 : string <<get>> <<set>>
    + JointAngle : float <<get>> <<set>>
    + SetAngleData(trackerAngleComputingData0:Tuple<string, TrackerData, SerializableVector3>, trackerAngleComputingData1:Tuple<string, TrackerData, SerializableVector3>, jointAngle:float, chestRotation:TrackerData) : void
}
class TrackerData {
    + SetTrackerData(trackerPosition:SerializableVector3, trackerRotation:SerializableQuaternion) : void
}
class SpawningPointData {
    + Name : string <<get>> <<set>>
    + SetSpawningPointData(name:string, position:SerializableVector3, timestampAtCollection:DateTime, sizeOfSpawningPointAura:SerializableVector3) : void
}
class "List`1"<T> {
}
MonoBehaviour <|-- DataSerializationClasses
UserData --> "SimulationStartTime" DateTime
UserData --> "SimulationEndTime" DateTime
UserData --> "InitialLimbData" InitialLimbData
UserData --> "TrainedLimbData<TrainedLimbData>" "List`1"
UserData --> "ReferenceLimbData<ReferenceLimbData>" "List`1"
InitialLimbData --> "ChestData" ChestData
InitialLimbData --> "UpperLimbHorizontal" LimbData
InitialLimbData --> "UpperLimbVertical" LimbData
InitialLimbData --> "ShoulderRotation" LimbData
InitialLimbData --> "ElbowExtension" LimbData
InitialLimbData --> "LowerLimbSupination" LimbData
LimbData --> "RightLimbData" AngleData
LimbData --> "LeftLimbData" AngleData
TrainedLimbData --> "ChestData" ChestData
TrainedLimbData --> "UpperLimbHorizontal" AngleData
TrainedLimbData --> "UpperLimbVertical" AngleData
TrainedLimbData --> "ShoulderRotation" AngleData
TrainedLimbData --> "ElbowRotation" AngleData
TrainedLimbData --> "LowerLimbRotation" AngleData
TrainedLimbData --> "SpawningPointData" SpawningPointData
ReferenceLimbData --> "ChestData" ChestData
ReferenceLimbData --> "UpperLimbHorizontal" AngleData
ReferenceLimbData --> "UpperLimbVertical" AngleData
ReferenceLimbData --> "ShoulderRotation" AngleData
ReferenceLimbData --> "ElbowExtension" AngleData
ReferenceLimbData --> "LowerLimbSupination" AngleData
ReferenceLimbData --> "SpawningPointData" SpawningPointData
ChestData --> "TrackerChestData" TrackerData
ChestData --> "ChestRotationEulerAngles" SerializableVector3
AngleData --> "TrackerPosition0" SerializableVector3
AngleData --> "TrackerRotation0" SerializableQuaternion
AngleData --> "ComputingVectorDirection0" SerializableVector3
AngleData --> "TrackerPosition1" SerializableVector3
AngleData --> "TrackerRotation1" SerializableQuaternion
AngleData --> "ComputingVectorDirection1" SerializableVector3
AngleData --> "ChestRotation" SerializableQuaternion
TrackerData --> "TrackerPosition" SerializableVector3
TrackerData --> "TrackerRotation" SerializableQuaternion
SpawningPointData --> "Position" SerializableVector3
SpawningPointData --> "TimestampAtCollection" DateTime
SpawningPointData --> "SizeOfSpawningPointAura" SerializableVector3
@enduml
