@startuml
class BonePose {
    + setTranslation : bool
    + setRotation : bool
    + setScale : bool
    + Reset(humanoid:HumanoidControl) : void
    + ShowPose(humanoid:HumanoidControl, value:float) : void
    + ShowPose(humanoid:HumanoidControl, showSide:Side, value:float) : void
    + ShowPoseAdditive(humanoid:HumanoidControl, showSide:Side, value:float) : void
    + UpdateTranslation(humanoid:HumanoidControl, side:Side) : void
    + UpdateRotation(humanoid:HumanoidControl, side:Side) : void
    + SetReferenceRoot() : void
    + SetReferenceLocal(humanoid:HumanoidControl, side:Side) : void
    + SetReference(referenceBoneId:Bone) : void
    + GetScore(humanoid:HumanoidControl, side:Side) : float
}
BonePose o-> "boneType" BoneType
BonePose o-> "boneRef" BoneReference
BonePose o-> "referenceBoneRef" BoneReference
BonePose --> "translation" Vector3
BonePose --> "rotation" Quaternion
BonePose --> "scale" Vector3
@enduml
