@startuml
class BarTextDisplayer {
    + OnPointerEnter(eventData:PointerEventData) : void
    + OnPointerExit(eventData:PointerEventData) : void
    + OnPointerDown(eventData:PointerEventData) : void
    + OnBeginDrag(eventData:PointerEventData) : void
    + OnDrag(eventData:PointerEventData) : void
    + OnEndDrag(eventData:PointerEventData) : void
    + OnDrop(eventData:PointerEventData) : void
    + OnPointerUp(eventData:PointerEventData) : void
    + OnPointerClick(eventData:PointerEventData) : void
}
MonoBehaviour <|-- BarTextDisplayer
IPointerEnterHandler <|-- BarTextDisplayer
IPointerExitHandler <|-- BarTextDisplayer
IPointerDownHandler <|-- BarTextDisplayer
IBeginDragHandler <|-- BarTextDisplayer
IDragHandler <|-- BarTextDisplayer
IEndDragHandler <|-- BarTextDisplayer
IDropHandler <|-- BarTextDisplayer
IPointerClickHandler <|-- BarTextDisplayer
IPointerUpHandler <|-- BarTextDisplayer
@enduml
