@startuml
enum HandColliderType {
    None,
    Trigger,
    Collider,
}
class HandRenderer {
    + IsLeft : bool = false
    + showGestureColor : bool = false
    + showConficenceAsAlpha : bool = true
}
class HandData {
    + confidence : float = 0
    + HandData()
}
MonoBehaviour <|-- HandRenderer
HandRenderer o-> "pointColor" Color
HandRenderer o-> "linkColor" Color
HandRenderer o-> "colliderType" HandColliderType
HandRenderer +-- HandData
HandData o-> "gesture" WVR_HandGestureType
HandData o-> "position" Vector3
HandData o-> "rotation" Quaternion
@enduml
