@startuml
class ModelRenderer {
    + IsLeft : bool = false
    + showConficenceAsAlpha : bool = false
}
struct JointResult {
    + confidence : float
}
MonoBehaviour <|-- ModelRenderer
ModelRenderer o-> "initialRotation" Vector3
ModelRenderer o-> "Hand" GameObject
ModelRenderer +-- JointResult
JointResult --> "rotation" Quaternion
@enduml
