@startuml
class HumanoidTracking {
    + ContentCalibration : bool <<get>>
    + CustomSettings : bool <<get>> <<set>>
    + AvatarHeight : float <<get>> <<set>>
    + AvatarScale : float <<get>> <<set>>
    + CustomizeExtrinsics : bool <<get>> <<set>>
    + BeginTracking() : void
    + StopTracking() : void
    + StartFixUpdateBodyTracking() : IEnumerator
}
enum TrackingMode {
    Arm= BodyTrackingMode.ARMIK,
    UpperBody= BodyTrackingMode.UPPERBODYIK,
    FullBody= BodyTrackingMode.FULLBODYIK,
    UpperBodyAndLeg= BodyTrackingMode.UPPERIKANDLEGFK,
}
MonoBehaviour <|-- HumanoidTracking
HumanoidTracking --> "Tracking" TrackingMode
HumanoidTracking --> "AvatarOffset" Transform
HumanoidTracking --> "Head" ExtrinsicInfo_t
HumanoidTracking --> "LeftWrist" ExtrinsicInfo_t
HumanoidTracking --> "RightWrist" ExtrinsicInfo_t
HumanoidTracking --> "LeftHandheld" ExtrinsicInfo_t
HumanoidTracking --> "RightHandheld" ExtrinsicInfo_t
HumanoidTracking --> "LeftHand" ExtrinsicInfo_t
HumanoidTracking --> "RightHand" ExtrinsicInfo_t
HumanoidTracking --> "Hips" ExtrinsicInfo_t
HumanoidTracking --> "LeftLowerLeg" ExtrinsicInfo_t
HumanoidTracking --> "RightLowerLeg" ExtrinsicInfo_t
HumanoidTracking --> "LeftFoot" ExtrinsicInfo_t
HumanoidTracking --> "RightFoot" ExtrinsicInfo_t
HumanoidTracking --> "LeftToes" ExtrinsicInfo_t
HumanoidTracking --> "RightToes" ExtrinsicInfo_t
HumanoidTracking +-- TrackingMode
@enduml
