@startuml
class NetworkedTransform_Check {
    + {static} CheckForNetworkTransform(gameObject:GameObject) : void
}
class NetworkedTransform_Editor {
    + OnEnable() : void
    + <<override>> OnInspectorGUI() : void
}
Editor <|-- NetworkedTransform_Editor
@enduml
