@startuml
struct TR {
    + {static} FromWorld(t:Transform) : TR
    + {static} FromParent(t:Transform) : TR
    + {static} FromLocal(t:Transform) : TR
    + {static} FromRelative(t:Transform, from:Transform) : TR
    + TR(r:Quaternion, t:Vector3)
    + TR(r:Quaternion)
    + TR(t:Vector3)
    + TRS(s:float) : Matrix4x4
    + Inverse() : TR
}
TR --> "Rotation" Quaternion
TR --> "Translation" Vector3
TR --> "Identity" TR
@enduml
