@startuml
class ChangeSizeColor {
    + ChangeEffectColor(value:float) : void
    + CheckIsColorChange(value:bool) : void
    + CheckColorState() : void
    + GetIntensityFactor() : void
}
MonoBehaviour <|-- ChangeSizeColor
ChangeSizeColor --> "color" Gradient
ChangeSizeColor --> "m_changeColor" Color
ChangeSizeColor --> "m_obj" GameObject
ChangeSizeColor --> "m_ColorHandler" Image
ChangeSizeColor --> "m_intensityfactor" Text
@enduml
