@startuml
class NewMaterialChange {
    + isParticleSystem : bool
    + m_timeToReduce : float
    + m_reduceFactor : float = 0.0f
    + m_upFactor : float
}
MonoBehaviour <|-- NewMaterialChange
NewMaterialChange --> "m_inputMaterial" Material
@enduml
