@startuml
class VariousTranslateMove {
    + m_power : float
    + m_reduceTime : float
    + m_fowardMove : bool
    + m_rightMove : bool
    + m_upMove : bool
    + m_changedFactor : float
}
MonoBehaviour <|-- VariousTranslateMove
@enduml
