@startuml
class VariousMouseOrbit {
    + distance : float
    + xSpeed : float = 250.0f
    + ySpeed : float = 120.0f
    + yMinLimit : float
    + yMaxLimit : float = 80.0f
    + CameraDist : float = 10
}
MonoBehaviour <|-- VariousMouseOrbit
@enduml
