@startuml
class Pin <<static>> {
    + {static} Create(src:ArraySegment<T>) : Pin<T>
    + {static} Create(src:T[]) : Pin<T>
}
class "Pin`1"<T> {
    + Length : int <<get>>
    + Pin(src:ArraySegment<T>)
    + Dispose() : void
}
class ArrayExtensions <<static>> {
    + {static} SelectInplace(src:T[], pred:Func<T, T>) : T[]
}
class ArraySegmentExtensions <<static>> {
    + {static} Slice(self:ArraySegment<T>, start:int, length:int) : ArraySegment<T>
    + {static} Slice(self:ArraySegment<T>, start:int) : ArraySegment<T>
}
IDisposable <|-- "Pin`1"
"Pin`1" --> "Ptr" IntPtr
@enduml
