@startuml
class NumericsExtensions <<static>> {
    + {static} NearlyEqual(lhs:Vector3, rhs:Vector3) : bool
    + {static} NearlyEqual(lhs:Quaternion, rhs:Quaternion) : bool
    + <<const>> TO_RAD : float
    + {static} ReverseX(src:Vector3) : Vector3
    + {static} ReverseZ(src:Vector3) : Vector3
    + {static} GetAxisAngle(q:Quaternion) : (Vector3, float)
    + {static} ReverseX(src:Quaternion) : Quaternion
    + {static} ReverseZ(src:Quaternion) : Quaternion
    + {static} ExtractPosition(matrix:Matrix4x4) : Vector3
    + {static} ExtractRotation(matrix:Matrix4x4) : Quaternion
    + {static} ExtractScale(matrix:Matrix4x4) : Vector3
    + {static} FromTRS(t:Vector3, r:Quaternion, s:Vector3) : Matrix4x4
    + {static} IsOnlyTranslation(m:Matrix4x4) : bool
}
@enduml
