@startuml
struct PosRot {
    + {static} FromGlobalTransform(t:Transform) : PosRot
}
class BlendShape {
    + Name : string
    + BlendShape(name:string)
}
class UnityExtensions <<static>> {
    + {static} RotateY180(v:Vector4) : Vector4
    + {static} ReverseZ(v:Vector4) : Vector4
    + {static} RotateY180(v:Vector3) : Vector3
    + {static} ReverseZ(v:Vector3) : Vector3
    + {static} ReverseY(v:Vector2) : Vector2
    + {static} ReverseUV(v:Vector2) : Vector2
    + {static} ReverseZ(q:Quaternion) : Quaternion
    + {static} Matrix4x4FromColumns(c0:Vector4, c1:Vector4, c2:Vector4, c3:Vector4) : Matrix4x4
    + {static} Matrix4x4FromRotation(q:Quaternion) : Matrix4x4
    + {static} RotateY180(m:Matrix4x4) : Matrix4x4
    + {static} ReverseZ(m:Matrix4x4) : Matrix4x4
    + {static} MatrixFromArray(values:float[]) : Matrix4x4
    + {static} ExtractRotation(matrix:Matrix4x4) : Quaternion
    + {static} ExtractPosition(matrix:Matrix4x4) : Vector3
    + {static} ExtractScale(matrix:Matrix4x4) : Vector3
    + {static} RelativePathFrom(self:Transform, root:Transform) : string
    + {static} GetChildByName(self:Transform, childName:string) : Transform
    + {static} GetFromPath(self:Transform, path:string) : Transform
    + {static} GetChildren(self:Transform) : IEnumerable<Transform>
    + {static} Traverse(t:Transform) : IEnumerable<Transform>
    + {static} FindDescenedant(t:Transform, name:string) : Transform
    + {static} Ancestors(t:Transform) : IEnumerable<Transform>
    + {static} ToArray(q:Quaternion) : float[]
    + {static} ToArray(v:Vector3) : float[]
    + {static} ToArray(v:Vector4) : float[]
    + {static} ReverseZRecursive(root:Transform) : void
    + {static} GetSharedMesh(t:Transform) : Mesh
    + {static} GetSharedMaterials(t:Transform) : Material[]
    + {static} Has(transform:Transform, t:T) : bool
    + {static} GetOrAddComponent(go:GameObject) : T
}
class "List`1"<T> {
}
PosRot --> "Position" Vector3
PosRot --> "Rotation" Quaternion
BlendShape o-> "Positions<Vector3>" "List`1"
BlendShape o-> "Normals<Vector3>" "List`1"
BlendShape o-> "Tangents<Vector3>" "List`1"
@enduml
