@startuml
class ObjectTracker_Editor {
    + OnEnable() : void
    + OnDisable() : void
    + <<override>> OnInspectorGUI() : void
    + {static} Settings(objectTracker:ObjectTracker) : void
    + OnSceneGUI() : void
}
enum Side {
    Left,
    Right,
}
Editor <|-- ObjectTracker_Editor
ObjectTracker_Editor +-- Side
@enduml
