@startuml
class HumanoidCollisionHandler {
    + OnCollisionEnter(collision:Collision) : void
    + OnTriggerEnter(otherCollider:Collider) : void
    + OnTriggerStay(otherCollider:Collider) : void
    + OnTriggerExit() : void
    + OnCollisionExit(collision:Collision) : void
}
MonoBehaviour <|-- HumanoidCollisionHandler
HumanoidCollisionHandler --> "humanoid" HumanoidControl
@enduml
