@startuml
struct AssetsPath {
    + RelativePath : string <<get>>
    + <<override>> ToString() : string
    + FileName : string <<get>>
    + FileNameWithoutExtension : string <<get>>
    + Extension : string <<get>>
    + Child(name:string) : AssetsPath
    + <<override>> GetHashCode() : int
    + <<override>> Equals(obj:object) : bool
    + FullPath : string <<get>>
    + IsFileExists : bool <<get>>
    + IsDirectoryExists : bool <<get>>
    + {static} FromFullpath(fullPath:string) : AssetsPath
    + TraverseDir() : IEnumerable<AssetsPath>
}
class "IEnumerable`1"<T> {
}
AssetsPath --> "Parent" AssetsPath
AssetsPath --> "ChildDirs<AssetsPath>" "IEnumerable`1"
AssetsPath --> "ChildFiles<AssetsPath>" "IEnumerable`1"
@enduml
