@startuml
enum MeshProcessingMessages {
    TARGET_OBJECT,
    MESH_SEPARATOR,
    MESH_SEPARATOR_BY_BLENDSHAPE,
    MESH_INTEGRATOR,
    BONE_MESH_ERASER,
    SELECT_SKINNED_MESH,
    SELECT_ERASE_ROOT,
    NO_GAMEOBJECT_SELECTED,
    NO_SKINNED_MESH,
    NO_STATIC_MESH,
    NO_MESH,
    VRM_DETECTED,
}
@enduml
