@startuml
class CacheScript {
    + acceptableCollisionDeviation : float = 30
    + OnDestroy() : void
}
class "UnityEvent`1"<T> {
}
'MonoBehaviour <|-- CacheScript
CacheScript --> "collectionEffect" GameObject
CacheScript --> "popEffect" GameObject
CacheScript --> "poppingSound" AudioClip
CacheScript --> "collectingSound" AudioClip
CacheScript --> "extraPointsModifier<int>" "UnityEvent`1"
CacheScript --> "extraSpeedModifier<float>" "UnityEvent`1"
@enduml
