@startuml
class CylinderProgressBar {
    + glowSpeed : float = 3f
    + glowMin : float = 1f
    + glowMax : float = 5f
    + delayDuration : float = 0.3f
}
class "UnityEvent`1"<T> {
}
'MonoBehaviour <|-- CylinderProgressBar
CylinderProgressBar --> "outerBar" GameObject
CylinderProgressBar --> "innerBarRenderer" Renderer
CylinderProgressBar o-> "baseEmissionColor" Color
CylinderProgressBar --> "newLevelReached<int>" "UnityEvent`1"
@enduml
