@startuml
class SpawnedObjectInfo {
    + UUID : string
    + spawnIndex : int
    + spawnPointID : int
    + objectName : string
    + interactionPosition : Vector3? = null
    + interactionAngle : float? = null
    + SpawnedObjectInfo(obj:GameObject, index:int, uuid:string, spawnPoint:int)
    + SetState(newState:ObjectInteractionState, position:Vector3) : void
    + SetState(newState:ObjectInteractionState, position:Vector3, collisionAngle:float) : void
    + GetState() : ObjectInteractionState
}
SpawnedObjectInfo --> "spawnPosition" Vector3
SpawnedObjectInfo --> "spawnRotation" Quaternion
SpawnedObjectInfo o-> "interactionState" ObjectInteractionState
@enduml
