@startuml
class ExpressionEditorHelper <<static>> {
    + {static} StringPopup(rect:Rect, prop:SerializedProperty, options:string[], newIndex:int) : bool
    + {static} EnumPopup(rect:Rect, value:T) : T
    + {static} IntPopup(rect:Rect, prop:SerializedProperty, options:string[], newIndex:int) : bool
    + {static} FloatSlider(rect:Rect, prop:SerializedProperty, maxValue:float) : bool
    + {static} ColorProp(rect:Rect, prop:SerializedProperty) : bool
    + {static} UVProp(rect:Rect, prop:SerializedProperty) : bool
}
class TextureScale {
    + {static} Scale(tex:Texture2D, newWidth:int, newHeight:int) : void
    + {static} GetResized(texture:Texture2D, width:int, height:int) : Texture2D
}
@enduml
