@startuml
class ReorderableMaterialColorBindingList {
    + ReorderableMaterialColorBindingList(serializedObject:SerializedObject, materialNames:string[], height:int)
    + Draw(label:string) : bool
}
@enduml
