@startuml
class SerializedExpressionEditor {
    + IsBinary : bool <<get>>
    + SerializedExpressionEditor(serializedObject:SerializedObject, previewSceneManager:PreviewSceneManager)
    + SerializedExpressionEditor(expression:VRM10Expression, previewSceneManager:PreviewSceneManager)
    + SerializedExpressionEditor(serializedObject:SerializedObject, targetObject:VRM10Expression, previewSceneManager:PreviewSceneManager)
    + Draw(bakeValue:VRM10Expression) : bool
}
class CustomUI <<static>> {
    + {static} Foldout(display:bool, title:string) : bool
}
@enduml
