@startuml
class ArmPredictor {
}
class ArmAnimator {
    + armSwing : bool
    + <<override>> Start(humanoid:HumanoidControl, targetTransform:Transform) : void
    + <<override>> Update() : void
}
@enduml
