@startuml
class LegAnimator {
    + animationSpeed : float = 1
    + velocityAnimationSpeed : bool = false
    + <<override>> Start(humanoid:HumanoidControl, targetTransform:Transform) : void
    + <<override>> Update() : void
    + ResetFoot(com:Vector3) : void
    + isMoving : bool = false
    + f : float = 0
    + prevFrame : int
    + nextFrame : int
    + GetCurrentPosition(step:Vector3, fWithinFrame:float) : Vector3
    + GetCurrentPosition(step:Vector3, fWithinFrame:float, prevFrame:int, nextFrame:int) : Vector3
    + GetCurrentRotation() : Quaternion
}
class KeyFrame {
    + f : float
    + KeyFrame(_fromFrameNr:int, _position:Vector3, _angles:Vector3, totalFrames:float)
}
LegSensor <|-- LegAnimator
LegAnimator o-> "scale" Vector3
LegAnimator +-- KeyFrame
KeyFrame --> "position" Vector3
KeyFrame --> "rotation" Quaternion
@enduml
