@startuml
class ImporterContext {
}
class BvhImporterContext {
    + Parse() : void
    + Parse(path:string) : void
    + Parse(path:string, source:string) : void
    + Load() : void
    + Destroy(destroySubAssets:bool) : void
}
class "List`1"<T> {
}
BvhImporterContext <|-- ImporterContext
BvhImporterContext --> "Path" String
BvhImporterContext --> "Source" String
BvhImporterContext --> "Bvh" Bvh
BvhImporterContext --> "Root" GameObject
BvhImporterContext o-> "Nodes<Transform>" "List`1"
BvhImporterContext --> "Animation" AnimationClip
BvhImporterContext --> "AvatarDescription" AvatarDescription
BvhImporterContext --> "Avatar" Avatar
BvhImporterContext --> "Mesh" Mesh
BvhImporterContext --> "Material" Material
@enduml
