@startuml
class BoneSelector {
    + BoneSelector(camera:Camera)
    + Dispose() : void
    + SetTarget(activeGameObject:GameObject) : void
    + IntersectBone(ray:Ray, isHover:bool) : GameObject
    + Draw() : void
}
struct HitResult {
    + s : float
    + Distance() : float
}
IDisposable <|-- BoneSelector
BoneSelector --> "CurrentAnimator" Animator
BoneSelector --> "SelectedBoneInfo" BoneInfo
BoneSelector --> "HoverBoneInfo" BoneInfo
BoneSelector +-- HitResult
HitResult --> "pos1" Vector3
HitResult --> "pos2" Vector3
@enduml
