@startuml
class PreviewMeshItem <<sealed>> {
    + Path : string <<get>>
    + BlendShapeCount : int <<get>>
    + Bake(values:IEnumerable<MorphTargetBinding>, weight:float) : void
    + {static} Create(t:Transform, root:Transform, getOrCreateMaterial:Func<Material, Material>) : PreviewMeshItem
}
PreviewMeshItem --> "SkinnedMeshRenderer" SkinnedMeshRenderer
PreviewMeshItem --> "Mesh" Mesh
PreviewMeshItem --> "Position" Vector3
PreviewMeshItem --> "Rotation" Quaternion
@enduml
