@startuml
struct CopyIndicesJobs {
}
struct UInt2UInt {
    + UInt2UInt(vertexOffset:uint, source:NativeSlice<uint>, destination:NativeSlice<uint>)
    + Execute(index:int) : void
}
struct Ushort2Uint {
    + Ushort2Uint(vertexOffset:uint, source:NativeSlice<ushort>, destination:NativeSlice<uint>)
    + Execute(index:int) : void
}
struct Ushort2Ushort {
    + Ushort2Ushort(vertexOffset:ushort, source:NativeSlice<ushort>, destination:NativeSlice<ushort>)
    + Execute(index:int) : void
}
struct Uint2Ushort {
    + Uint2Ushort(vertexOffset:ushort, source:NativeSlice<uint>, destination:NativeSlice<ushort>)
    + Execute(index:int) : void
}
CopyIndicesJobs +-- UInt2UInt
IJobParallelFor <|-- UInt2UInt
CopyIndicesJobs +-- Ushort2Uint
IJobParallelFor <|-- Ushort2Uint
CopyIndicesJobs +-- Ushort2Ushort
IJobParallelFor <|-- Ushort2Ushort
CopyIndicesJobs +-- Uint2Ushort
IJobParallelFor <|-- Uint2Ushort
@enduml
