@startuml
class ModelExporter {
    + Export(arrayManager:INativeArrayManager, root:GameObject) : VrmLib.Model
}
class "Dictionary`2"<T1,T2> {
}
class "List`1"<T> {
}
ModelExporter o-> "Nodes<GameObject,VrmLib.Node>" "Dictionary`2"
ModelExporter o-> "Materials<UnityEngine.Material>" "List`1"
ModelExporter o-> "Meshes<UnityEngine.Mesh,VrmLib.MeshGroup>" "Dictionary`2"
@enduml
