@startuml
class GltfDeserializer <<static>> {
    + {static} TryGet(src:UniGLTF.glTFExtension, extension:VRMC_materials_mtoon) : bool
    + {static} Deserialize(parsed:JsonNode) : VRMC_materials_mtoon
    + {static} Deserialize_ShadeColorFactor(parsed:JsonNode) : float[]
    + {static} Deserialize_ShadeMultiplyTexture(parsed:JsonNode) : TextureInfo
    + {static} Deserialize_ShadingShiftTexture(parsed:JsonNode) : ShadingShiftTextureInfo
    + {static} Deserialize_MatcapFactor(parsed:JsonNode) : float[]
    + {static} Deserialize_MatcapTexture(parsed:JsonNode) : TextureInfo
    + {static} Deserialize_ParametricRimColorFactor(parsed:JsonNode) : float[]
    + {static} Deserialize_RimMultiplyTexture(parsed:JsonNode) : TextureInfo
    + {static} Deserialize_OutlineWidthMultiplyTexture(parsed:JsonNode) : TextureInfo
    + {static} Deserialize_OutlineColorFactor(parsed:JsonNode) : float[]
    + {static} Deserialize_UvAnimationMaskTexture(parsed:JsonNode) : TextureInfo
}
GltfDeserializer o-> "ExtensionNameUtf8" Utf8String
@enduml
