@startuml
class CalibrationPoint {
    + leftDetected : bool = false
    + rightDetected : bool = false
    + rotationMargin : float = 5
    + positionMargin : float = 0.01F
    + StartCalibrate() : void
}
MonoBehaviour <|-- CalibrationPoint
CalibrationPoint --> "leftCalibrationPoint" Transform
CalibrationPoint --> "rightCalibrationPoint" Transform
@enduml
