@startuml
class ColoringInteractionPointer {
}
InteractionPointer <|-- ColoringInteractionPointer
ColoringInteractionPointer --> "validMaterial" Material
ColoringInteractionPointer --> "invalidMaterial" Material
@enduml
