@startuml
class MenuManager {
    + menuDistance : float = 0.5F
    + SetMenuActive(active:bool) : void
}
MonoBehaviour <|-- MenuManager
MenuManager --> "humanoid" HumanoidControl
MenuManager --> "leftMenuPointer" InteractionPointer
MenuManager --> "rightMenuPointer" InteractionPointer
MenuManager --> "leftTeleporter" InteractionPointer
MenuManager --> "rightTeleporter" InteractionPointer
@enduml
