@startuml
class GltfTextureDescriptorGenerator <<sealed>> {
    + GltfTextureDescriptorGenerator(data:GltfData)
    + Get() : TextureDescriptorSet
}
ITextureDescriptorGenerator <|-- GltfTextureDescriptorGenerator
@enduml
