@startuml
class GltfTextureExporter <<static>> {
    + {static} PushGltfTexture(data:ExportingGltfData, texture:Texture2D, textureColorSpace:ColorSpace, textureSerializer:ITextureSerializer) : int
}
@enduml
