@startuml
enum ErrorLevels {
    Info,
    Warning,
    Error,
    Critical,
}
struct ValidationContext {
    + {static} Create(c:T) : ValidationContext
    + {static} Create(extended:Action) : ValidationContext
}
struct Validation {
    + CanExport : bool <<get>>
    + {static} Critical(msg:string, context:ValidationContext) : Validation
    + {static} Error(msg:string, context:ValidationContext) : Validation
    + {static} Warning(msg:string, context:ValidationContext) : Validation
    + {static} Info(msg:string, context:ValidationContext) : Validation
    + AddTo(dst:IList<Validation>) : void
}
ValidationContext --> "Type" Type
ValidationContext --> "Extended" Action
Validation --> "ErrorLevel" ErrorLevels
Validation --> "Message" String
Validation --> "Context" ValidationContext
@enduml
