@startuml
class GlbLowLevelParser <<sealed>> {
    + {static} <<readonly>> UniqueFixResourceSuffix : string = "__UNIGLTF__DUPLICATED__"
    + GlbLowLevelParser(path:string, specifiedBinary:byte[])
    + Parse() : GltfData
    + {static} ParseGlbChunks(data:byte[]) : List<GlbChunk>
    + {static} ParseGltf(path:string, json:string, chunks:IReadOnlyList<GlbChunk>, storage:IStorage, migrationFlags:MigrationFlags) : GltfData
    + {static} PrepareUri(uri:string) : string
    + {static} AppendImageExtension(texture:glTFImage, extension:string) : void
    + {static} FixNameUnique(used:HashSet<string>, originalName:string) : string
    + {static} TryGetOriginalName(name:string, originalName:string) : bool
}
@enduml
