@startuml
struct EuclideanTransform {
    + EuclideanTransform(rotation:Quaternion, translation:Vector3)
    + EuclideanTransform(rotation:Quaternion)
    + EuclideanTransform(translation:Vector3)
    + EuclideanTransform(matrix:Matrix4x4)
}
EuclideanTransform --> "Rotation" Quaternion
EuclideanTransform --> "Translation" Vector3
@enduml
