@startuml
class ByteBuffer {
    + ByteBuffer()
    + ByteBuffer(buffer:Byte[])
    + Count : int <<get>>
    + Remain : int <<get>>
    + Push(b:Byte) : void
    + Push(buffer:Byte[]) : void
    + Push(buffer:ArraySegment<Byte>) : void
    + Unshift(size:int) : void
}
class "ArraySegment`1"<T> {
}
ByteBuffer --> "Bytes<Byte>" "ArraySegment`1"
@enduml
