@startuml
class ConcreteCast <<static>> <<partial>> {
    + {static} CastByteToByte(src:Byte) : Byte
    + {static} CastByteToUInt16(src:Byte) : UInt16
    + {static} CastByteToUInt32(src:Byte) : UInt32
    + {static} CastByteToUInt64(src:Byte) : UInt64
    + {static} CastByteToSByte(src:Byte) : SByte
    + {static} CastByteToInt16(src:Byte) : Int16
    + {static} CastByteToInt32(src:Byte) : Int32
    + {static} CastByteToInt64(src:Byte) : Int64
    + {static} CastByteToSingle(src:Byte) : Single
    + {static} CastByteToDouble(src:Byte) : Double
    + {static} CastUInt16ToByte(src:UInt16) : Byte
    + {static} CastUInt16ToUInt16(src:UInt16) : UInt16
    + {static} CastUInt16ToUInt32(src:UInt16) : UInt32
    + {static} CastUInt16ToUInt64(src:UInt16) : UInt64
    + {static} CastUInt16ToSByte(src:UInt16) : SByte
    + {static} CastUInt16ToInt16(src:UInt16) : Int16
    + {static} CastUInt16ToInt32(src:UInt16) : Int32
    + {static} CastUInt16ToInt64(src:UInt16) : Int64
    + {static} CastUInt16ToSingle(src:UInt16) : Single
    + {static} CastUInt16ToDouble(src:UInt16) : Double
    + {static} CastUInt32ToByte(src:UInt32) : Byte
    + {static} CastUInt32ToUInt16(src:UInt32) : UInt16
    + {static} CastUInt32ToUInt32(src:UInt32) : UInt32
    + {static} CastUInt32ToUInt64(src:UInt32) : UInt64
    + {static} CastUInt32ToSByte(src:UInt32) : SByte
    + {static} CastUInt32ToInt16(src:UInt32) : Int16
    + {static} CastUInt32ToInt32(src:UInt32) : Int32
    + {static} CastUInt32ToInt64(src:UInt32) : Int64
    + {static} CastUInt32ToSingle(src:UInt32) : Single
    + {static} CastUInt32ToDouble(src:UInt32) : Double
    + {static} CastUInt64ToByte(src:UInt64) : Byte
    + {static} CastUInt64ToUInt16(src:UInt64) : UInt16
    + {static} CastUInt64ToUInt32(src:UInt64) : UInt32
    + {static} CastUInt64ToUInt64(src:UInt64) : UInt64
    + {static} CastUInt64ToSByte(src:UInt64) : SByte
    + {static} CastUInt64ToInt16(src:UInt64) : Int16
    + {static} CastUInt64ToInt32(src:UInt64) : Int32
    + {static} CastUInt64ToInt64(src:UInt64) : Int64
    + {static} CastUInt64ToSingle(src:UInt64) : Single
    + {static} CastUInt64ToDouble(src:UInt64) : Double
    + {static} CastSByteToByte(src:SByte) : Byte
    + {static} CastSByteToUInt16(src:SByte) : UInt16
    + {static} CastSByteToUInt32(src:SByte) : UInt32
    + {static} CastSByteToUInt64(src:SByte) : UInt64
    + {static} CastSByteToSByte(src:SByte) : SByte
    + {static} CastSByteToInt16(src:SByte) : Int16
    + {static} CastSByteToInt32(src:SByte) : Int32
    + {static} CastSByteToInt64(src:SByte) : Int64
    + {static} CastSByteToSingle(src:SByte) : Single
    + {static} CastSByteToDouble(src:SByte) : Double
    + {static} CastInt16ToByte(src:Int16) : Byte
    + {static} CastInt16ToUInt16(src:Int16) : UInt16
    + {static} CastInt16ToUInt32(src:Int16) : UInt32
    + {static} CastInt16ToUInt64(src:Int16) : UInt64
    + {static} CastInt16ToSByte(src:Int16) : SByte
    + {static} CastInt16ToInt16(src:Int16) : Int16
    + {static} CastInt16ToInt32(src:Int16) : Int32
    + {static} CastInt16ToInt64(src:Int16) : Int64
    + {static} CastInt16ToSingle(src:Int16) : Single
    + {static} CastInt16ToDouble(src:Int16) : Double
    + {static} CastInt32ToByte(src:Int32) : Byte
    + {static} CastInt32ToUInt16(src:Int32) : UInt16
    + {static} CastInt32ToUInt32(src:Int32) : UInt32
    + {static} CastInt32ToUInt64(src:Int32) : UInt64
    + {static} CastInt32ToSByte(src:Int32) : SByte
    + {static} CastInt32ToInt16(src:Int32) : Int16
    + {static} CastInt32ToInt32(src:Int32) : Int32
    + {static} CastInt32ToInt64(src:Int32) : Int64
    + {static} CastInt32ToSingle(src:Int32) : Single
    + {static} CastInt32ToDouble(src:Int32) : Double
    + {static} CastInt64ToByte(src:Int64) : Byte
    + {static} CastInt64ToUInt16(src:Int64) : UInt16
    + {static} CastInt64ToUInt32(src:Int64) : UInt32
    + {static} CastInt64ToUInt64(src:Int64) : UInt64
    + {static} CastInt64ToSByte(src:Int64) : SByte
    + {static} CastInt64ToInt16(src:Int64) : Int16
    + {static} CastInt64ToInt32(src:Int64) : Int32
    + {static} CastInt64ToInt64(src:Int64) : Int64
    + {static} CastInt64ToSingle(src:Int64) : Single
    + {static} CastInt64ToDouble(src:Int64) : Double
    + {static} CastSingleToByte(src:Single) : Byte
    + {static} CastSingleToUInt16(src:Single) : UInt16
    + {static} CastSingleToUInt32(src:Single) : UInt32
    + {static} CastSingleToUInt64(src:Single) : UInt64
    + {static} CastSingleToSByte(src:Single) : SByte
    + {static} CastSingleToInt16(src:Single) : Int16
    + {static} CastSingleToInt32(src:Single) : Int32
    + {static} CastSingleToInt64(src:Single) : Int64
    + {static} CastSingleToSingle(src:Single) : Single
    + {static} CastSingleToDouble(src:Single) : Double
    + {static} CastDoubleToByte(src:Double) : Byte
    + {static} CastDoubleToUInt16(src:Double) : UInt16
    + {static} CastDoubleToUInt32(src:Double) : UInt32
    + {static} CastDoubleToUInt64(src:Double) : UInt64
    + {static} CastDoubleToSByte(src:Double) : SByte
    + {static} CastDoubleToInt16(src:Double) : Int16
    + {static} CastDoubleToInt32(src:Double) : Int32
    + {static} CastDoubleToInt64(src:Double) : Int64
    + {static} CastDoubleToSingle(src:Double) : Single
    + {static} CastDoubleToDouble(src:Double) : Double
}
@enduml
