@startuml
class TreeValueException {
}
class ParserException {
    + ParserException(msg:string)
}
class DeserializationException {
    + DeserializationException(msg:string)
}
class FormatterException {
    + FormatterException(msg:string)
}
ArgumentException <|-- TreeValueException
TreeValueException <|-- ParserException
TreeValueException <|-- DeserializationException
TreeValueException <|-- FormatterException
@enduml
