@startuml
interface IFileSystemAccessor {
}
class FileSystemAccessor {
    + FileSystemAccessor(path:string)
    + <<override>> ToString() : string
    + ReadAllText() : string
    + ReadAllText(relativePath:string) : string
    + Get(relativePath:string) : IFileSystemAccessor
}
IFileSystemAccessor <|-- FileSystemAccessor
@enduml
