@startuml
class AnimationValidator <<static>> {
    + {static} Validate(root:GameObject) : IEnumerable<Validation>
}
enum ExporterValidatorMessages {
    ROOT_ANIMATED,
}
AnimationValidator +-- ExporterValidatorMessages
@enduml
