@startuml
class NormalizeTests {
    + MapBoneWeightTest() : void
}
class BoneMap {
    + Add(src:GameObject, dst:GameObject) : void
    + CreateBoneWeight(vertexCount:int) : IEnumerable<BoneWeight>
}
class "List`1"<T> {
}
class "Dictionary`2"<T1,T2> {
}
NormalizeTests +-- BoneMap
BoneMap o-> "SrcBones<Transform>" "List`1"
BoneMap o-> "DstBones<Transform>" "List`1"
BoneMap o-> "Map<Transform,Transform>" "Dictionary`2"
@enduml
