@startuml
class ToJsonExtensions <<static>> {
    + {static} ToJson(self:glTF) : string
    + {static} ToJson(self:glTFMesh) : string
    + {static} ToJson(self:glTFPrimitives) : string
    + {static} ToJson(self:glTFAttributes) : string
    + {static} ToJson(self:glTFMaterialBaseColorTextureInfo) : string
    + {static} ToJson(self:glTFMaterial) : string
    + {static} ToJson(self:glTFNode) : string
    + {static} ToJson(self:glTFSkin) : string
    + {static} ToJson(self:glTF_VRM_MaterialValueBind) : string
    + {static} ToJson(self:glTF_VRM_BlendShapeBind) : string
    + {static} ToJson(self:glTF_VRM_BlendShapeGroup) : string
    + {static} ToJson(self:glTF_VRM_DegreeMap) : string
    + {static} ToJson(self:glTF_VRM_MeshAnnotation) : string
    + {static} ToJson(self:glTF_VRM_Firstperson) : string
    + {static} ToJson(self:glTF_VRM_HumanoidBone) : string
    + {static} ToJson(self:glTF_VRM_Humanoid) : string
    + {static} ToJson(self:glTF_VRM_Material) : string
    + {static} ToJson(self:glTF_VRM_Meta) : string
    + {static} ToJson(self:glTF_VRM_SecondaryAnimationCollider) : string
    + {static} ToJson(self:glTF_VRM_SecondaryAnimationColliderGroup) : string
    + {static} ToJson(self:glTF_VRM_SecondaryAnimationGroup) : string
    + {static} ToJson(self:glTF_VRM_SecondaryAnimation) : string
}
class UniVRMSerializeTests {
    + MaterialValueBindTest() : void
    + BlendShapeBindTest() : void
    + BlendShapeBindTestError() : void
    + BlendShapeGroupTest() : void
    + BlendShapeGroupTestError() : void
    + BlendShapePresetInvariantCultureTest() : void
    + DegreeMapTest() : void
    + MeshAnnotationTest() : void
    + FirstPersonTest() : void
    + HumanoidBoneTest() : void
    + HumanoidBoneTestError() : void
    + HumanoidTest() : void
    + MaterialTest() : void
    + MetaTest() : void
    + MetaTestError() : void
    + MetaDeserializeTest() : void
    + SecondaryAnimationColliderTest() : void
    + SecondaryAnimationColliderGroupTest() : void
    + SecondaryAnimationColliderGroupTestError() : void
    + SecondaryAnimationGroupTest() : void
    + SecondaryAnimationGroupTestErrorBones() : void
    + SecondaryAnimationGroupTestErrorColliderGroups() : void
    + SecondaryAnimationTest() : void
    + ExtensionsTest() : void
}
@enduml
