@startuml
class AnimatorPoseProvider <<sealed>> {
    + AnimatorPoseProvider(root:Transform, animator:Animator)
}
INormalizedPoseProvider <|-- AnimatorPoseProvider
ITPoseProvider <|-- AnimatorPoseProvider
@enduml
