@startuml
struct BoneInitialRotation {
    + BoneInitialRotation(transform:Transform)
}
BoneInitialRotation --> "Transform" Transform
BoneInitialRotation --> "InitialLocalPosition" Vector3
BoneInitialRotation --> "InitialLocalRotation" Quaternion
BoneInitialRotation --> "InitialGlobalRotation" Quaternion
BoneInitialRotation --> "NormalizedLocalRotation" Quaternion
@enduml
