@startuml
class ArmRangeOfMotion {
    + AngleByRotation() : void
}
MonoBehaviour <|-- ArmRangeOfMotion
ArmRangeOfMotion o-> "trackerElbowRight" GameObject
ArmRangeOfMotion o-> "trackerElbowLeft" GameObject
ArmRangeOfMotion o-> "trackerChest" GameObject
ArmRangeOfMotion o-> "controllerRight" GameObject
ArmRangeOfMotion o-> "controllerLeft" GameObject
@enduml
