@startuml
class TransformRegistry <<sealed>> {
    + SubscribeOnValueChanged(action:Action) : void
    + UnSubscribeOnValueChanged(action:Action) : void
    + Register(nativeTransform:NativeTransform, synchronizationType:TransformSynchronizationType) : void
    + Unregister(nativeTransform:NativeTransform) : void
}
class "IReadOnlyList`1"<T> {
}
TransformRegistry --> "Transforms<NativeTransform>" "IReadOnlyList`1"
TransformRegistry --> "PullTargets<NativeTransform>" "IReadOnlyList`1"
TransformRegistry --> "PushTargets<NativeTransform>" "IReadOnlyList`1"
@enduml
