@startuml
class Vrm10SerializerGenerator <<static>> {
    + {static} Run(debug:bool) : void
}
struct GenerateInfo {
    + JsonSchema : string
    + FormatDir : string
    + SerializerDir : string
    + GenerateInfo(jsonSchema:string, formatDir:string, serializerDir:string)
    + GenerateInfo(jsonSchema:string, formatDir:string)
}
Vrm10SerializerGenerator +-- GenerateInfo
@enduml
