@startuml
class BodyTrackingSample {
    + SetArmMode() : void
    + SetUpperMode() : void
    + SetFullMode() : void
    + SetUpperBodyAndLegMode() : void
    + BeginTracking() : void
    + StopTracking() : void
}
MonoBehaviour <|-- BodyTrackingSample
BodyTrackingSample --> "inputBody" Body
@enduml
