@startuml
class BTDemoHelper <<static>> {
    + {static} Name(mode:TrackingMode) : string
}
enum TrackingMode {
    Arm= BodyTrackingMode.ARMIK,
    UpperBody= BodyTrackingMode.UPPERBODYIK,
    FullBody= BodyTrackingMode.FULLBODYIK,
    UpperBodyAndLeg= BodyTrackingMode.UPPERIKANDLEGFK,
}
BTDemoHelper +-- TrackingMode
@enduml
