@startuml
class DefaultTrackedDeviceExtrinsics {
}
MonoBehaviour <|-- DefaultTrackedDeviceExtrinsics
DefaultTrackedDeviceExtrinsics o-> "hipPosition" Vector3
DefaultTrackedDeviceExtrinsics o-> "hipRotation" Quaternion
DefaultTrackedDeviceExtrinsics o-> "leftWristPosition" Vector3
DefaultTrackedDeviceExtrinsics o-> "leftWristRotation" Quaternion
DefaultTrackedDeviceExtrinsics o-> "rightWristPosition" Vector3
DefaultTrackedDeviceExtrinsics o-> "rightWristRotation" Quaternion
DefaultTrackedDeviceExtrinsics o-> "headPosition" Vector3
DefaultTrackedDeviceExtrinsics o-> "headRotation" Quaternion
DefaultTrackedDeviceExtrinsics o-> "leftAnklePosition" Vector3
DefaultTrackedDeviceExtrinsics o-> "leftAnkleRotation" Quaternion
DefaultTrackedDeviceExtrinsics o-> "rightAnklePosition" Vector3
DefaultTrackedDeviceExtrinsics o-> "rightAnkleRotation" Quaternion
@enduml
