@startuml
class DevicesTracking {
}
enum ShowingDevice {
    DeviceID= 1,
    DeviceRole= 2,
}
MonoBehaviour <|-- DevicesTracking
DevicesTracking --> "Showing" ShowingDevice
DevicesTracking o-> "RightElbow" GameObject
DevicesTracking o-> "LeftElbow" GameObject
DevicesTracking o-> "Chest" GameObject
DevicesTracking o-> "Waist" GameObject
DevicesTracking o-> "RightFoot" GameObject
DevicesTracking o-> "LeftFoot" GameObject
DevicesTracking +-- ShowingDevice
@enduml
