@startuml
class VRMImporterContext {
    + VRMImporterContext(data:VRMData, externalObjectMap:IReadOnlyDictionary<SubAssetKey, Object>, textureDeserializer:ITextureDeserializer, materialGenerator:IMaterialDescriptorGenerator, loadAnimation:bool)
    + <<async>> ReadMetaAsync(awaitCaller:IAwaitCaller, createThumbnail:bool) : Task<VRMMetaObject>
    + <<override>> TransferOwnership(take:TakeResponsibilityForDestroyObjectFunc) : void
    + <<override>> Dispose() : void
}
ImporterContext <|-- VRMImporterContext
VRMImporterContext --> "HumanoidAvatar" Avatar
VRMImporterContext --> "BlendShapeAvatar" BlendShapeAvatar
VRMImporterContext --> "Meta" VRMMetaObject
@enduml
