@startuml
class VRM10SpringBoneColliderGroup {
    + Name : string
    + GUIName(i:int) : string
}
class "List`1"<T> {
}
MonoBehaviour <|-- VRM10SpringBoneColliderGroup
VRM10SpringBoneColliderGroup o-> "Colliders<VRM10SpringBoneCollider>" "List`1"
@enduml
