@startuml
enum VRM10SpringBoneColliderTypes {
    Sphere,
    Capsule,
}
class VRM10SpringBoneCollider {
    + Radius : float
    + {static} SelectedGuid : int
    + IsSelected : bool <<get>>
    + OnDrawGizmosSelected() : void
}
MonoBehaviour <|-- VRM10SpringBoneCollider
VRM10SpringBoneCollider --> "ColliderType" VRM10SpringBoneColliderTypes
VRM10SpringBoneCollider --> "Offset" Vector3
VRM10SpringBoneCollider --> "Tail" Vector3
@enduml
